// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_opendir(SB), $56-16
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	LEAQ -8(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL ·DirOpen(SB)
_Ltmp0:
	MOVQ SP, AX
	MOVL 16(AX), AX
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_3
	MOVL AX, -20(BP)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp1:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVL -20(BP), CX
	MOVL CX, 0(AX)
_LBB0_2:
	XORL AX, AX
	JMP _LBB0_6
_LBB0_3:
	MOVQ SP, AX
	MOVQ ·_typeinfo_mlib_DIR(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000120
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp2:
	MOVQ SP, AX
	MOVQ 16(AX), CX
	MOVQ -8(BP), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB0_4
	MOVQ AX, 0(CX)
	MOVQ CX, AX
_LBB0_6:
	MOVQ AX, 24(BP)
	RET
_LBB0_4:
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL ·DirClose(SB)
_Ltmp3:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp4:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x000c00c7
	BYTE $0x00
	BYTE $0x00
	JMP _LBB0_2
_Lfunc_end0:
	FUNCDATA $0, gclocals·25fa9a62766576b7(SB)
DATA gclocals·25fa9a62766576b7+0(SB)/4, $4
DATA gclocals·25fa9a62766576b7+4(SB)/4, $2
DATA gclocals·25fa9a62766576b7+8(SB)/1, $0x01
DATA gclocals·25fa9a62766576b7+9(SB)/1, $0x01
DATA gclocals·25fa9a62766576b7+10(SB)/1, $0x01
DATA gclocals·25fa9a62766576b7+11(SB)/1, $0x01
GLOBL gclocals·25fa9a62766576b7(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·d9d8058410cbe076(SB)
DATA gclocals·d9d8058410cbe076+0(SB)/4, $4
DATA gclocals·d9d8058410cbe076+4(SB)/4, $7
DATA gclocals·d9d8058410cbe076+8(SB)/1, $0x00
DATA gclocals·d9d8058410cbe076+9(SB)/1, $0x60
DATA gclocals·d9d8058410cbe076+10(SB)/1, $0x40
DATA gclocals·d9d8058410cbe076+11(SB)/1, $0x20
GLOBL gclocals·d9d8058410cbe076(SB), DUPOK|RODATA, $12

TEXT ·mlib_readdir(SB), $56-16
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	MOVQ 0(AX), CX
	ADDQ $8, AX
	MOVQ AX, -16(BP)
	MOVQ CX, -24(BP)
	MOVQ SP, DX
	MOVQ AX, 8(DX)
	MOVQ CX, 0(DX)
	PCDATA $1, $1
	CALL ·DirRead(SB)
_Ltmp5:
	MOVQ SP, AX
	MOVL 16(AX), AX
	BYTE $0x85
	BYTE $0xc0
	JLE _LBB1_2
	MOVQ -16(BP), AX
	JMP _LBB1_5
_LBB1_2:
	JPL _LBB1_4
	BYTE $0xf7
	BYTE $0xd8
	MOVL AX, -4(BP)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp6:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVL -4(BP), CX
	MOVL CX, 0(AX)
_LBB1_4:
	XORL AX, AX
_LBB1_5:
	MOVQ AX, 24(BP)
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·e1ed1c6d4bb0c637(SB)
DATA gclocals·e1ed1c6d4bb0c637+0(SB)/4, $2
DATA gclocals·e1ed1c6d4bb0c637+4(SB)/4, $2
DATA gclocals·e1ed1c6d4bb0c637+8(SB)/1, $0x01
DATA gclocals·e1ed1c6d4bb0c637+9(SB)/1, $0x01
GLOBL gclocals·e1ed1c6d4bb0c637(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·93005c6ea5fa7700(SB)
DATA gclocals·93005c6ea5fa7700+0(SB)/4, $2
DATA gclocals·93005c6ea5fa7700+4(SB)/4, $7
DATA gclocals·93005c6ea5fa7700+8(SB)/1, $0x00
DATA gclocals·93005c6ea5fa7700+9(SB)/1, $0x30
GLOBL gclocals·93005c6ea5fa7700(SB), DUPOK|RODATA, $10

TEXT ·mlib_readdir_r(SB), $56-32
	PCDATA $1, $-1
	MOVQ 32(BP), AX
	MOVQ 24(BP), CX
	MOVQ 16(BP), DX
	MOVQ 0(DX), DX
	MOVQ CX, -16(BP)
	MOVQ DX, -24(BP)
	MOVQ AX, -8(BP)
	MOVQ SP, AX
	MOVQ CX, 8(AX)
	MOVQ DX, 0(AX)
	PCDATA $1, $1
	CALL ·DirRead(SB)
_Ltmp7:
	MOVQ SP, AX
	MOVL 16(AX), DX
	MOVQ -8(BP), AX
	MOVL DX, CX
	BYTE $0xf7
	BYTE $0xd9
	BYTE $0x85
	BYTE $0xd2
	JLE _LBB2_1
	MOVQ -16(BP), SI
	JMP _LBB2_3
_LBB2_1:
	XORL SI, SI
_LBB2_3:
	SARL $31, DX
	ANDL CX, DX
	MOVQ SI, 0(AX)
	MOVL DX, 40(BP)
	RET
_Lfunc_end2:
	FUNCDATA $0, gclocals·28c71e076fd2fcb1(SB)
DATA gclocals·28c71e076fd2fcb1+0(SB)/4, $2
DATA gclocals·28c71e076fd2fcb1+4(SB)/4, $4
DATA gclocals·28c71e076fd2fcb1+8(SB)/1, $0x07
DATA gclocals·28c71e076fd2fcb1+9(SB)/1, $0x07
GLOBL gclocals·28c71e076fd2fcb1(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·93009c6ea5fae3c0(SB)
DATA gclocals·93009c6ea5fae3c0+0(SB)/4, $2
DATA gclocals·93009c6ea5fae3c0+4(SB)/4, $7
DATA gclocals·93009c6ea5fae3c0+8(SB)/1, $0x00
DATA gclocals·93009c6ea5fae3c0+9(SB)/1, $0x70
GLOBL gclocals·93009c6ea5fae3c0(SB), DUPOK|RODATA, $10

TEXT ·mlib_closedir(SB), $40-16
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	MOVQ 0(AX), CX
	LONG $0x0000c748
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	MOVQ CX, -16(BP)
	MOVQ SP, AX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·DirClose(SB)
_Ltmp8:
	MOVQ SP, AX
	MOVL 8(AX), AX
	XORL CX, CX
	BYTE $0x85
	BYTE $0xc0
	JPL _LBB3_2
	BYTE $0xf7
	BYTE $0xd8
	MOVL AX, -4(BP)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp9:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVL -4(BP), CX
	MOVL CX, 0(AX)
	MOVL $-1, CX
_LBB3_2:
	MOVL CX, 24(BP)
	RET
_Lfunc_end3:
	FUNCDATA $0, gclocals·e1ed1c6d4bb0c637(SB)
	FUNCDATA $1, gclocals·4c2d5cd481de629a(SB)
DATA gclocals·4c2d5cd481de629a+0(SB)/4, $2
DATA gclocals·4c2d5cd481de629a+4(SB)/4, $5
DATA gclocals·4c2d5cd481de629a+8(SB)/1, $0x00
DATA gclocals·4c2d5cd481de629a+9(SB)/1, $0x08
GLOBL gclocals·4c2d5cd481de629a(SB), DUPOK|RODATA, $10

TEXT ·mlib_rewinddir(SB), $40-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	MOVQ 0(AX), AX
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL ·DirRewind(SB)
_Ltmp10:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	JPL _LBB4_2
	BYTE $0xf7
	BYTE $0xd8
	MOVL AX, -4(BP)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp11:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVL -4(BP), CX
	MOVL CX, 0(AX)
_LBB4_2:
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·4c2d5cd481de629a(SB)
