//go:build windows && amd64 && go1.25

// Code generated by c2go-bind. DO NOT EDIT.
// Input-derived material retains the input's copyright and license. This file
// also contains original C2Go runtime-support code copied from c2go-bind,
// available under AGPL-3.0-only or a separate commercial agreement.
// See https://github.com/c2gohq/c2go_bind/blob/main/LICENSING.md.

package mlib

import (
	_ "github.com/c2gohq/c2go_libc"
	"reflect"
	"unsafe"
)

// ─── Types ──────────────────────────────────────────────────
type _c2go_mlib_FILE struct {
	_raw                 [32]uint64
	_cookie_raw          [8]uint64
	_buffer_root         *byte
	_object_root         unsafe.Pointer
	_result_pointer_slot unsafe.Pointer
	_result_size_slot    unsafe.Pointer
	_lock_state          unsafe.Pointer
	_memory_pos          uint64
	_memory_len          uint64
	_memory_space        uint64
	_prev                *_c2go_mlib_FILE
	_next                *_c2go_mlib_FILE
	_active              int32
	_listed              int32
}
type mlib_DIR struct {
	_state unsafe.Pointer
	_entry [280]int8
}
type mlib_cookie_io_functions_t struct {
	read  uintptr
	write uintptr
	seek  uintptr
	close uintptr
}
type mlib_dirent_slot struct {
	value *dirent
}
type mlib_glob_slot struct {
	value *byte
}
type mlib_glob_t struct {
	gl_pathc uint64
	gl_pathv **byte
	gl_offs  uint64
	__dummy1 int32
	__dummy2 [5]uint64
}
type mlib_match struct {
	next *mlib_match
	name *byte
}

// ─── Forward-only opaque types ───────────────────
// Types declared in C as `typedef struct X X;` without a
// matching definition in any c2go-compiled TU. Emitted as
// zero-size opaque structs; pointers to them remain valid
// handles but contents are inaccessible from Go-side code.
type dirent struct{}

// ─── Type-descriptor indirection (#218) ──────
// clang's Plan 9 .s loads each type descriptor from the per-type
// _typeinfo_<X> var below; each caches the *runtime._type computed
// once at init via reflect.TypeFor[T] (no value construction).
var (
	_typeinfo__c2go_mlib_FILE  unsafe.Pointer
	_typeinfo_mlib_DIR         unsafe.Pointer
	_typeinfo_mlib_dirent_slot unsafe.Pointer
	_typeinfo_mlib_glob_slot   unsafe.Pointer
	_typeinfo_mlib_match       unsafe.Pointer
)

// reflect.Type's 2nd interface word is the *runtime._type mallocgc wants.
func _c2go_rtype(t reflect.Type) unsafe.Pointer {
	return (*[2]unsafe.Pointer)(unsafe.Pointer(&t))[1]
}

func init() {
	_typeinfo__c2go_mlib_FILE = _c2go_rtype(reflect.TypeFor[_c2go_mlib_FILE]())
	_typeinfo_mlib_DIR = _c2go_rtype(reflect.TypeFor[mlib_DIR]())
	_typeinfo_mlib_dirent_slot = _c2go_rtype(reflect.TypeFor[mlib_dirent_slot]())
	_typeinfo_mlib_glob_slot = _c2go_rtype(reflect.TypeFor[mlib_glob_slot]())
	_typeinfo_mlib_match = _c2go_rtype(reflect.TypeFor[mlib_match]())
}

// ─── Function declarations ──────────────────────────────────
// Bodies provided by clang-emitted Plan 9 .s with TEXT ·<name>(SB)
// at ABI0. Go compiler auto-generates the ABIInternal wrapper.

//go:linkname MlibClearerr github.com/c2gohq/c2go_libc/mlib.mlib_clearerr
func MlibClearerr(stream *_c2go_mlib_FILE)

//go:linkname MlibClosedir github.com/c2gohq/c2go_libc/mlib.mlib_closedir
func MlibClosedir(dir *mlib_DIR) int32

//go:linkname MlibFclose github.com/c2gohq/c2go_libc/mlib.mlib_fclose
func MlibFclose(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFdopen github.com/c2gohq/c2go_libc/mlib.mlib_fdopen
func MlibFdopen(fd int32, mode *byte) *_c2go_mlib_FILE

//go:linkname MlibFeof github.com/c2gohq/c2go_libc/mlib.mlib_feof
func MlibFeof(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFerror github.com/c2gohq/c2go_libc/mlib.mlib_ferror
func MlibFerror(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFflush github.com/c2gohq/c2go_libc/mlib.mlib_fflush
func MlibFflush(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFgetc github.com/c2gohq/c2go_libc/mlib.mlib_fgetc
func MlibFgetc(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFgetpos github.com/c2gohq/c2go_libc/mlib.mlib_fgetpos
func MlibFgetpos(stream *_c2go_mlib_FILE, position *int64) int32

//go:linkname MlibFgets github.com/c2gohq/c2go_libc/mlib.mlib_fgets
func MlibFgets(destination *byte, count int32, stream *_c2go_mlib_FILE) *byte

//go:linkname MlibFileno github.com/c2gohq/c2go_libc/mlib.mlib_fileno
func MlibFileno(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFlockfile github.com/c2gohq/c2go_libc/mlib.mlib_flockfile
func MlibFlockfile(stream *_c2go_mlib_FILE)

//go:linkname MlibFmemopen github.com/c2gohq/c2go_libc/mlib.mlib_fmemopen
func MlibFmemopen(buffer unsafe.Pointer, size uint64, mode *byte) *_c2go_mlib_FILE

//go:linkname MlibFopen github.com/c2gohq/c2go_libc/mlib.mlib_fopen
func MlibFopen(filename *byte, mode *byte) *_c2go_mlib_FILE

//go:linkname MlibFopencookie github.com/c2gohq/c2go_libc/mlib.mlib_fopencookie
func MlibFopencookie(cookie unsafe.Pointer, mode *byte, functions mlib_cookie_io_functions_t) *_c2go_mlib_FILE

//go:linkname MlibFprintf github.com/c2gohq/c2go_libc/mlib.mlib_fprintf
func MlibFprintf(stream *_c2go_mlib_FILE, format *byte, argptrs unsafe.Pointer) int32

//go:linkname MlibFputc github.com/c2gohq/c2go_libc/mlib.mlib_fputc
func MlibFputc(character int32, stream *_c2go_mlib_FILE) int32

//go:linkname MlibFputs github.com/c2gohq/c2go_libc/mlib.mlib_fputs
func MlibFputs(text *byte, stream *_c2go_mlib_FILE) int32

//go:linkname MlibFread github.com/c2gohq/c2go_libc/mlib.mlib_fread
func MlibFread(destination unsafe.Pointer, size uint64, count uint64, stream *_c2go_mlib_FILE) uint64

//go:linkname MlibFscanf github.com/c2gohq/c2go_libc/mlib.mlib_fscanf
func MlibFscanf(stream *_c2go_mlib_FILE, format *byte, argptrs unsafe.Pointer) int32

//go:linkname MlibFseek github.com/c2gohq/c2go_libc/mlib.mlib_fseek
func MlibFseek(stream *_c2go_mlib_FILE, offset int32, whence int32) int32

//go:linkname MlibFseeko github.com/c2gohq/c2go_libc/mlib.mlib_fseeko
func MlibFseeko(stream *_c2go_mlib_FILE, offset int64, whence int32) int32

//go:linkname MlibFsetpos github.com/c2gohq/c2go_libc/mlib.mlib_fsetpos
func MlibFsetpos(stream *_c2go_mlib_FILE, position *int64) int32

//go:linkname MlibFtell github.com/c2gohq/c2go_libc/mlib.mlib_ftell
func MlibFtell(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFtello github.com/c2gohq/c2go_libc/mlib.mlib_ftello
func MlibFtello(stream *_c2go_mlib_FILE) int64

//go:linkname MlibFtrylockfile github.com/c2gohq/c2go_libc/mlib.mlib_ftrylockfile
func MlibFtrylockfile(stream *_c2go_mlib_FILE) int32

//go:linkname MlibFunlockfile github.com/c2gohq/c2go_libc/mlib.mlib_funlockfile
func MlibFunlockfile(stream *_c2go_mlib_FILE)

//go:linkname MlibFwrite github.com/c2gohq/c2go_libc/mlib.mlib_fwrite
func MlibFwrite(source unsafe.Pointer, size uint64, count uint64, stream *_c2go_mlib_FILE) uint64

//go:linkname MlibGetc github.com/c2gohq/c2go_libc/mlib.mlib_getc
func MlibGetc(stream *_c2go_mlib_FILE) int32

//go:linkname MlibGetchar github.com/c2gohq/c2go_libc/mlib.mlib_getchar
func MlibGetchar() int32

//go:linkname MlibGetdelim github.com/c2gohq/c2go_libc/mlib.mlib_getdelim
func MlibGetdelim(line **byte, capacity *uint64, delimiter int32, stream *_c2go_mlib_FILE) int64

//go:linkname MlibGetline github.com/c2gohq/c2go_libc/mlib.mlib_getline
func MlibGetline(line **byte, capacity *uint64, stream *_c2go_mlib_FILE) int64

//go:linkname MlibGlob github.com/c2gohq/c2go_libc/mlib.mlib_glob
func MlibGlob(pattern *byte, flags int32, error_function uintptr, result *mlib_glob_t) int32

//go:linkname MlibGlobfree github.com/c2gohq/c2go_libc/mlib.mlib_globfree
func MlibGlobfree(result *mlib_glob_t)

//go:linkname MlibOpenMemstream github.com/c2gohq/c2go_libc/mlib.mlib_open_memstream
func MlibOpenMemstream(buffer_slot **byte, size_slot *uint64) *_c2go_mlib_FILE

//go:linkname MlibOpendir github.com/c2gohq/c2go_libc/mlib.mlib_opendir
func MlibOpendir(name *byte) *mlib_DIR

//go:linkname MlibPrintf github.com/c2gohq/c2go_libc/mlib.mlib_printf
func MlibPrintf(format *byte, argptrs unsafe.Pointer) int32

//go:linkname MlibPutc github.com/c2gohq/c2go_libc/mlib.mlib_putc
func MlibPutc(character int32, stream *_c2go_mlib_FILE) int32

//go:linkname MlibPutchar github.com/c2gohq/c2go_libc/mlib.mlib_putchar
func MlibPutchar(character int32) int32

//go:linkname MlibPuts github.com/c2gohq/c2go_libc/mlib.mlib_puts
func MlibPuts(text *byte) int32

//go:linkname MlibReaddir github.com/c2gohq/c2go_libc/mlib.mlib_readdir
func MlibReaddir(dir *mlib_DIR) *dirent

//go:linkname MlibReaddirR github.com/c2gohq/c2go_libc/mlib.mlib_readdir_r
func MlibReaddirR(dir *mlib_DIR, entry *dirent, result **dirent) int32

//go:linkname MlibRewind github.com/c2gohq/c2go_libc/mlib.mlib_rewind
func MlibRewind(stream *_c2go_mlib_FILE)

//go:linkname MlibRewinddir github.com/c2gohq/c2go_libc/mlib.mlib_rewinddir
func MlibRewinddir(dir *mlib_DIR)

//go:linkname MlibScandir github.com/c2gohq/c2go_libc/mlib.mlib_scandir
func MlibScandir(path *byte, result ***dirent, select_entry uintptr, compare_entry uintptr) int32

//go:linkname MlibScanf github.com/c2gohq/c2go_libc/mlib.mlib_scanf
func MlibScanf(format *byte, argptrs unsafe.Pointer) int32

//go:linkname MlibSscanf github.com/c2gohq/c2go_libc/mlib.mlib_sscanf
func MlibSscanf(input *byte, format *byte, argptrs unsafe.Pointer) int32

//go:linkname MlibStdfile github.com/c2gohq/c2go_libc/mlib.mlib_stdfile
func MlibStdfile(which int32) *_c2go_mlib_FILE

//go:linkname MlibUngetc github.com/c2gohq/c2go_libc/mlib.mlib_ungetc
func MlibUngetc(character int32, stream *_c2go_mlib_FILE) int32

//go:linkname MlibVfprintf github.com/c2gohq/c2go_libc/mlib.mlib_vfprintf
func MlibVfprintf(stream *_c2go_mlib_FILE, format *byte, arguments *byte) int32

//go:linkname MlibVfscanf github.com/c2gohq/c2go_libc/mlib.mlib_vfscanf
func MlibVfscanf(stream *_c2go_mlib_FILE, format *byte, arguments *byte) int32

//go:linkname MlibVprintf github.com/c2gohq/c2go_libc/mlib.mlib_vprintf
func MlibVprintf(format *byte, arguments *byte) int32

//go:linkname MlibVscanf github.com/c2gohq/c2go_libc/mlib.mlib_vscanf
func MlibVscanf(format *byte, arguments *byte) int32

//go:linkname MlibVsscanf github.com/c2gohq/c2go_libc/mlib.mlib_vsscanf
func MlibVsscanf(input *byte, format *byte, arguments *byte) int32

// ─── §B4 Go-owned global storage ────────────────────────────
// Pointer-carrying file-scope C globals whose storage is owned
// by this Go package. Each var's layout mirrors the C global's
// gcmask (unsafe.Pointer per pointer word, uintptr filler), so
// the Go compiler emits matching gcdata bits and the runtime
// scans every pointer slot as a root. Clang's .s output
// suppresses the matching GLOBL trailer for each name below.
var mlib_ofl_head unsafe.Pointer
var mlib_std_files [3]unsafe.Pointer

// ─── Embedded runtime-support helpers ───────────────────────

// _c2go_cgocall is a thin shim around runtime.cgocall, used by the
// cross-world bridge for unmanaged function calls. Only emitted when
// the sidecar declares unmanaged extern functions; v0 always emits
// for simplicity.
//
// #218 fix: Go 1.25 stopped honouring the bodyless-decl form of
// //go:linkname (the symbol named on the local side was no longer
// rewritten to the runtime target — the .s reference would resolve
// to sqlitepkg._c2go_cgocall which the runtime never provided).
// Use the alias-then-wrap pattern: pull runtime.cgocall into a
// private local name via linkname, then expose the public name as
// a thin wrapper.
//
//go:linkname _runtime_cgocall runtime.cgocall
//go:noescape
func _runtime_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32

//go:nosplit
func _c2go_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32 {
	return _runtime_cgocall(fn, frame)
}

// _c2go_typedmemmove copies a typed value, invoking the bulk write
// barrier when the type has pointers. Used by realloc lowering and
// the c2go-memcpy-typing pass.
//
//go:linkname _runtime_typedmemmove runtime.typedmemmove
//go:noescape
func _runtime_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer)

//go:nosplit
func _c2go_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer) {
	_runtime_typedmemmove(typ, dst, src)
}

// _c2go_typedMemmoveArray is the per-element loop used by the
// c2go-memcpy-typing pass when copying arrays of pointerful elements.
//
//go:nosplit
func _c2go_typedMemmoveArray(typ unsafe.Pointer, dst, src unsafe.Pointer, n uintptr) {
	sz := *(*uintptr)(typ) // _type.Size_ at offset 0 (pinned Go 1.22+)
	for i := uintptr(0); i < n; i++ {
		_c2go_typedmemmove(typ,
			unsafe.Pointer(uintptr(dst)+i*sz),
			unsafe.Pointer(uintptr(src)+i*sz))
	}
}

// _c2go_writePtr is the slow-path of the inline write barrier.
// The LLVM c2go-write-barriers pass emits an inline check of
// runtime.writeBarrier.enabled; on the slow path it calls this
// helper. The Go compiler, seeing the *slot = val store in this
// body, emits the real inline barrier sequence (gcWriteBarrier2
// reservation + push). We never touch the special-ABI helper directly.
//
//go:nosplit
func _c2go_writePtr(slot *unsafe.Pointer, val unsafe.Pointer) {
	*slot = val
}

// errString is used by the §E2 unmanaged-extern wrappers' dlsym-
// failure panic path. Kept zero-import (no fmt) so the wrappers
// don't drag in extra runtime cost.
func errString(err error) string {
	if err == nil {
		return "<nil>"
	}
	return err.Error()
}
