//go:build linux && arm64 && go1.25

// Code generated by c2go-bind. DO NOT EDIT.
// Licensing follows the translated input and its third-party provenance; see
// the c2go-libc NOTICE, provenance inventory, and bundled license texts.

package selftest

import (
	_ "unsafe"
)

// ─── Types ──────────────────────────────────────────────────

// ─── Function declarations ──────────────────────────────────
// Bodies provided by clang-emitted Plan 9 .s with TEXT ·<name>(SB)
// at ABI0. Go compiler auto-generates the ABIInternal wrapper.

func AtexitSelftestAssert()
func AtexitSelftestLIFO()
func QsortSelftest() int32
func ScandirSelftest() int32
func SignalSelftestAbort()
func SignalSelftestFired() int32
func SignalSelftestIgn() int32
func SignalSelftestInstall()
func SignalSelftestRaise() int32
func SignalSelftestSegvRefused() int32
func WcharSelftest() int32

//go:linkname NftwSelftest github.com/c2gohq/c2go_libc/selftest.nftw_selftest
func NftwSelftest() int32

//go:linkname SearchSelftest github.com/c2gohq/c2go_libc/selftest.search_selftest
func SearchSelftest() int32

//go:linkname TermiosSelftest github.com/c2gohq/c2go_libc/selftest.termios_selftest
func TermiosSelftest() int32
