//go:build linux && arm64 && go1.25

// Code generated by c2go-bind. DO NOT EDIT.
// Input-derived material retains the input's copyright and license. This file
// also contains original C2Go runtime-support code copied from c2go-bind,
// available under AGPL-3.0-only or a separate commercial agreement.
// See https://github.com/c2gohq/c2go_bind/blob/main/LICENSING.md.

package selftest

import (
	_ "github.com/c2gohq/c2go_libc"
	"unsafe"
)

// ─── Types ──────────────────────────────────────────────────

// ─── Function declarations ──────────────────────────────────
// Bodies provided by clang-emitted Plan 9 .s with TEXT ·<name>(SB)
// at ABI0. Go compiler auto-generates the ABIInternal wrapper.

func AtexitSelftestAssert()
func AtexitSelftestLIFO()
func QsortSelftest() int32
func ScandirSelftest() int32
func SignalSelftestAbort()
func SignalSelftestFired() int32
func SignalSelftestIgn() int32
func SignalSelftestInstall()
func SignalSelftestRaise() int32
func SignalSelftestSegvRefused() int32
func WcharSelftest() int32

//go:linkname NftwSelftest github.com/c2gohq/c2go_libc/selftest.nftw_selftest
func NftwSelftest() int32

//go:linkname SearchSelftest github.com/c2gohq/c2go_libc/selftest.search_selftest
func SearchSelftest() int32

//go:linkname TermiosSelftest github.com/c2gohq/c2go_libc/selftest.termios_selftest
func TermiosSelftest() int32

// ─── Embedded runtime-support helpers ───────────────────────

// _c2go_cgocall is a thin shim around runtime.cgocall, used by the
// cross-world bridge for unmanaged function calls. Only emitted when
// the sidecar declares unmanaged extern functions; v0 always emits
// for simplicity.
//
// #218 fix: Go 1.25 stopped honouring the bodyless-decl form of
// //go:linkname (the symbol named on the local side was no longer
// rewritten to the runtime target — the .s reference would resolve
// to sqlitepkg._c2go_cgocall which the runtime never provided).
// Use the alias-then-wrap pattern: pull runtime.cgocall into a
// private local name via linkname, then expose the public name as
// a thin wrapper.
//
//go:linkname _runtime_cgocall runtime.cgocall
//go:noescape
func _runtime_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32

//go:nosplit
func _c2go_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32 {
	return _runtime_cgocall(fn, frame)
}

// _c2go_typedmemmove copies a typed value, invoking the bulk write
// barrier when the type has pointers. Used by realloc lowering and
// the c2go-memcpy-typing pass.
//
//go:linkname _runtime_typedmemmove runtime.typedmemmove
//go:noescape
func _runtime_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer)

//go:nosplit
func _c2go_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer) {
	_runtime_typedmemmove(typ, dst, src)
}

// _c2go_typedMemmoveArray is the per-element loop used by the
// c2go-memcpy-typing pass when copying arrays of pointerful elements.
//
//go:nosplit
func _c2go_typedMemmoveArray(typ unsafe.Pointer, dst, src unsafe.Pointer, n uintptr) {
	sz := *(*uintptr)(typ) // _type.Size_ at offset 0 (pinned Go 1.22+)
	for i := uintptr(0); i < n; i++ {
		_c2go_typedmemmove(typ,
			unsafe.Pointer(uintptr(dst)+i*sz),
			unsafe.Pointer(uintptr(src)+i*sz))
	}
}

// _c2go_writePtr is the slow-path of the inline write barrier.
// The LLVM c2go-write-barriers pass emits an inline check of
// runtime.writeBarrier.enabled; on the slow path it calls this
// helper. The Go compiler, seeing the *slot = val store in this
// body, emits the real inline barrier sequence (gcWriteBarrier2
// reservation + push). We never touch the special-ABI helper directly.
//
//go:nosplit
func _c2go_writePtr(slot *unsafe.Pointer, val unsafe.Pointer) {
	*slot = val
}

// errString is used by the §E2 unmanaged-extern wrappers' dlsym-
// failure panic path. Kept zero-import (no fmt) so the wrappers
// don't drag in extra runtime cost.
func errString(err error) string {
	if err == nil {
		return "<nil>"
	}
	return err.Error()
}
