package libc

// Cross-checks for the "gamma" math cluster (tgamma, lgamma, lgamma_r, erf,
// erfc and their f-variants) against Go's standard math package.
//
// NOTE: the Go bindings (libc.Tgamma, libc.LgammaR, ...) are generated by
// gen.sh from the c2go_linkname'd decls in include/math.h; until that runs this
// file will not compile. It is written correct against the binding names:
//   tgamma->Tgamma, lgamma->Lgamma, lgamma_r->LgammaR, erf->Erf, erfc->Erfc
//   (+ f-variants Tgammaf, Lgammaf, LgammafR, Erff, Erfcf).
//
// Tolerances are ULP-or-relative and deliberately generous for the transcen-
// dentals: our ports compose separately-ported exp/log/pow, and Go's math.Gamma
// uses a different algorithm than musl's Lanczos tgamma, so a couple ULP of
// disagreement is expected. lgamma/erf share FreeBSD lineage with Go's math and
// stay much tighter.

import (
	"math"
	"testing"
)

// ---- ULP distance helpers (sign-magnitude -> monotone ordering) ----

func ulp64(a, b float64) uint64 {
	ua := math.Float64bits(a)
	ub := math.Float64bits(b)
	if ua&(1<<63) != 0 {
		ua = 0x8000000000000000 - ua
	}
	if ub&(1<<63) != 0 {
		ub = 0x8000000000000000 - ub
	}
	if ua > ub {
		return ua - ub
	}
	return ub - ua
}

func ulp32(a, b float32) uint32 {
	ua := math.Float32bits(a)
	ub := math.Float32bits(b)
	if ua&(1<<31) != 0 {
		ua = 0x80000000 - ua
	}
	if ub&(1<<31) != 0 {
		ub = 0x80000000 - ub
	}
	if ua > ub {
		return ua - ub
	}
	return ub - ua
}

func close64(got, want float64, maxUlp uint64, rel float64) bool {
	if math.IsNaN(got) || math.IsNaN(want) {
		return math.IsNaN(got) && math.IsNaN(want)
	}
	if math.IsInf(got, 0) || math.IsInf(want, 0) {
		return got == want
	}
	if got == want {
		return true
	}
	if ulp64(got, want) <= maxUlp {
		return true
	}
	if want != 0 {
		return math.Abs((got-want)/want) <= rel
	}
	return math.Abs(got) <= rel
}

func close32(got, want float32, maxUlp uint32, rel float64) bool {
	g, w := float64(got), float64(want)
	if math.IsNaN(g) || math.IsNaN(w) {
		return math.IsNaN(g) && math.IsNaN(w)
	}
	if math.IsInf(g, 0) || math.IsInf(w, 0) {
		return got == want
	}
	if got == want {
		return true
	}
	if ulp32(got, want) <= maxUlp {
		return true
	}
	if w != 0 {
		return math.Abs((g-w)/w) <= rel
	}
	return math.Abs(g) <= rel
}

// exact-or-NaN equality for special-value assertions
func sameExact(got, want float64) bool {
	if math.IsNaN(want) {
		return math.IsNaN(got)
	}
	return got == want
}

// ============================== tgamma ==============================

func TestTgammaSpecials(t *testing.T) {
	negZero := math.Copysign(0, -1)
	cases := []struct {
		in, want float64
	}{
		{0, math.Inf(1)},
		{negZero, math.Inf(-1)},
		{math.Inf(1), math.Inf(1)},
		{math.Inf(-1), math.NaN()},
		{math.NaN(), math.NaN()},
		{-1, math.NaN()},
		{-5, math.NaN()},
		{5, 24}, // integer -> exact factorial(4)
		{1, 1},
		{2, 1},
	}
	for _, c := range cases {
		got := Tgamma(c.in)
		if !sameExact(got, c.want) {
			t.Errorf("Tgamma(%v) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestTgammaValues(t *testing.T) {
	xs := []float64{
		0.5, 1.5, 2.5, 3.5, 4.2, 0.1, 0.01, 0.001,
		-0.5, -1.5, -2.5, -3.7, -0.1, -10.3,
		10.3, 20.7, 50.5, 100.5, 150.0, 170.5,
	}
	for _, x := range xs {
		got := Tgamma(x)
		want := math.Gamma(x)
		if !close64(got, want, 32, 1e-12) {
			t.Errorf("Tgamma(%v) = %v, want %v (ulp=%d)", x, got, want, ulp64(got, want))
		}
	}
}

func TestTgammaf(t *testing.T) {
	xs := []float32{0.5, 1.5, 2.5, 3.5, 4.2, 0.1, -0.5, -1.5, -2.5, -3.7, 10.3, 20.7, 30.5}
	for _, x := range xs {
		got := Tgammaf(x)
		want := float32(math.Gamma(float64(x)))
		if !close32(got, want, 16, 1e-5) {
			t.Errorf("Tgammaf(%v) = %v, want %v", x, got, want)
		}
	}
}

// ============================== lgamma ==============================

func TestLgammaSpecials(t *testing.T) {
	cases := []struct {
		in, want float64
	}{
		{1, 0},
		{2, 0},
		{0, math.Inf(1)},
		{-1, math.Inf(1)}, // pole
		{-2, math.Inf(1)},
		{math.Inf(1), math.Inf(1)},
		{math.Inf(-1), math.Inf(1)}, // musl: lgamma(-inf)=inf (bug-for-bug C99)
		{math.NaN(), math.NaN()},
	}
	for _, c := range cases {
		got := Lgamma(c.in)
		if !sameExact(got, c.want) {
			t.Errorf("Lgamma(%v) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestLgammaValues(t *testing.T) {
	xs := []float64{
		0.5, 1.5, 2.3, 4.7, 6.0, 8.5, 20.3, 100.7, 1e5, 1e10,
		0.1, 0.01, 1e-30,
		-0.5, -2.3, -5.5, -10.7,
	}
	for _, x := range xs {
		got := Lgamma(x)
		want, _ := math.Lgamma(x)
		if !close64(got, want, 8, 1e-13) {
			t.Errorf("Lgamma(%v) = %v, want %v (ulp=%d)", x, got, want, ulp64(got, want))
		}
	}
}

func TestLgammaR(t *testing.T) {
	xs := []float64{0.5, 1.5, 2.3, 4.7, 8.5, 20.3, 100.7, -0.5, -2.3, -5.5}
	for _, x := range xs {
		var sign int32
		got := LgammaR(x, &sign)
		want, wsign := math.Lgamma(x)
		if !close64(got, want, 8, 1e-13) {
			t.Errorf("LgammaR(%v) value = %v, want %v", x, got, want)
		}
		if int(sign) != wsign {
			t.Errorf("LgammaR(%v) sign = %d, want %d", x, sign, wsign)
		}
	}
}

func TestLgammaf(t *testing.T) {
	xs := []float32{0.5, 1.5, 2.3, 4.7, 8.5, 20.3, 100.7, 0.1, -0.5, -2.3, -5.5}
	for _, x := range xs {
		got := Lgammaf(x)
		wd, _ := math.Lgamma(float64(x))
		want := float32(wd)
		if !close32(got, want, 16, 1e-5) {
			t.Errorf("Lgammaf(%v) = %v, want %v", x, got, want)
		}
	}
}

func TestLgammafR(t *testing.T) {
	xs := []float32{0.5, 1.5, 2.3, 4.7, 8.5, -0.5, -2.3, -5.5}
	for _, x := range xs {
		var sign int32
		got := LgammafR(x, &sign)
		wd, wsign := math.Lgamma(float64(x))
		want := float32(wd)
		if !close32(got, want, 16, 1e-5) {
			t.Errorf("LgammafR(%v) value = %v, want %v", x, got, want)
		}
		if int(sign) != wsign {
			t.Errorf("LgammafR(%v) sign = %d, want %d", x, sign, wsign)
		}
	}
}

// ============================== erf / erfc ==============================

func TestErfSpecials(t *testing.T) {
	cases := []struct {
		in, want float64
	}{
		{0, 0},
		{math.Inf(1), 1},
		{math.Inf(-1), -1},
		{math.NaN(), math.NaN()},
	}
	for _, c := range cases {
		got := Erf(c.in)
		if !sameExact(got, c.want) {
			t.Errorf("Erf(%v) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestErfcSpecials(t *testing.T) {
	cases := []struct {
		in, want float64
	}{
		{0, 1},
		{math.Inf(1), 0},
		{math.Inf(-1), 2},
		{math.NaN(), math.NaN()},
	}
	for _, c := range cases {
		got := Erfc(c.in)
		if !sameExact(got, c.want) {
			t.Errorf("Erfc(%v) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestErfValues(t *testing.T) {
	xs := []float64{
		-6, -3, -2, -1.25, -1, -0.84, -0.5, -0.1, -0.001,
		0.001, 0.1, 0.25, 0.5, 0.84, 1, 1.25, 2, 2.8, 3, 6, 30,
		1e-30, 1e-300,
	}
	for _, x := range xs {
		got := Erf(x)
		want := math.Erf(x)
		if !close64(got, want, 4, 1e-14) {
			t.Errorf("Erf(%v) = %v, want %v (ulp=%d)", x, got, want, ulp64(got, want))
		}
	}
}

func TestErfcValues(t *testing.T) {
	xs := []float64{
		-6, -3, -2, -1.25, -1, -0.84, -0.5, -0.1,
		0.1, 0.25, 0.5, 0.84, 1, 1.25, 2, 2.8, 3, 6, 26, 27,
		1e-30, 1e-300,
	}
	for _, x := range xs {
		got := Erfc(x)
		want := math.Erfc(x)
		if !close64(got, want, 4, 1e-13) {
			t.Errorf("Erfc(%v) = %v, want %v (ulp=%d)", x, got, want, ulp64(got, want))
		}
	}
}

func TestErff(t *testing.T) {
	xs := []float32{-3, -1.25, -1, -0.5, -0.1, 0.1, 0.5, 0.84, 1, 1.25, 2, 3, 6}
	for _, x := range xs {
		got := Erff(x)
		want := float32(math.Erf(float64(x)))
		if !close32(got, want, 8, 2e-6) {
			t.Errorf("Erff(%v) = %v, want %v", x, got, want)
		}
	}
}

func TestErfcf(t *testing.T) {
	xs := []float32{-3, -1.25, -1, -0.5, -0.1, 0.1, 0.5, 0.84, 1, 1.25, 2, 3, 6, 10}
	for _, x := range xs {
		got := Erfcf(x)
		want := float32(math.Erfc(float64(x)))
		if !close32(got, want, 8, 2e-6) {
			t.Errorf("Erfcf(%v) = %v, want %v", x, got, want)
		}
	}
}
