// math_pow_test.go — cross-checks the "pow" cluster (pow/sqrt/cbrt/hypot + f
// variants). sqrt/sqrtf are hardware correctly-rounded, so they must match
// Go's math.Sqrt bit-exactly. The transcendental pow/cbrt/hypot (and their
// float variants) are compared against a correctly-rounded high-precision
// oracle (mpmath, see math_oracle_test.go) instead of Go's math package: Go's
// pow is wrong by up to ~1000 ULP at the extreme-exponent inputs here while
// the port is correctly rounded, so Go is a bad reference. Finite in-domain
// inputs use the oracle at a tight ULP bound; special/edge inputs (Inf, NaN,
// ±0 bases, negative-base non-integer exponents) are absent from the oracle
// and fall back to Go's math, which is exact for them.
//
// NOTE: the Go bindings (Pow, Powf, Sqrt, Sqrtf, Cbrt, Cbrtf, Hypot, Hypotf)
// are generated by gen.sh, so this file does not compile until then. That is
// expected.
package libc

import (
	"math"
	"strconv"
	"testing"
)

// ---- ULP distance helpers (total-order monotonic mapping) ----

func mono64(f float64) uint64 {
	b := math.Float64bits(f)
	if b>>63 == 1 {
		return ^b
	}
	return b + (1 << 63)
}

func powUlp64(a, b float64) uint64 {
	ma, mb := mono64(a), mono64(b)
	if ma > mb {
		return ma - mb
	}
	return mb - ma
}

func mono32(f float32) uint32 {
	b := math.Float32bits(f)
	if b>>31 == 1 {
		return ^b
	}
	return b + (1 << 31)
}

func powUlp32(a, b float32) uint32 {
	ma, mb := mono32(a), mono32(b)
	if ma > mb {
		return ma - mb
	}
	return mb - ma
}

func chk64(t *testing.T, label string, got, want float64, tol uint64) {
	t.Helper()
	if math.IsNaN(got) && math.IsNaN(want) {
		return
	}
	if d := powUlp64(got, want); d > tol {
		t.Errorf("%s = %v (%#016x), want %v (%#016x); ulp diff %d > %d",
			label, got, math.Float64bits(got), want, math.Float64bits(want), d, tol)
	}
}

func chk32(t *testing.T, label string, got, want float32, tol uint32) {
	t.Helper()
	if math.IsNaN(float64(got)) && math.IsNaN(float64(want)) {
		return
	}
	if d := powUlp32(got, want); d > tol {
		t.Errorf("%s = %v (%#08x), want %v (%#08x); ulp diff %d > %d",
			label, got, math.Float32bits(got), want, math.Float32bits(want), d, tol)
	}
}

// A broad spread of double inputs: 0, -0, ±1, subnormals, min-normal, large,
// small, ±Inf, NaN, and assorted normals.
var powDvals = []float64{
	0.0,
	math.Copysign(0, -1),
	1.0, -1.0, 2.0, -2.0, 0.5, -0.5,
	3.14159265358979, -3.14159265358979,
	123456.789, -987654.321,
	1e300, 1e-300,
	math.MaxFloat64,
	2.2250738585072014e-308, // smallest normal
	5e-324,                  // smallest subnormal
	8.0, 27.0, -64.0, 1000000.0,
	math.Inf(1), math.Inf(-1), math.NaN(),
}

var powFvals = []float32{
	0.0,
	float32(math.Copysign(0, -1)),
	1.0, -1.0, 2.0, -2.0, 0.5, -0.5,
	3.14159265, -3.14159265,
	12345.678, -98765.4,
	1e30, 1e-30,
	math.MaxFloat32,
	1.1754944e-38, // smallest normal float32
	1.4e-45,       // smallest subnormal float32
	8.0, 27.0, -64.0, 1000000.0,
	float32(math.Inf(1)), float32(math.Inf(-1)), float32(math.NaN()),
}

// ---- sqrt / sqrtf : correctly rounded, must be bit-exact ----

func TestSqrt(t *testing.T) {
	for _, x := range powDvals {
		chk64(t, fmtf("Sqrt", x), Sqrt(x), math.Sqrt(x), 0)
	}
}

func TestSqrtf(t *testing.T) {
	for _, x := range powFvals {
		want := float32(math.Sqrt(float64(x)))
		chk32(t, fmtf32("Sqrtf", x), Sqrtf(x), want, 0)
	}
}

// ---- cbrt / cbrtf ----

func TestCbrt(t *testing.T) {
	for _, x := range powDvals {
		chk64(t, fmtf("Cbrt", x), Cbrt(x), cbrtRef(x), 2)
	}
}

func TestCbrtf(t *testing.T) {
	for _, x := range powFvals {
		want := float32(cbrtRef(float64(x)))
		chk32(t, fmtf32("Cbrtf", x), Cbrtf(x), want, 2)
	}
}

// ---- pow / powf ----

var dpairs = [][2]float64{
	{2, 3}, {2, 0.5}, {2, -0.5}, {2, -3}, {10, 10}, {0.5, 20},
	{3, 100}, {2, 1023}, {2, -1023}, {1.5, 2.7}, {123.456, 0.333},
	{0.9999, 10000}, {1.0001, 5000}, {7, 7}, {2.5, 4},
	// integer-exponent negatives
	{-2, 3}, {-2, 2}, {-8, 0.3333333333333333}, {-2, 2.5}, // last -> NaN
	// special: x==±0
	{0, 3}, {0, -3}, {math.Copysign(0, -1), 3}, {math.Copysign(0, -1), -3},
	{0, 4}, {0, -4},
	// special: exponent 0 / 1, base 1
	{2, 0}, {math.NaN(), 0}, {2, 1}, {1, 1e300}, {-1, 1e300}, {1, math.NaN()},
	// infinities
	{math.Inf(1), 2}, {math.Inf(1), -2}, {math.Inf(-1), 3}, {math.Inf(-1), -3},
	{2, math.Inf(1)}, {0.5, math.Inf(1)}, {2, math.Inf(-1)}, {0.5, math.Inf(-1)},
	{-1, math.Inf(1)},
	// NaN
	{math.NaN(), 2}, {2, math.NaN()},
	// over/underflow
	{1e300, 2}, {1e-300, 2},
}

func TestPow(t *testing.T) {
	for _, p := range dpairs {
		x, y := p[0], p[1]
		chk64(t, fmtf2("Pow", x, y), Pow(x, y), powRef(x, y), 2)
	}
}

var fpairs = [][2]float32{
	{2, 3}, {2, 0.5}, {2, -0.5}, {2, -3}, {10, 10}, {0.5, 20},
	{3, 20}, {2, 100}, {2, -100}, {1.5, 2.7}, {123.456, 0.333},
	{7, 7}, {2.5, 4},
	{-2, 3}, {-2, 2}, {-8, 0.3333333333333333}, {-2, 2.5},
	{0, 3}, {0, -3}, {float32(math.Copysign(0, -1)), 3}, {float32(math.Copysign(0, -1)), -3},
	{2, 0}, {float32(math.NaN()), 0}, {2, 1}, {1, 1e30}, {-1, 1e30}, {1, float32(math.NaN())},
	{float32(math.Inf(1)), 2}, {float32(math.Inf(1)), -2},
	{float32(math.Inf(-1)), 3}, {float32(math.Inf(-1)), -3},
	{2, float32(math.Inf(1))}, {0.5, float32(math.Inf(1))},
	{2, float32(math.Inf(-1))}, {-1, float32(math.Inf(1))},
	{float32(math.NaN()), 2}, {2, float32(math.NaN())},
	{1e30, 2}, {1e-30, 2},
}

func TestPowf(t *testing.T) {
	for _, p := range fpairs {
		x, y := p[0], p[1]
		want := float32(powRef(float64(x), float64(y)))
		chk32(t, fmtf322("Powf", x, y), Powf(x, y), want, 2)
	}
}

// ---- hypot / hypotf ----

var dhpairs = [][2]float64{
	{3, 4}, {5, 12}, {8, 15}, {0, 0}, {0, 5}, {5, 0}, {-3, 4}, {-3, -4},
	{1e300, 1e300}, {1e-300, 1e-300}, {1.5e-308, 1.5e-308},
	{math.MaxFloat64, math.MaxFloat64}, // -> +Inf both
	{1e308, 1e308},                     // finite: 1.414e308 < MaxFloat64
	{1e300, 1}, {1, 1e300},
	{math.Inf(1), 5}, {5, math.Inf(1)}, {math.Inf(-1), 5},
	{math.Inf(1), math.NaN()}, {math.NaN(), math.Inf(1)}, // -> +Inf both
	{math.NaN(), 5}, {5, math.NaN()},                     // -> NaN both
	{1e-162, 1e-162}, {123.0, 456.0}, {0.0003, 0.0004},
}

func TestHypot(t *testing.T) {
	for _, p := range dhpairs {
		x, y := p[0], p[1]
		chk64(t, fmtf2("Hypot", x, y), Hypot(x, y), hypotRef(x, y), 2)
	}
}

var fhpairs = [][2]float32{
	{3, 4}, {5, 12}, {8, 15}, {0, 0}, {0, 5}, {5, 0}, {-3, 4}, {-3, -4},
	{1e30, 1e30}, {1e-30, 1e-30}, {1e-40, 1e-40},
	{math.MaxFloat32, math.MaxFloat32}, // -> +Inf both
	{1e30, 1}, {1, 1e30},
	{float32(math.Inf(1)), 5}, {5, float32(math.Inf(1))}, {float32(math.Inf(-1)), 5},
	{float32(math.Inf(1)), float32(math.NaN())}, {float32(math.NaN()), float32(math.Inf(1))},
	{float32(math.NaN()), 5}, {5, float32(math.NaN())},
	{123.0, 456.0}, {0.0003, 0.0004},
}

func TestHypotf(t *testing.T) {
	for _, p := range fhpairs {
		x, y := p[0], p[1]
		want := float32(hypotRef(float64(x), float64(y)))
		chk32(t, fmtf322("Hypotf", x, y), Hypotf(x, y), want, 2)
	}
}

// ---- tiny label formatters (avoid importing fmt just for %g spread) ----

func fmtf(name string, x float64) string {
	return name + "(" + g64(x) + ")"
}
func fmtf2(name string, x, y float64) string {
	return name + "(" + g64(x) + ", " + g64(y) + ")"
}
func fmtf32(name string, x float32) string {
	return name + "(" + g64(float64(x)) + ")"
}
func fmtf322(name string, x, y float32) string {
	return name + "(" + g64(float64(x)) + ", " + g64(float64(y)) + ")"
}
func g64(x float64) string {
	return strconv.FormatFloat(x, 'g', -1, 64)
}
