// math_explog_test.go — cross-checks the "explog" cluster (exp/exp2/expm1/log/
// log2/log10/log1p + f variants, from source/math_explog.c, ported from
// musl-1.2.6) against a correctly-rounded high-precision oracle (mpmath, see
// math_oracle_test.go) rather than Go's math package. Go is a bad reference
// here for two reasons: its transcendentals are only ~1-ULP accurate, and —
// decisively — on amd64/Rosetta its Frexp-based math.Log/math.Log10 return a
// wrong value for the smallest subnormal (math.Log(5e-324) yields -709.09
// instead of the true -744.44), an FP-emulation artifact. The finite in-domain
// results are compared against the oracle; out-of-domain/special inputs
// (Inf/NaN, x<=0 for the log family, x<=-1 for log1p) are absent from the
// oracle and fall back to Go's math, which returns the exact -Inf/NaN there.
// Results are allowed a tight 2-ULP bound (or bit-exact); NaN==NaN and equal
// infinities compare equal (ULP distance 0).
//
// All helpers and data here carry an `el` prefix so this file is self-contained
// and never collides with the shared helpers/vars in sibling math_*_test.go
// files. Bindings (Exp, Expf, Exp2, ... Log1pf) are the C name Capitalized and
// are generated by gen.sh, so this file does not compile until then — expected.
package libc

import (
	"math"
	"strconv"
	"testing"
)

// ---- ULP distance helpers (total-order monotonic mapping) ----

func elMono64(f float64) uint64 {
	b := math.Float64bits(f)
	if b>>63 == 1 {
		return ^b
	}
	return b + (1 << 63)
}

func elUlp64(a, b float64) uint64 {
	ma, mb := elMono64(a), elMono64(b)
	if ma > mb {
		return ma - mb
	}
	return mb - ma
}

func elMono32(f float32) uint32 {
	b := math.Float32bits(f)
	if b>>31 == 1 {
		return ^b
	}
	return b + (1 << 31)
}

func elUlp32(a, b float32) uint32 {
	ma, mb := elMono32(a), elMono32(b)
	if ma > mb {
		return ma - mb
	}
	return mb - ma
}

func elChk64(t *testing.T, label string, got, want float64, tol uint64) {
	t.Helper()
	if math.IsNaN(got) && math.IsNaN(want) {
		return
	}
	if d := elUlp64(got, want); d > tol {
		t.Errorf("%s = %v (%#016x), want %v (%#016x); ulp diff %d > %d",
			label, got, math.Float64bits(got), want, math.Float64bits(want), d, tol)
	}
}

func elChk32(t *testing.T, label string, got, want float32, tol uint32) {
	t.Helper()
	if math.IsNaN(float64(got)) && math.IsNaN(float64(want)) {
		return
	}
	if d := elUlp32(got, want); d > tol {
		t.Errorf("%s = %v (%#08x), want %v (%#08x); ulp diff %d > %d",
			label, got, math.Float32bits(got), want, math.Float32bits(want), d, tol)
	}
}

func elG64(x float64) string { return strconv.FormatFloat(x, 'g', -1, 64) }
func elLbl(name string, x float64) string { return name + "(" + elG64(x) + ")" }

// A broad spread: 0, -0, ±1, small/large normals, exp over/underflow-boundary
// magnitudes, subnormals, min-normal, ±Inf, NaN. Negative inputs exercise the
// log NaN path; huge inputs exercise the exp overflow (→Inf) path.
var elDvals = []float64{
	0.0,
	math.Copysign(0, -1),
	1.0, -1.0, 2.0, -2.0, 0.5, -0.5,
	math.E, math.Pi, -math.Pi,
	0.1, 0.25, 10.0, 100.0, 1000.0,
	1.5, 123.456, -987.654,
	709.0, 700.5, -708.0, -740.0, // exp: near overflow / subnormal-result region
	1e-5, 1e5, 1e-10, 1e10,
	1e300, 1e-300,
	math.MaxFloat64,
	2.2250738585072014e-308, // smallest normal double
	5e-324,                  // smallest subnormal double
	math.Inf(1), math.Inf(-1), math.NaN(),
}

var elFvals = []float32{
	0.0,
	float32(math.Copysign(0, -1)),
	1.0, -1.0, 2.0, -2.0, 0.5, -0.5,
	float32(math.E), float32(math.Pi), -float32(math.Pi),
	0.1, 0.25, 10.0, 100.0, 1000.0,
	1.5, 123.456, -987.654,
	80.0, 88.0, -80.0, -103.0, // expf: near overflow (~88.72) / underflow (~-103.97)
	1e-5, 1e5,
	1e30, 1e-30,
	math.MaxFloat32,
	1.1754944e-38, // smallest normal float32
	1.4e-45,       // smallest subnormal float32
	float32(math.Inf(1)), float32(math.Inf(-1)), float32(math.NaN()),
}

// ================================ exp ================================

func TestExp(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Exp", x), Exp(x), expRef(x), 2)
	}
}

func TestExpf(t *testing.T) {
	for _, x := range elFvals {
		want := float32(expRef(float64(x)))
		elChk32(t, elLbl("Expf", float64(x)), Expf(x), want, 2)
	}
}

// ================================ exp2 ===============================

func TestExp2(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Exp2", x), Exp2(x), exp2Ref(x), 2)
	}
}

func TestExp2f(t *testing.T) {
	for _, x := range elFvals {
		want := float32(exp2Ref(float64(x)))
		elChk32(t, elLbl("Exp2f", float64(x)), Exp2f(x), want, 2)
	}
}

// ================================ expm1 ==============================

func TestExpm1(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Expm1", x), Expm1(x), expm1Ref(x), 2)
	}
}

func TestExpm1f(t *testing.T) {
	for _, x := range elFvals {
		want := float32(expm1Ref(float64(x)))
		elChk32(t, elLbl("Expm1f", float64(x)), Expm1f(x), want, 2)
	}
}

// ================================= log ===============================

func TestLog(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Log", x), Log(x), logRef(x), 2)
	}
}

func TestLogf(t *testing.T) {
	for _, x := range elFvals {
		want := float32(logRef(float64(x)))
		elChk32(t, elLbl("Logf", float64(x)), Logf(x), want, 2)
	}
}

// ================================= log2 ==============================

func TestLog2(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Log2", x), Log2(x), log2Ref(x), 2)
	}
}

func TestLog2f(t *testing.T) {
	for _, x := range elFvals {
		want := float32(log2Ref(float64(x)))
		elChk32(t, elLbl("Log2f", float64(x)), Log2f(x), want, 2)
	}
}

// ================================= log10 =============================

func TestLog10(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Log10", x), Log10(x), log10Ref(x), 2)
	}
}

func TestLog10f(t *testing.T) {
	for _, x := range elFvals {
		want := float32(log10Ref(float64(x)))
		elChk32(t, elLbl("Log10f", float64(x)), Log10f(x), want, 2)
	}
}

// ================================= log1p =============================

func TestLog1p(t *testing.T) {
	for _, x := range elDvals {
		elChk64(t, elLbl("Log1p", x), Log1p(x), log1pRef(x), 2)
	}
}

func TestLog1pf(t *testing.T) {
	for _, x := range elFvals {
		want := float32(log1pRef(float64(x)))
		elChk32(t, elLbl("Log1pf", float64(x)), Log1pf(x), want, 2)
	}
}
