// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_pthread_prefixed_selftest(SB), $144-8
	PCDATA $1, $-1
	WORD $0x6f00e400
	MOVD RSP, R8
	ADD $104, RSP, R9
	MOVD ZR, 144(RSP)
	MOVD ZR, 104(RSP)
	FMOVQ F0, 56(RSP)
	FMOVQ F0, 72(RSP)
	FMOVQ F0, 88(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp0:
	CBZW R0, _LBB0_2
	ADDW $10, R0, R8
	JMP _LBB0_4
_LBB0_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_mutex(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp1:
	CBZW R0, _LBB0_5
	ADDW $20, R0, R8
_LBB0_4:
	MOVW R8, 168(RSP)
	RET
_LBB0_5:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_pthread_mutex_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp2:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB0_8
	MOVD RSP, R9
	MOVD R8, 48(RSP)
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp3:
	CBZW R0, _LBB0_9
	ADDW $30, R0, R8
	JMP _LBB0_4
_LBB0_8:
	MOVW $30, R8
	JMP _LBB0_4
_LBB0_9:
	MOVW $-1, R9
	MOVD RSP, R8
	MOVD ZR, 144(RSP)
	MOVW R9, 116(RSP)
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrInit(SB)
_Ltmp4:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_11
	MOVW $51, R8
	JMP _LBB0_4
_LBB0_11:
	MOVD RSP, R8
	MOVW $1, R9
	ADD $120, RSP, R10
	MOVW R9, 16(R8)
	MOVD R10, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrSetType(SB)
_Ltmp5:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_13
	MOVW $52, R8
	JMP _LBB0_4
_LBB0_13:
	MOVD RSP, R8
	ADD $116, RSP, R9
	ADD $120, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrGetType(SB)
_Ltmp6:
	MOVD RSP, R8
	MOVWU 24(R8), R9
	MOVW $53, R8
	CBNZW R9, _LBB0_4
	MOVWU 116(RSP), R9
	CMPW $1, R9
	BNE _LBB0_4
	MOVD RSP, R8
	ADD $120, RSP, R9
	ADD $144, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp7:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_17
	MOVW $54, R8
	JMP _LBB0_4
_LBB0_17:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp8:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_19
	MOVW $55, R8
	JMP _LBB0_4
_LBB0_19:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp9:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_21
	MOVW $56, R8
	JMP _LBB0_4
_LBB0_21:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp10:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp11:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_23
	MOVW $57, R8
	JMP _LBB0_4
_LBB0_23:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp12:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_25
	MOVW $58, R8
	JMP _LBB0_4
_LBB0_25:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp13:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_27
	MOVW $59, R8
	JMP _LBB0_4
_LBB0_27:
	MOVD RSP, R8
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrDestroy(SB)
_Ltmp14:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_29
	MOVW $60, R8
	JMP _LBB0_4
_LBB0_29:
	PCDATA $1, $0
	CALL ·exercise_prefixed_cond(SB)
_Ltmp15:
	CBZW R0, _LBB0_31
	ADDW $70, R0, R8
	JMP _LBB0_4
_LBB0_31:
	PCDATA $1, $0
	CALL ·exercise_prefixed_rwlock(SB)
_Ltmp16:
	CBZW R0, _LBB0_33
	ADDW $90, R0, R8
	JMP _LBB0_4
_LBB0_33:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexLock(SB)
_Ltmp17:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_35
	MOVW $111, R8
	JMP _LBB0_4
_LBB0_35:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexUnlock(SB)
_Ltmp18:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_37
	MOVW $112, R8
	JMP _LBB0_4
_LBB0_37:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexDestroy(SB)
_Ltmp19:
	MOVD RSP, R8
	MOVW $113, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R8
	JMP _LBB0_4
_Lfunc_end0:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·2603814e3e2186c6(SB)
DATA gclocals·2603814e3e2186c6+0(SB)/4, $4
DATA gclocals·2603814e3e2186c6+4(SB)/4, $19
DATA gclocals·2603814e3e2186c6+8(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+9(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+10(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+11(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+12(SB)/1, $0x20
DATA gclocals·2603814e3e2186c6+13(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+14(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+15(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+16(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+17(SB)/1, $0x40
DATA gclocals·2603814e3e2186c6+18(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+19(SB)/1, $0x04
GLOBL gclocals·2603814e3e2186c6(SB), DUPOK|RODATA, $20

TEXT ·exercise_prefixed_mutex(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	MOVD RSP, R10
	STP (ZR, ZR), 56(RSP)
	MOVD R9, 48(RSP)
	STP (R9, ZR), 8(R10)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp20:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB1_2
	MOVW $1, R0
	JMP _LBB1_11
_LBB1_2:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp21:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_4
	MOVW $2, R0
	JMP _LBB1_11
_LBB1_4:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp22:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp23:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB1_8
	MOVD 48(RSP), R8
	MOVD RSP, R9
	ADD $56, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp24:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $110, R8
	BNE _LBB1_9
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp25:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_10
	MOVW $5, R0
	JMP _LBB1_11
_LBB1_8:
	MOVW $3, R0
	JMP _LBB1_11
_LBB1_9:
	MOVW $4, R0
	JMP _LBB1_11
_LBB1_10:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp26:
	MOVD RSP, R8
	MOVW $6, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
_LBB1_11:
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·18a3a95a1ff0a71e(SB)
DATA gclocals·18a3a95a1ff0a71e+0(SB)/4, $2
DATA gclocals·18a3a95a1ff0a71e+4(SB)/4, $9
DATA gclocals·18a3a95a1ff0a71e+8(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+9(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+10(SB)/1, $0x40
DATA gclocals·18a3a95a1ff0a71e+11(SB)/1, $0x00
GLOBL gclocals·18a3a95a1ff0a71e(SB), DUPOK|RODATA, $12

TEXT ·exercise_prefixed_cond(SB), $96-0
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $64, RSP, R9
	STP (ZR, ZR), 88(RSP)
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrInit(SB)
_Ltmp27:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_2
	MOVW $1, R0
	JMP _LBB2_12
_LBB2_2:
	MOVD RSP, R8
	ADD $96, RSP, R10
	STP (R10, ZR), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp28:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB2_4
	MOVW $2, R0
	JMP _LBB2_12
_LBB2_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	ADD $88, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp29:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB2_6
	MOVW $3, R0
	JMP _LBB2_12
_LBB2_6:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp30:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_8
	MOVW $4, R0
	JMP _LBB2_12
_LBB2_8:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp31:
	MOVD RSP, R8
	ADD $48, RSP, R9
	ADD $96, RSP, R10
	STP (R10, R9), 16(R8)
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp32:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CMPW $110, R8
	BNE _LBB2_11
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp33:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp34:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_13
	MOVW $6, R0
	JMP _LBB2_12
_LBB2_11:
	MOVW $5, R0
_LBB2_12:
	RET
_LBB2_13:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondSignal(SB)
_Ltmp35:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_15
	MOVW $7, R0
	JMP _LBB2_12
_LBB2_15:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondBroadcast(SB)
_Ltmp36:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_17
	MOVW $8, R0
	JMP _LBB2_12
_LBB2_17:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp37:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_19
	MOVW $9, R0
	JMP _LBB2_12
_LBB2_19:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp38:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_21
	MOVW $10, R0
	JMP _LBB2_12
_LBB2_21:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrDestroy(SB)
_Ltmp39:
	MOVD RSP, R8
	MOVW $11, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB2_12
_Lfunc_end2:
	FUNCDATA $0, gclocals·c7c2bf3b330983e6(SB)
DATA gclocals·c7c2bf3b330983e6+0(SB)/4, $3
DATA gclocals·c7c2bf3b330983e6+4(SB)/4, $0
GLOBL gclocals·c7c2bf3b330983e6(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4fea40b68a78c7cb(SB)
DATA gclocals·4fea40b68a78c7cb+0(SB)/4, $3
DATA gclocals·4fea40b68a78c7cb+4(SB)/4, $13
DATA gclocals·4fea40b68a78c7cb+8(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+9(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+10(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+11(SB)/1, $0x18
DATA gclocals·4fea40b68a78c7cb+12(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+13(SB)/1, $0x10
GLOBL gclocals·4fea40b68a78c7cb(SB), DUPOK|RODATA, $14

TEXT ·exercise_prefixed_rwlock(SB), $64-0
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD ZR, 64(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrInit(SB)
_Ltmp40:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_2
	MOVW $1, R0
	JMP _LBB3_10
_LBB3_2:
	MOVD RSP, R8
	ADD $40, RSP, R9
	ADD $64, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp41:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB3_4
	MOVW $2, R0
	JMP _LBB3_10
_LBB3_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp42:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_6
	MOVW $3, R0
	JMP _LBB3_10
_LBB3_6:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp43:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp44:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB3_9
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp45:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_11
	MOVW $5, R0
	JMP _LBB3_10
_LBB3_9:
	MOVW $4, R0
_LBB3_10:
	RET
_LBB3_11:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp46:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_13
	MOVW $6, R0
	JMP _LBB3_10
_LBB3_13:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp47:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB3_16
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp48:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_17
	MOVW $8, R0
	JMP _LBB3_10
_LBB3_16:
	MOVW $7, R0
	JMP _LBB3_10
_LBB3_17:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp49:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_19
	MOVW $9, R0
	JMP _LBB3_10
_LBB3_19:
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrDestroy(SB)
_Ltmp50:
	MOVD RSP, R8
	MOVW $10, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB3_10
_Lfunc_end3:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·mlib_sem_prefixed_selftest(SB), $48-8
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD ZR, 48(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_sem(SB)
_Ltmp51:
	CBZW R0, _LBB4_2
	ADDW $10, R0, R8
	JMP _LBB4_7
_LBB4_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_sem(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL ·exercise_prefixed_sem(SB)
_Ltmp52:
	CBZW R0, _LBB4_4
	ADDW $20, R0, R8
	JMP _LBB4_7
_LBB4_4:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_sem_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp53:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB4_6
	MOVD RSP, R9
	MOVD R8, 40(RSP)
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL ·exercise_prefixed_sem(SB)
_Ltmp54:
	ADDW $30, R0, R9
	CMPW $0, R0
	CSELW EQ, ZR, R9, R8
	JMP _LBB4_7
_LBB4_6:
	MOVW $30, R8
_LBB4_7:
	MOVW R8, 72(RSP)
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be91aa5e7697217d(SB)
DATA gclocals·be91aa5e7697217d+0(SB)/4, $3
DATA gclocals·be91aa5e7697217d+4(SB)/4, $1
DATA gclocals·be91aa5e7697217d+8(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+9(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+10(SB)/1, $0x00
GLOBL gclocals·be91aa5e7697217d(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·1dc925208ae72fbb(SB)
DATA gclocals·1dc925208ae72fbb+0(SB)/4, $3
DATA gclocals·1dc925208ae72fbb+4(SB)/4, $7
DATA gclocals·1dc925208ae72fbb+8(SB)/1, $0x00
DATA gclocals·1dc925208ae72fbb+9(SB)/1, $0x40
DATA gclocals·1dc925208ae72fbb+10(SB)/1, $0x20
GLOBL gclocals·1dc925208ae72fbb(SB), DUPOK|RODATA, $11

TEXT ·exercise_prefixed_sem(SB), $64-8
	PCDATA $1, $-1
	MOVW $-1, R9
	MOVD RSP, R8
	MOVW R9, 68(RSP)
	MOVD 88(RSP), R9
	MOVD $4294967296, R10
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 40(RSP)
	STP (R9, R10), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp55:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB5_2
	MOVW $1, R0
	JMP _LBB5_10
_LBB5_2:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp56:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp57:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_4
	MOVW $2, R0
	JMP _LBB5_10
_LBB5_4:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $48, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp58:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $110, R8
	BNE _LBB5_8
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp59:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $11, R8
	BNE _LBB5_9
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp60:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_11
	MOVW $5, R0
	JMP _LBB5_10
_LBB5_8:
	MOVW $3, R0
	JMP _LBB5_10
_LBB5_9:
	MOVW $4, R0
_LBB5_10:
	RET
_LBB5_11:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $68, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp61:
	MOVD RSP, R8
	MOVW $6, R0
	MOVWU 24(R8), R8
	CBNZW R8, _LBB5_10
	MOVWU 68(RSP), R8
	CMPW $1, R8
	BNE _LBB5_10
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp62:
	MOVD RSP, R8
	MOVW $7, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB5_10
_Lfunc_end5:
DATA c2go_global_gcmask·prefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·prefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·175d695a1edb77be(SB)
DATA gclocals·175d695a1edb77be+0(SB)/4, $2
DATA gclocals·175d695a1edb77be+4(SB)/4, $9
DATA gclocals·175d695a1edb77be+8(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+9(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+10(SB)/1, $0x20
DATA gclocals·175d695a1edb77be+11(SB)/1, $0x00
GLOBL gclocals·175d695a1edb77be(SB), DUPOK|RODATA, $12
