// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_pthread_prefixed_selftest(SB), $152-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0x9845c748
	LONG $0x00000000
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -96(BP)
	MOVUPS X0, -80(BP)
	MOVUPS X0, -64(BP)
	MOVQ SP, AX
	LEAQ -104(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp0:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_2
	ADDL $10, AX
	JMP _LBB0_26
_LBB0_2:
	MOVQ SP, AX
	LEAQ ·prefixed_global_mutex(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp1:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_4
	ADDL $20, AX
_LBB0_26:
	MOVL AX, 16(BP)
	RET
_LBB0_4:
	MOVQ SP, AX
	MOVQ ·_typeinfo_mlib_pthread_mutex_t(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000008
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp2:
	MOVQ SP, AX
	MOVQ 16(AX), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_5
	MOVQ AX, -112(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp3:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_8
	ADDL $30, AX
	JMP _LBB0_26
_LBB0_5:
	MOVL $30, AX
	JMP _LBB0_26
_LBB0_8:
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xfff445c7
	BYTE $0xff
	BYTE $0xff
	BYTE $0xff
	MOVQ SP, AX
	LEAQ -36(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrInit(SB)
_Ltmp4:
	MOVQ SP, AX
	MOVL $51, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -36(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x010840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrSetType(SB)
_Ltmp5:
	MOVQ SP, AX
	MOVL $52, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -12(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -36(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrGetType(SB)
_Ltmp6:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL $53, AX
	JNE _LBB0_26
	LONG $0x01f47d83
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -36(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp7:
	MOVQ SP, AX
	MOVL $54, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp8:
	MOVQ SP, AX
	MOVL $55, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp9:
	MOVQ SP, AX
	MOVL $56, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp10:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp11:
	MOVQ SP, AX
	MOVL $57, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp12:
	MOVQ SP, AX
	MOVL $58, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp13:
	MOVQ SP, AX
	MOVL $59, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -36(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrDestroy(SB)
_Ltmp14:
	MOVQ SP, AX
	MOVL $60, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	PCDATA $1, $0
	CALL ·exercise_prefixed_cond(SB)
_Ltmp15:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_21
	ADDL $70, AX
	JMP _LBB0_26
_LBB0_21:
	PCDATA $1, $0
	CALL ·exercise_prefixed_rwlock(SB)
_Ltmp16:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_23
	ADDL $90, AX
	JMP _LBB0_26
_LBB0_23:
	MOVQ SP, AX
	LEAQ -96(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexLock(SB)
_Ltmp17:
	MOVQ SP, AX
	MOVL $111, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -96(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexUnlock(SB)
_Ltmp18:
	MOVQ SP, AX
	MOVL $112, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB0_26
	MOVQ SP, AX
	LEAQ -96(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexDestroy(SB)
_Ltmp19:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $113, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
	JMP _LBB0_26
_Lfunc_end0:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·1f7fd9d699c7cfc6(SB)
DATA gclocals·1f7fd9d699c7cfc6+0(SB)/4, $4
DATA gclocals·1f7fd9d699c7cfc6+4(SB)/4, $19
DATA gclocals·1f7fd9d699c7cfc6+8(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+9(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+10(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+11(SB)/1, $0x40
DATA gclocals·1f7fd9d699c7cfc6+12(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+13(SB)/1, $0x04
DATA gclocals·1f7fd9d699c7cfc6+14(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+15(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+16(SB)/1, $0x04
DATA gclocals·1f7fd9d699c7cfc6+17(SB)/1, $0x20
DATA gclocals·1f7fd9d699c7cfc6+18(SB)/1, $0x00
DATA gclocals·1f7fd9d699c7cfc6+19(SB)/1, $0x04
GLOBL gclocals·1f7fd9d699c7cfc6(SB), DUPOK|RODATA, $20

TEXT ·exercise_prefixed_mutex(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	LONG $0x0841c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp20:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB1_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp21:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_6
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp22:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp23:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB1_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp24:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x3c107883
	MOVL CX, AX
	JNE _LBB1_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp25:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp26:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $6, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB1_6:
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·exercise_prefixed_cond(SB), $104-0
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xf045c748
	LONG $0x00000000
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -64(BP)
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrInit(SB)
_Ltmp27:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp28:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp29:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp30:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp31:
	MOVQ SP, AX
	LEAQ -64(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp32:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x3c187883
	MOVL CX, AX
	JNE _LBB2_11
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp33:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp34:
	MOVQ SP, AX
	MOVL $6, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondSignal(SB)
_Ltmp35:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondBroadcast(SB)
_Ltmp36:
	MOVQ SP, AX
	MOVL $8, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp37:
	MOVQ SP, AX
	MOVL $9, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp38:
	MOVQ SP, AX
	MOVL $10, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_11
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrDestroy(SB)
_Ltmp39:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $11, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB2_11:
	RET
_Lfunc_end2:
	FUNCDATA $0, gclocals·c7c2bf3b330983e6(SB)
DATA gclocals·c7c2bf3b330983e6+0(SB)/4, $3
DATA gclocals·c7c2bf3b330983e6+4(SB)/4, $0
GLOBL gclocals·c7c2bf3b330983e6(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4fea40b68a78c7cb(SB)
DATA gclocals·4fea40b68a78c7cb+0(SB)/4, $3
DATA gclocals·4fea40b68a78c7cb+4(SB)/4, $13
DATA gclocals·4fea40b68a78c7cb+8(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+9(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+10(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+11(SB)/1, $0x18
DATA gclocals·4fea40b68a78c7cb+12(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+13(SB)/1, $0x10
GLOBL gclocals·4fea40b68a78c7cb(SB), DUPOK|RODATA, $14

TEXT ·exercise_prefixed_rwlock(SB), $72-0
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -32(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrInit(SB)
_Ltmp40:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -32(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp41:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp42:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp43:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp44:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp45:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp46:
	MOVQ SP, AX
	MOVL $6, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp47:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp48:
	MOVQ SP, AX
	MOVL $8, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp49:
	MOVQ SP, AX
	MOVL $9, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_10
	MOVQ SP, AX
	LEAQ -32(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrDestroy(SB)
_Ltmp50:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $10, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB3_10:
	RET
_Lfunc_end3:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
TEXT ·mlib_sem_prefixed_selftest(SB), $56-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_prefixed_sem(SB)
_Ltmp51:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB4_2
	ADDL $10, AX
	JMP _LBB4_7
_LBB4_2:
	MOVQ SP, AX
	LEAQ ·prefixed_global_sem(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·exercise_prefixed_sem(SB)
_Ltmp52:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB4_4
	ADDL $20, AX
	JMP _LBB4_7
_LBB4_4:
	MOVQ SP, AX
	MOVQ ·_typeinfo_mlib_sem_t(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000008
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp53:
	MOVQ SP, AX
	MOVQ 16(AX), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB4_5
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL ·exercise_prefixed_sem(SB)
_Ltmp54:
	MOVL AX, CX
	ADDL $30, CX
	BYTE $0x85
	BYTE $0xc0
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
	JMP _LBB4_7
_LBB4_5:
	MOVL $30, AX
_LBB4_7:
	MOVL AX, 16(BP)
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be91aa5e7697217d(SB)
DATA gclocals·be91aa5e7697217d+0(SB)/4, $3
DATA gclocals·be91aa5e7697217d+4(SB)/4, $1
DATA gclocals·be91aa5e7697217d+8(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+9(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+10(SB)/1, $0x00
GLOBL gclocals·be91aa5e7697217d(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·1dc925208ae72fbb(SB)
DATA gclocals·1dc925208ae72fbb+0(SB)/4, $3
DATA gclocals·1dc925208ae72fbb+4(SB)/4, $7
DATA gclocals·1dc925208ae72fbb+8(SB)/1, $0x00
DATA gclocals·1dc925208ae72fbb+9(SB)/1, $0x40
DATA gclocals·1dc925208ae72fbb+10(SB)/1, $0x20
GLOBL gclocals·1dc925208ae72fbb(SB), DUPOK|RODATA, $11

TEXT ·exercise_prefixed_sem(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0xfffc45c7
	BYTE $0xff
	BYTE $0xff
	BYTE $0xff
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ $4294967296, DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp55:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB5_8
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp56:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp57:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB5_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp58:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x3c107883
	MOVL CX, AX
	JNE _LBB5_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp59:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x23087883
	MOVL CX, AX
	JNE _LBB5_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp60:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB5_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -4(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp61:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL $6, AX
	JNE _LBB5_8
	LONG $0x01fc7d83
	JNE _LBB5_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp62:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $7, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB5_8:
	RET
_Lfunc_end5:
DATA c2go_global_gcmask·prefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·prefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·1617295a1dc6485e(SB)
DATA gclocals·1617295a1dc6485e+0(SB)/4, $2
DATA gclocals·1617295a1dc6485e+4(SB)/4, $9
DATA gclocals·1617295a1dc6485e+8(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+9(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+10(SB)/1, $0x80
DATA gclocals·1617295a1dc6485e+11(SB)/1, $0x00
GLOBL gclocals·1617295a1dc6485e(SB), DUPOK|RODATA, $12
