//go:build darwin && arm64 && go1.25

// Code generated by c2go-bind. DO NOT EDIT.
// Input-derived material retains the input's copyright and license. This file
// also contains original C2Go runtime-support code copied from c2go-bind,
// available under AGPL-3.0-only or a separate commercial agreement.
// See https://github.com/c2gohq/c2go_bind/blob/main/LICENSING.md.

package namespaced

import (
	_ "github.com/c2gohq/c2go_libc"
	_ "github.com/c2gohq/c2go_libc/mlib"
	"reflect"
	"unsafe"
)

// ─── Types ──────────────────────────────────────────────────
type c2go_mlib_asprintf_result struct {
	formatted *byte
}
type c2go_mlib_cookie_state struct {
	bytes    [128]int8
	snapshot *byte
	position uint64
	length   uint64
}
type c2go_mlib_getcwd_result struct {
	allocated     *byte
	caller_buffer *byte
}
type c2go_mlib_realpath_result struct {
	allocated     *byte
	caller_buffer *byte
}
type c2go_mlib_scan_result struct {
	file_text     *byte
	text          *byte
	wide          *int32
	pointer       unsafe.Pointer
	line          *byte
	line_capacity uint64
	output        *byte
	output_size   uint64
}
type c2go_mlib_search_item struct {
	key     int32
	payload *c2go_mlib_search_payload
}
type c2go_mlib_search_payload struct {
	value  int32
	nested *int32
}
type c2go_mlib_search_queue struct {
	next     *c2go_mlib_search_queue
	previous *c2go_mlib_search_queue
	payload  *c2go_mlib_search_payload
	key      int32
}
type c2go_mlib_stdio_retire_owner struct {
	closed      *_c2go_mlib_FILE
	replacement *_c2go_mlib_FILE
}
type mlib_DIR struct {
	_state unsafe.Pointer
	_entry [280]int8
}
type mlib_cookie_io_functions_t struct {
	read  uintptr
	write uintptr
	seek  uintptr
	close uintptr
}
type mlib_entry struct {
	key  *byte
	data unsafe.Pointer
}
type mlib_glob_t struct {
	gl_pathc uint64
	gl_pathv **byte
	gl_offs  uint64
	__dummy1 int32
	__dummy2 [5]uint64
}
type mlib_hsearch_data struct {
	__tab     *mlib_hsearch_table
	__unused1 uint32
	__unused2 uint32
}
type mlib_pthread_cond_t struct {
	_state unsafe.Pointer
}
type mlib_pthread_mutex_t struct {
	_state unsafe.Pointer
}
type mlib_pthread_rwlock_t struct {
	_state unsafe.Pointer
}
type mlib_qelem struct {
	q_forw *mlib_qelem
	q_back *mlib_qelem
	q_data [1]int8
}
type mlib_regex struct {
	re_nsub      uint64
	__opaque     unsafe.Pointer
	__c2go_arena unsafe.Pointer
}
type mlib_sem_t struct {
	_state unsafe.Pointer
}

// ─── Forward-only opaque types ───────────────────
// Types declared in C as `typedef struct X X;` without a
// matching definition in any c2go-compiled TU. Emitted as
// zero-size opaque structs; pointers to them remain valid
// handles but contents are inaccessible from Go-side code.
type _c2go_mlib_FILE struct{}
type mlib_hsearch_table struct{}

// ─── Type-descriptor indirection (#218) ──────
// clang's Plan 9 .s loads each type descriptor from the per-type
// _typeinfo_<X> var below; each caches the *runtime._type computed
// once at init via reflect.TypeFor[T] (no value construction).
var (
	_typeinfo_c2go_mlib_asprintf_result unsafe.Pointer
	_typeinfo_c2go_mlib_cookie_state    unsafe.Pointer
	_typeinfo_c2go_mlib_getcwd_result   unsafe.Pointer
	_typeinfo_c2go_mlib_realpath_result unsafe.Pointer
	_typeinfo_c2go_mlib_scan_result     unsafe.Pointer
	_typeinfo_c2go_mlib_search_item     unsafe.Pointer
	_typeinfo_c2go_mlib_search_payload  unsafe.Pointer
	_typeinfo_c2go_mlib_search_queue    unsafe.Pointer
	_typeinfo_mlib_pthread_mutex_t      unsafe.Pointer
	_typeinfo_mlib_sem_t                unsafe.Pointer
)

// reflect.Type's 2nd interface word is the *runtime._type mallocgc wants.
func _c2go_rtype(t reflect.Type) unsafe.Pointer {
	return (*[2]unsafe.Pointer)(unsafe.Pointer(&t))[1]
}

func init() {
	_typeinfo_c2go_mlib_asprintf_result = _c2go_rtype(reflect.TypeFor[c2go_mlib_asprintf_result]())
	_typeinfo_c2go_mlib_cookie_state = _c2go_rtype(reflect.TypeFor[c2go_mlib_cookie_state]())
	_typeinfo_c2go_mlib_getcwd_result = _c2go_rtype(reflect.TypeFor[c2go_mlib_getcwd_result]())
	_typeinfo_c2go_mlib_realpath_result = _c2go_rtype(reflect.TypeFor[c2go_mlib_realpath_result]())
	_typeinfo_c2go_mlib_scan_result = _c2go_rtype(reflect.TypeFor[c2go_mlib_scan_result]())
	_typeinfo_c2go_mlib_search_item = _c2go_rtype(reflect.TypeFor[c2go_mlib_search_item]())
	_typeinfo_c2go_mlib_search_payload = _c2go_rtype(reflect.TypeFor[c2go_mlib_search_payload]())
	_typeinfo_c2go_mlib_search_queue = _c2go_rtype(reflect.TypeFor[c2go_mlib_search_queue]())
	_typeinfo_mlib_pthread_mutex_t = _c2go_rtype(reflect.TypeFor[mlib_pthread_mutex_t]())
	_typeinfo_mlib_sem_t = _c2go_rtype(reflect.TypeFor[mlib_sem_t]())
}

// ─── Function declarations ──────────────────────────────────
// Bodies provided by clang-emitted Plan 9 .s with TEXT ·<name>(SB)
// at ABI0. Go compiler auto-generates the ABIInternal wrapper.

//go:linkname MlibAsprintfPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_asprintf_prefixed_selftest
func MlibAsprintfPrefixedSelftest() int32

//go:linkname MlibDirentPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_dirent_prefixed_selftest
func MlibDirentPrefixedSelftest() int32

//go:linkname MlibFtwPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_ftw_prefixed_selftest
func MlibFtwPrefixedSelftest() int32

//go:linkname MlibGetcwdPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_getcwd_prefixed_selftest
func MlibGetcwdPrefixedSelftest() int32

//go:linkname MlibGlobPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_glob_prefixed_selftest
func MlibGlobPrefixedSelftest() int32

//go:linkname MlibPopenPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_popen_prefixed_selftest
func MlibPopenPrefixedSelftest() int32

//go:linkname MlibPthreadPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_pthread_prefixed_selftest
func MlibPthreadPrefixedSelftest() int32

//go:linkname MlibRealpathPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_realpath_prefixed_selftest
func MlibRealpathPrefixedSelftest() int32

//go:linkname MlibRegexPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_regex_prefixed_selftest
func MlibRegexPrefixedSelftest() int32

//go:linkname MlibSearchPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_search_prefixed_selftest
func MlibSearchPrefixedSelftest() int32

//go:linkname MlibSemPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_sem_prefixed_selftest
func MlibSemPrefixedSelftest() int32

//go:linkname MlibStdioPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_stdio_prefixed_selftest
func MlibStdioPrefixedSelftest() int32

//go:linkname MlibStdioPrefixedStdinSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_stdio_prefixed_stdin_selftest
func MlibStdioPrefixedStdinSelftest() int32

//go:linkname MlibStdioPrefixedStdoutSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_stdio_prefixed_stdout_selftest
func MlibStdioPrefixedStdoutSelftest() int32

//go:linkname MlibStdioRetirePrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_stdio_retire_prefixed_selftest
func MlibStdioRetirePrefixedSelftest() int32

//go:linkname MlibStringPrefixedSelftest github.com/c2gohq/c2go_libc/mlib/selftest/namespaced.mlib_string_prefixed_selftest
func MlibStringPrefixedSelftest() int32

// ─── §B4 Go-owned global storage ────────────────────────────
// Pointer-carrying file-scope C globals whose storage is owned
// by this Go package. Each var's layout mirrors the C global's
// gcmask (unsafe.Pointer per pointer word, uintptr filler), so
// the Go compiler emits matching gcdata bits and the runtime
// scans every pointer slot as a root. Clang's .s output
// suppresses the matching GLOBL trailer for each name below.
var prefixed_global_mutex unsafe.Pointer
var prefixed_global_sem unsafe.Pointer
var prefixed_thread_key unsafe.Pointer

// ─── Embedded runtime-support helpers ───────────────────────

// _c2go_cgocall is a thin shim around runtime.cgocall, used by the
// cross-world bridge for unmanaged function calls. Only emitted when
// the sidecar declares unmanaged extern functions; v0 always emits
// for simplicity.
//
// #218 fix: Go 1.25 stopped honouring the bodyless-decl form of
// //go:linkname (the symbol named on the local side was no longer
// rewritten to the runtime target — the .s reference would resolve
// to sqlitepkg._c2go_cgocall which the runtime never provided).
// Use the alias-then-wrap pattern: pull runtime.cgocall into a
// private local name via linkname, then expose the public name as
// a thin wrapper.
//
//go:linkname _runtime_cgocall runtime.cgocall
//go:noescape
func _runtime_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32

//go:nosplit
func _c2go_cgocall(fn unsafe.Pointer, frame unsafe.Pointer) int32 {
	return _runtime_cgocall(fn, frame)
}

// _c2go_typedmemmove copies a typed value, invoking the bulk write
// barrier when the type has pointers. Used by realloc lowering and
// the c2go-memcpy-typing pass.
//
//go:linkname _runtime_typedmemmove runtime.typedmemmove
//go:noescape
func _runtime_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer)

//go:nosplit
func _c2go_typedmemmove(typ unsafe.Pointer, dst, src unsafe.Pointer) {
	_runtime_typedmemmove(typ, dst, src)
}

// _c2go_typedMemmoveArray is the per-element loop used by the
// c2go-memcpy-typing pass when copying arrays of pointerful elements.
//
//go:nosplit
func _c2go_typedMemmoveArray(typ unsafe.Pointer, dst, src unsafe.Pointer, n uintptr) {
	sz := *(*uintptr)(typ) // _type.Size_ at offset 0 (pinned Go 1.22+)
	for i := uintptr(0); i < n; i++ {
		_c2go_typedmemmove(typ,
			unsafe.Pointer(uintptr(dst)+i*sz),
			unsafe.Pointer(uintptr(src)+i*sz))
	}
}

// _c2go_writePtr is the slow-path of the inline write barrier.
// The LLVM c2go-write-barriers pass emits an inline check of
// runtime.writeBarrier.enabled; on the slow path it calls this
// helper. The Go compiler, seeing the *slot = val store in this
// body, emits the real inline barrier sequence (gcWriteBarrier2
// reservation + push). We never touch the special-ABI helper directly.
//
//go:nosplit
func _c2go_writePtr(slot *unsafe.Pointer, val unsafe.Pointer) {
	*slot = val
}

// errString is used by the §E2 unmanaged-extern wrappers' dlsym-
// failure panic path. Kept zero-import (no fmt) so the wrappers
// don't drag in extra runtime cost.
func errString(err error) string {
	if err == nil {
		return "<nil>"
	}
	return err.Error()
}
