// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_dirent_prefixed_selftest(SB), $400-8
	PCDATA $1, $-1
	MOVD RSP, R8
	MOVD $_L_str<>(SB), R9
	MOVD ZR, 80(RSP)
	STP (ZR, ZR), 104(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_opendir(SB)
_Ltmp0:
	MOVD RSP, R8
	MOVD 80(RSP), R9
	MOVD 16(R8), R8
	MOVD R9, 112(RSP)
	CBZ R8, _LBB0_7
	MOVD R8, 96(RSP)
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp1:
	MOVD 96(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp2:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_16
	WORD $0x38413d09
	CBZW R9, _LBB0_8
	MOVW $1, R10
	MOVWU R9, R11
	MOVD ZR, R12
	MOVWU R10, R9
	MOVD $_L_str<>(SB), R14
_LBB0_4:
	WORD $0x386c69ca
	MOVWU R11, R13
	CMPW R10, R11
	MOVWU R9, R11
	MOVD R12, R9
	MOVWU R13, R10
	BNE _LBB0_9
	MOVWU R11, R9
	MOVWU R9, R10
	ADDW $1, R11, R9
	WORD $0x386a690d
	MOVD R10, R12
	MOVWU R13, R11
	CBNZW R13, _LBB0_4
	MOVD R10, R9
	MOVWU ZR, R10
	JMP _LBB0_9
_LBB0_7:
	MOVW $1, R8
	JMP _LBB0_23
_LBB0_8:
	MOVD ZR, R9
	MOVWU ZR, R10
	MOVD $_L_str<>(SB), R14
_LBB0_9:
	WORD $0x386969c8
	CMPW R8, R10
	BNE _LBB0_16
	MOVD 96(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp3:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_22
	WORD $0x38413d09
	MOVD $_L_str_1<>(SB), R14
	CBZW R9, _LBB0_17
	MOVW $1, R10
	MOVWU R9, R11
	MOVD ZR, R12
	MOVWU R10, R9
_LBB0_13:
	WORD $0x386c69ca
	MOVWU R11, R13
	CMPW R10, R11
	MOVWU R9, R11
	MOVD R12, R9
	MOVWU R13, R10
	BNE _LBB0_19
	MOVWU R11, R9
	MOVWU R9, R10
	ADDW $1, R11, R9
	WORD $0x386a690d
	MOVD R10, R12
	MOVWU R13, R11
	CBNZW R13, _LBB0_13
	MOVD R10, R9
	JMP _LBB0_18
_LBB0_16:
	MOVW $2, R8
	JMP _LBB0_23
_LBB0_17:
	MOVD ZR, R9
_LBB0_18:
	MOVWU ZR, R10
_LBB0_19:
	WORD $0x386969c8
	CMPW R8, R10
	BNE _LBB0_22
	MOVD 96(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_rewinddir(SB)
_Ltmp4:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp5:
	MOVD 96(RSP), R8
	MOVD RSP, R9
	ADD $112, RSP, R10
	ADD $120, RSP, R11
	STP (R11, R10), 16(R9)
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir_r(SB)
_Ltmp6:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CBZW R8, _LBB0_24
	MOVW $4, R8
	JMP _LBB0_23
_LBB0_22:
	MOVW $3, R8
_LBB0_23:
	MOVW R8, 424(RSP)
	RET
_LBB0_24:
	MOVD 112(RSP), R8
	ADD $120, RSP, R9
	CMP R9, R8
	BNE _LBB0_40
	WORD $0x38413d09
	CBZW R9, _LBB0_30
	MOVW $1, R10
	MOVWU R9, R11
	MOVD ZR, R12
	MOVWU R10, R9
	MOVD $_L_str<>(SB), R14
_LBB0_27:
	WORD $0x386c69ca
	MOVWU R11, R13
	CMPW R10, R11
	MOVWU R9, R11
	MOVD R12, R9
	MOVWU R13, R10
	BNE _LBB0_31
	MOVWU R11, R9
	MOVWU R9, R10
	ADDW $1, R11, R9
	WORD $0x386a690d
	MOVD R10, R12
	MOVWU R13, R11
	CBNZW R13, _LBB0_27
	MOVD R10, R9
	MOVWU ZR, R10
	JMP _LBB0_31
_LBB0_30:
	MOVD ZR, R9
	MOVWU ZR, R10
	MOVD $_L_str<>(SB), R14
_LBB0_31:
	WORD $0x386969c8
	CMPW R8, R10
	BNE _LBB0_40
	MOVD 96(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_dirfd(SB)
_Ltmp7:
	MOVD RSP, R8
	MOVD RSP, R9
	MOVWU 16(R8), R8
	MOVW R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·dup(SB)
_Ltmp8:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	TBNZ $31, R8, _LBB0_41
	MOVWU R8, R9
	MOVD RSP, R8
	MOVW R9, 80(RSP)
	MOVW R9, 8(R8)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_fdopendir(SB)
_Ltmp9:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_42
	MOVD R8, 88(RSP)
	PCDATA $1, $4
	CALL ·ForceGC(SB)
_Ltmp10:
	MOVD 88(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp11:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_47
	WORD $0x38413d09
	CBZW R9, _LBB0_43
	MOVW $1, R10
	MOVWU R9, R11
	MOVD ZR, R12
	MOVWU R10, R9
	MOVD $_L_str<>(SB), R14
_LBB0_37:
	WORD $0x386c69ca
	MOVWU R11, R13
	CMPW R10, R11
	MOVWU R9, R11
	MOVD R12, R9
	MOVWU R13, R10
	BNE _LBB0_44
	MOVWU R11, R9
	MOVWU R9, R10
	ADDW $1, R11, R9
	WORD $0x386a690d
	MOVD R10, R12
	MOVWU R13, R11
	CBNZW R13, _LBB0_37
	MOVD R10, R9
	MOVWU ZR, R10
	JMP _LBB0_44
_LBB0_40:
	MOVW $5, R8
	JMP _LBB0_23
_LBB0_41:
	MOVW $6, R8
	JMP _LBB0_23
_LBB0_42:
	MOVWU 80(RSP), R9
	MOVD RSP, R8
	MOVW R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·close(SB)
_Ltmp12:
	MOVW $7, R8
	JMP _LBB0_23
_LBB0_43:
	MOVD ZR, R9
	MOVWU ZR, R10
	MOVD $_L_str<>(SB), R14
_LBB0_44:
	WORD $0x386969c8
	CMPW R8, R10
	BNE _LBB0_47
	MOVD 88(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp13:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_48
	MOVW $9, R8
	JMP _LBB0_23
_LBB0_47:
	MOVW $8, R8
	JMP _LBB0_23
_LBB0_48:
	MOVD 96(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp14:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_50
	MOVW $10, R8
	JMP _LBB0_23
_LBB0_50:
	MOVD $·force_gc_in_compare(SB), R9
	MOVW $1, R10
	MOVD $_L_str<>(SB), R8
	MOVB R10, ·force_gc_in_compare(SB)
	MOVD RSP, R9
	MOVD $·compare_reverse_alpha(SB), R10
	MOVD ZR, 104(RSP)
	STP (ZR, R10), 24(R9)
	ADD $104, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $5
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_scandir(SB)
_Ltmp15:
	MOVD RSP, R8
	MOVWU 40(R8), R8
	CMPW $2, R8
	MOVW R8, 80(RSP)
	BGE _LBB0_52
	MOVW $11, R8
	JMP _LBB0_23
_LBB0_52:
	PCDATA $1, $5
	CALL ·ForceGC(SB)
_Ltmp16:
	MOVWU 80(RSP), R8
	MOVD ZR, R9
	MOVWU ZR, R12
	MOVWU ZR, R10
	MOVD $_L_str_1<>(SB), R20
	MOVD R8, 64(RSP)
	JMP _LBB0_54
_LBB0_53:
	MOVD 64(RSP), R9
	ADD $1, R21, R8
	MOVWU R11, R10
	MOVWU R1, R12
	CMP R9, R8
	MOVD R8, R9
	BEQ _LBB0_69
_LBB0_54:
	MOVD 104(RSP), R8
	MOVD R9, R21
	WORD $0x8b090d09
	MOVD 0(R9), R11
	WORD $0x38413d60
	CBZW R0, _LBB0_59
	MOVW $1, R13
	MOVWU R0, R14
	MOVD ZR, R16
	MOVD $_L_str<>(SB), R19
_LBB0_56:
	WORD $0x38706a6f
	CMPW R15, R14
	BNE _LBB0_60
	MOVWU R13, R14
	ADDW $1, R13, R15
	MOVWU R14, R16
	MOVWU R15, R13
	WORD $0x38706971
	MOVWU R17, R14
	CBNZW R17, _LBB0_56
	CMPW $2, R15
	WORD $0x1a9f1581
	JMP _LBB0_61
_LBB0_59:
	MOVWU R12, R1
	MOVD ZR, R13
	MOVWU ZR, R11
	JMP _LBB0_66
_LBB0_60:
	MOVWU R12, R1
_LBB0_61:
	MOVW $1, R12
	MOVD ZR, R14
_LBB0_62:
	MOVD R14, R13
	WORD $0x386e6a8e
	CMPW R14, R0
	BNE _LBB0_65
	MOVWU R12, R13
	ADDW $1, R12, R12
	WORD $0x386d696f
	MOVD R13, R14
	MOVWU R15, R0
	CBNZW R15, _LBB0_62
	MOVWU ZR, R11
	JMP _LBB0_66
_LBB0_65:
	MOVWU R0, R11
_LBB0_66:
	WORD $0x386d6a8c
	CMPW R12, R11
	WORD $0x1a9f154b
	CBZ R21, _LBB0_53
	MOVD R9, R10
	SUB $8, R9, R9
	MOVD R8, 96(RSP)
	MOVD RSP, R8
	MOVD R21, 80(RSP)
	STP (R9, R10), 8(R8)
	WORD $0x29092fe1
	PCDATA $1, $3
	CALL ·compare_reverse_alpha(SB)
_Ltmp17:
	WORD $0x29492fe1
	MOVD 80(RSP), R21
	MOVD $_L_str_1<>(SB), R20
	CMPW $0, R0
	BLE _LBB0_53
	MOVW $12, R8
	JMP _LBB0_23
_LBB0_69:
	MOVW $13, R8
	CBZW R1, _LBB0_23
	CBZW R11, _LBB0_23
	MOVD RSP, R8
	MOVD $·select_dots(SB), R9
	MOVD $·compare_reverse_alpha(SB), R10
	MOVD ZR, 104(RSP)
	STP (R9, R10), 24(R8)
	ADD $104, RSP, R10
	MOVD $_L_str<>(SB), R9
	STP (R9, R10), 8(R8)
	PCDATA $1, $5
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_scandir(SB)
_Ltmp18:
	MOVD RSP, R8
	MOVWU 40(R8), R8
	CMPW $2, R8
	BNE _LBB0_77
	PCDATA $1, $5
	CALL ·ForceGC(SB)
_Ltmp19:
	MOVD 104(RSP), R8
	MOVD 0(R8), R9
	WORD $0x38413d2a
	CBZW R10, _LBB0_78
	MOVW $1, R11
	MOVWU R10, R12
	MOVD ZR, R13
	MOVWU R11, R10
_LBB0_74:
	MOVD $_L_str_1<>(SB), R11
	MOVWU R12, R14
	WORD $0x386d696b
	CMPW R11, R12
	MOVWU R10, R12
	MOVD R13, R10
	MOVWU R14, R11
	BNE _LBB0_80
	MOVWU R12, R10
	MOVWU R10, R11
	ADDW $1, R12, R10
	WORD $0x386b692e
	MOVD R11, R13
	MOVWU R14, R12
	CBNZW R14, _LBB0_74
	MOVD R11, R10
	JMP _LBB0_79
_LBB0_77:
	MOVW $14, R8
	JMP _LBB0_23
_LBB0_78:
	MOVD ZR, R10
_LBB0_79:
	MOVWU ZR, R11
_LBB0_80:
	MOVD $_L_str_1<>(SB), R9
	WORD $0x386a6929
	CMPW R9, R11
	BNE _LBB0_86
	MOVD 8(R8), R8
	WORD $0x38413d09
	CBZW R9, _LBB0_87
	MOVW $1, R10
	MOVWU R9, R11
	MOVD ZR, R12
	MOVWU R10, R9
_LBB0_83:
	MOVD $_L_str<>(SB), R10
	MOVWU R11, R13
	WORD $0x386c694a
	CMPW R10, R11
	MOVWU R9, R11
	MOVD R12, R9
	MOVWU R13, R10
	BNE _LBB0_89
	MOVWU R11, R9
	MOVWU R9, R10
	ADDW $1, R11, R9
	WORD $0x386a690d
	MOVD R10, R12
	MOVWU R13, R11
	CBNZW R13, _LBB0_83
	MOVD R10, R9
	JMP _LBB0_88
_LBB0_86:
	MOVW $15, R8
	JMP _LBB0_23
_LBB0_87:
	MOVD ZR, R9
_LBB0_88:
	MOVWU ZR, R10
_LBB0_89:
	MOVD $_L_str<>(SB), R11
	WORD $0x38696969
	WORD $0x6b29015f
	MOVW $15, R9
	CSELW EQ, ZR, R9, R8
	JMP _LBB0_23
_Lfunc_end0:
	FUNCDATA $0, gclocals·726b3031c54e09e2(SB)
DATA gclocals·726b3031c54e09e2+0(SB)/4, $6
DATA gclocals·726b3031c54e09e2+4(SB)/4, $1
DATA gclocals·726b3031c54e09e2+8(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+9(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+10(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+11(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+12(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+13(SB)/1, $0x00
GLOBL gclocals·726b3031c54e09e2(SB), DUPOK|RODATA, $14

	FUNCDATA $1, gclocals·078f91c27fca4f68(SB)
DATA gclocals·078f91c27fca4f68+0(SB)/4, $6
DATA gclocals·078f91c27fca4f68+4(SB)/4, $51
DATA gclocals·078f91c27fca4f68+8(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+9(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+10(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+11(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+12(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+13(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+14(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+15(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+16(SB)/1, $0x60
DATA gclocals·078f91c27fca4f68+17(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+18(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+19(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+20(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+21(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+22(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+23(SB)/1, $0x70
DATA gclocals·078f91c27fca4f68+24(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+25(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+26(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+27(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+28(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+29(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+30(SB)/1, $0x30
DATA gclocals·078f91c27fca4f68+31(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+32(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+33(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+34(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+35(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+36(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+37(SB)/1, $0x38
DATA gclocals·078f91c27fca4f68+38(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+39(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+40(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+41(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+42(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+43(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+44(SB)/1, $0x20
DATA gclocals·078f91c27fca4f68+45(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+46(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+47(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+48(SB)/1, $0x00
DATA gclocals·078f91c27fca4f68+49(SB)/1, $0x00
GLOBL gclocals·078f91c27fca4f68(SB), DUPOK|RODATA, $50

TEXT ·compare_reverse_alpha(SB), $48-16
	PCDATA $1, $-1
	MOVBU ·force_gc_in_compare(SB), R11
	LDP 72(RSP), (R10, R8)
	CMPW $1, R11
	BNE _LBB1_2
	MOVB ZR, ·force_gc_in_compare(SB)
	STP (R8, R10), 40(RSP)
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp20:
	LDP 40(RSP), (R8, R10)
_LBB1_2:
	MOVD RSP, R9
	STP (R8, R10), 40(RSP)
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·alphasort(SB)
_Ltmp21:
	MOVD RSP, R8
	MOVWU 24(R8), R0
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·e1f3e66d4bb68923(SB)
DATA gclocals·e1f3e66d4bb68923+0(SB)/4, $2
DATA gclocals·e1f3e66d4bb68923+4(SB)/4, $2
DATA gclocals·e1f3e66d4bb68923+8(SB)/1, $0x03
DATA gclocals·e1f3e66d4bb68923+9(SB)/1, $0x03
GLOBL gclocals·e1f3e66d4bb68923(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·9300ac6ea5fafef0(SB)
DATA gclocals·9300ac6ea5fafef0+0(SB)/4, $2
DATA gclocals·9300ac6ea5fafef0+4(SB)/4, $7
DATA gclocals·9300ac6ea5fafef0+8(SB)/1, $0x00
DATA gclocals·9300ac6ea5fafef0+9(SB)/1, $0x60
GLOBL gclocals·9300ac6ea5fafef0(SB), DUPOK|RODATA, $10

TEXT ·select_dots(SB), NOSPLIT|NOFRAME, $0-8
	MOVD 8(RSP), R9
	MOVD $_L_str_1<>(SB), R8
	WORD $0x38413d20
	CBZW R0, _LBB2_10
	MOVW $1, R11
	MOVD $_L_str<>(SB), R10
	MOVWU R0, R12
	MOVD ZR, R14
_LBB2_2:
	WORD $0x386e694d
	CMPW R13, R12
	BNE _LBB2_6
	MOVWU R11, R12
	ADDW $1, R11, R13
	MOVWU R12, R14
	MOVWU R13, R11
	WORD $0x386e692f
	MOVWU R15, R12
	CBNZW R15, _LBB2_2
	CMPW $2, R13
	BNE _LBB2_6
	MOVW $1, R0
	RET
_LBB2_6:
	MOVW $1, R10
	MOVD ZR, R12
_LBB2_7:
	MOVD R12, R11
	WORD $0x386c690c
	CMPW R12, R0
	MOVWU R10, R12
	MOVD R11, R10
	MOVWU R0, R11
	BNE _LBB2_12
	MOVWU R12, R10
	MOVWU R10, R11
	ADDW $1, R12, R10
	WORD $0x386b692d
	MOVD R11, R12
	MOVWU R13, R0
	CBNZW R13, _LBB2_7
	MOVD R11, R10
	JMP _LBB2_11
_LBB2_10:
	MOVD ZR, R10
_LBB2_11:
	MOVWU ZR, R11
_LBB2_12:
	WORD $0x386a6908
	CMPW R8, R11
	CSETW EQ, R0
	RET
_Lfunc_end2:
TEXT ·mlib_pthread_prefixed_selftest(SB), $144-8
	PCDATA $1, $-1
	WORD $0x6f00e400
	MOVD RSP, R8
	ADD $104, RSP, R9
	MOVD ZR, 144(RSP)
	MOVD ZR, 104(RSP)
	FMOVQ F0, 56(RSP)
	FMOVQ F0, 72(RSP)
	FMOVQ F0, 88(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp22:
	CBZW R0, _LBB3_2
	ADDW $10, R0, R8
	JMP _LBB3_4
_LBB3_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_mutex(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp23:
	CBZW R0, _LBB3_5
	ADDW $20, R0, R8
_LBB3_4:
	MOVW R8, 168(RSP)
	RET
_LBB3_5:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_pthread_mutex_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp24:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB3_8
	MOVD RSP, R9
	MOVD R8, 48(RSP)
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp25:
	CBZW R0, _LBB3_9
	ADDW $30, R0, R8
	JMP _LBB3_4
_LBB3_8:
	MOVW $30, R8
	JMP _LBB3_4
_LBB3_9:
	MOVW $-1, R9
	MOVD RSP, R8
	MOVD ZR, 144(RSP)
	MOVW R9, 116(RSP)
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrInit(SB)
_Ltmp26:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_11
	MOVW $51, R8
	JMP _LBB3_4
_LBB3_11:
	MOVD RSP, R8
	MOVW $1, R9
	ADD $120, RSP, R10
	MOVW R9, 16(R8)
	MOVD R10, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrSetType(SB)
_Ltmp27:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB3_13
	MOVW $52, R8
	JMP _LBB3_4
_LBB3_13:
	MOVD RSP, R8
	ADD $116, RSP, R9
	ADD $120, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrGetType(SB)
_Ltmp28:
	MOVD RSP, R8
	MOVWU 24(R8), R9
	MOVW $53, R8
	CBNZW R9, _LBB3_4
	MOVWU 116(RSP), R9
	CMPW $1, R9
	BNE _LBB3_4
	MOVD RSP, R8
	ADD $120, RSP, R9
	ADD $144, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp29:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB3_17
	MOVW $54, R8
	JMP _LBB3_4
_LBB3_17:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp30:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_19
	MOVW $55, R8
	JMP _LBB3_4
_LBB3_19:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp31:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_21
	MOVW $56, R8
	JMP _LBB3_4
_LBB3_21:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp32:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp33:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_23
	MOVW $57, R8
	JMP _LBB3_4
_LBB3_23:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp34:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_25
	MOVW $58, R8
	JMP _LBB3_4
_LBB3_25:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp35:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_27
	MOVW $59, R8
	JMP _LBB3_4
_LBB3_27:
	MOVD RSP, R8
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrDestroy(SB)
_Ltmp36:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_29
	MOVW $60, R8
	JMP _LBB3_4
_LBB3_29:
	PCDATA $1, $0
	CALL ·exercise_prefixed_cond(SB)
_Ltmp37:
	CBZW R0, _LBB3_31
	ADDW $70, R0, R8
	JMP _LBB3_4
_LBB3_31:
	PCDATA $1, $0
	CALL ·exercise_prefixed_rwlock(SB)
_Ltmp38:
	CBZW R0, _LBB3_33
	ADDW $90, R0, R8
	JMP _LBB3_4
_LBB3_33:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexLock(SB)
_Ltmp39:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_35
	MOVW $111, R8
	JMP _LBB3_4
_LBB3_35:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexUnlock(SB)
_Ltmp40:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_37
	MOVW $112, R8
	JMP _LBB3_4
_LBB3_37:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexDestroy(SB)
_Ltmp41:
	MOVD RSP, R8
	MOVW $113, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R8
	JMP _LBB3_4
_Lfunc_end3:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·2603814e3e2186c6(SB)
DATA gclocals·2603814e3e2186c6+0(SB)/4, $4
DATA gclocals·2603814e3e2186c6+4(SB)/4, $19
DATA gclocals·2603814e3e2186c6+8(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+9(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+10(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+11(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+12(SB)/1, $0x20
DATA gclocals·2603814e3e2186c6+13(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+14(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+15(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+16(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+17(SB)/1, $0x40
DATA gclocals·2603814e3e2186c6+18(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+19(SB)/1, $0x04
GLOBL gclocals·2603814e3e2186c6(SB), DUPOK|RODATA, $20

TEXT ·exercise_prefixed_mutex(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	MOVD RSP, R10
	STP (ZR, ZR), 56(RSP)
	MOVD R9, 48(RSP)
	STP (R9, ZR), 8(R10)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp42:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB4_2
	MOVW $1, R0
	JMP _LBB4_11
_LBB4_2:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp43:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_4
	MOVW $2, R0
	JMP _LBB4_11
_LBB4_4:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp44:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp45:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB4_8
	MOVD 48(RSP), R8
	MOVD RSP, R9
	ADD $56, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp46:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $110, R8
	BNE _LBB4_9
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp47:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_10
	MOVW $5, R0
	JMP _LBB4_11
_LBB4_8:
	MOVW $3, R0
	JMP _LBB4_11
_LBB4_9:
	MOVW $4, R0
	JMP _LBB4_11
_LBB4_10:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp48:
	MOVD RSP, R8
	MOVW $6, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
_LBB4_11:
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·18a3a95a1ff0a71e(SB)
DATA gclocals·18a3a95a1ff0a71e+0(SB)/4, $2
DATA gclocals·18a3a95a1ff0a71e+4(SB)/4, $9
DATA gclocals·18a3a95a1ff0a71e+8(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+9(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+10(SB)/1, $0x40
DATA gclocals·18a3a95a1ff0a71e+11(SB)/1, $0x00
GLOBL gclocals·18a3a95a1ff0a71e(SB), DUPOK|RODATA, $12

TEXT ·exercise_prefixed_cond(SB), $96-0
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $64, RSP, R9
	STP (ZR, ZR), 88(RSP)
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrInit(SB)
_Ltmp49:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_2
	MOVW $1, R0
	JMP _LBB5_12
_LBB5_2:
	MOVD RSP, R8
	ADD $96, RSP, R10
	STP (R10, ZR), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp50:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB5_4
	MOVW $2, R0
	JMP _LBB5_12
_LBB5_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	ADD $88, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp51:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB5_6
	MOVW $3, R0
	JMP _LBB5_12
_LBB5_6:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp52:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_8
	MOVW $4, R0
	JMP _LBB5_12
_LBB5_8:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp53:
	MOVD RSP, R8
	ADD $48, RSP, R9
	ADD $96, RSP, R10
	STP (R10, R9), 16(R8)
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp54:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CMPW $110, R8
	BNE _LBB5_11
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp55:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp56:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_13
	MOVW $6, R0
	JMP _LBB5_12
_LBB5_11:
	MOVW $5, R0
_LBB5_12:
	RET
_LBB5_13:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondSignal(SB)
_Ltmp57:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_15
	MOVW $7, R0
	JMP _LBB5_12
_LBB5_15:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondBroadcast(SB)
_Ltmp58:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_17
	MOVW $8, R0
	JMP _LBB5_12
_LBB5_17:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp59:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_19
	MOVW $9, R0
	JMP _LBB5_12
_LBB5_19:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp60:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_21
	MOVW $10, R0
	JMP _LBB5_12
_LBB5_21:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrDestroy(SB)
_Ltmp61:
	MOVD RSP, R8
	MOVW $11, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB5_12
_Lfunc_end5:
	FUNCDATA $0, gclocals·c7c2bf3b330983e6(SB)
DATA gclocals·c7c2bf3b330983e6+0(SB)/4, $3
DATA gclocals·c7c2bf3b330983e6+4(SB)/4, $0
GLOBL gclocals·c7c2bf3b330983e6(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4fea40b68a78c7cb(SB)
DATA gclocals·4fea40b68a78c7cb+0(SB)/4, $3
DATA gclocals·4fea40b68a78c7cb+4(SB)/4, $13
DATA gclocals·4fea40b68a78c7cb+8(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+9(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+10(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+11(SB)/1, $0x18
DATA gclocals·4fea40b68a78c7cb+12(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+13(SB)/1, $0x10
GLOBL gclocals·4fea40b68a78c7cb(SB), DUPOK|RODATA, $14

TEXT ·exercise_prefixed_rwlock(SB), $64-0
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD ZR, 64(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrInit(SB)
_Ltmp62:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_2
	MOVW $1, R0
	JMP _LBB6_10
_LBB6_2:
	MOVD RSP, R8
	ADD $40, RSP, R9
	ADD $64, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp63:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB6_4
	MOVW $2, R0
	JMP _LBB6_10
_LBB6_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp64:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_6
	MOVW $3, R0
	JMP _LBB6_10
_LBB6_6:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp65:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp66:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB6_9
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp67:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_11
	MOVW $5, R0
	JMP _LBB6_10
_LBB6_9:
	MOVW $4, R0
_LBB6_10:
	RET
_LBB6_11:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp68:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_13
	MOVW $6, R0
	JMP _LBB6_10
_LBB6_13:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp69:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB6_16
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp70:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_17
	MOVW $8, R0
	JMP _LBB6_10
_LBB6_16:
	MOVW $7, R0
	JMP _LBB6_10
_LBB6_17:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp71:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_19
	MOVW $9, R0
	JMP _LBB6_10
_LBB6_19:
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrDestroy(SB)
_Ltmp72:
	MOVD RSP, R8
	MOVW $10, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB6_10
_Lfunc_end6:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·mlib_sem_prefixed_selftest(SB), $48-8
	PCDATA $1, $-1
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD ZR, 48(RSP)
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_sem(SB)
_Ltmp73:
	CBZW R0, _LBB7_2
	ADDW $10, R0, R8
	JMP _LBB7_7
_LBB7_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_sem(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL ·exercise_prefixed_sem(SB)
_Ltmp74:
	CBZW R0, _LBB7_4
	ADDW $20, R0, R8
	JMP _LBB7_7
_LBB7_4:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_sem_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp75:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB7_6
	MOVD RSP, R9
	MOVD R8, 40(RSP)
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL ·exercise_prefixed_sem(SB)
_Ltmp76:
	ADDW $30, R0, R9
	CMPW $0, R0
	CSELW EQ, ZR, R9, R8
	JMP _LBB7_7
_LBB7_6:
	MOVW $30, R8
_LBB7_7:
	MOVW R8, 72(RSP)
	RET
_Lfunc_end7:
	FUNCDATA $0, gclocals·be91aa5e7697217d(SB)
DATA gclocals·be91aa5e7697217d+0(SB)/4, $3
DATA gclocals·be91aa5e7697217d+4(SB)/4, $1
DATA gclocals·be91aa5e7697217d+8(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+9(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+10(SB)/1, $0x00
GLOBL gclocals·be91aa5e7697217d(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·1dc925208ae72fbb(SB)
DATA gclocals·1dc925208ae72fbb+0(SB)/4, $3
DATA gclocals·1dc925208ae72fbb+4(SB)/4, $7
DATA gclocals·1dc925208ae72fbb+8(SB)/1, $0x00
DATA gclocals·1dc925208ae72fbb+9(SB)/1, $0x40
DATA gclocals·1dc925208ae72fbb+10(SB)/1, $0x20
GLOBL gclocals·1dc925208ae72fbb(SB), DUPOK|RODATA, $11

TEXT ·exercise_prefixed_sem(SB), $64-8
	PCDATA $1, $-1
	MOVW $-1, R9
	MOVD RSP, R8
	MOVW R9, 68(RSP)
	MOVD 88(RSP), R9
	MOVD $4294967296, R10
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 40(RSP)
	STP (R9, R10), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp77:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB8_2
	MOVW $1, R0
	JMP _LBB8_10
_LBB8_2:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp78:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp79:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB8_4
	MOVW $2, R0
	JMP _LBB8_10
_LBB8_4:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $48, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp80:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $110, R8
	BNE _LBB8_8
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp81:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $11, R8
	BNE _LBB8_9
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp82:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB8_11
	MOVW $5, R0
	JMP _LBB8_10
_LBB8_8:
	MOVW $3, R0
	JMP _LBB8_10
_LBB8_9:
	MOVW $4, R0
_LBB8_10:
	RET
_LBB8_11:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $68, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp83:
	MOVD RSP, R8
	MOVW $6, R0
	MOVWU 24(R8), R8
	CBNZW R8, _LBB8_10
	MOVWU 68(RSP), R8
	CMPW $1, R8
	BNE _LBB8_10
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp84:
	MOVD RSP, R8
	MOVW $7, R10
	MOVWU 16(R8), R8
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB8_10
_Lfunc_end8:
DATA _L_str<>+0(SB)/1, $0x2e
DATA _L_str<>+1(SB)/1, $0x00
GLOBL _L_str<>(SB), RODATA, $2

DATA _L_str_1<>+0(SB)/1, $0x2e
DATA _L_str_1<>+1(SB)/1, $0x2e
DATA _L_str_1<>+2(SB)/1, $0x00
GLOBL _L_str_1<>(SB), RODATA, $3

GLOBL ·force_gc_in_compare(SB), NOPTR, $1

DATA c2go_global_gcmask·prefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·prefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·175d695a1edb77be(SB)
DATA gclocals·175d695a1edb77be+0(SB)/4, $2
DATA gclocals·175d695a1edb77be+4(SB)/4, $9
DATA gclocals·175d695a1edb77be+8(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+9(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+10(SB)/1, $0x20
DATA gclocals·175d695a1edb77be+11(SB)/1, $0x00
GLOBL gclocals·175d695a1edb77be(SB), DUPOK|RODATA, $12
