// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_dirent_prefixed_selftest(SB), $368-8
	PCDATA $1, $-1
	MOVD ZR, 56(RSP)
	MOVD ZR, 80(RSP)
	MOVD RSP, R8
	MOVD $_L_str<>(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_opendir(SB)
_Ltmp0:
	MOVD RSP, R8
	MOVD 16(R8), R8
	MOVD 56(RSP), R9
	MOVD R9, 80(RSP)
	CBZ R8, _LBB0_6
	MOVD R8, 72(RSP)
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp1:
	MOVD 72(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp2:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_14
	WORD $0x38413d09
	CBZW R9, _LBB0_7
	MOVD R9, R11
	MOVW $1, R9
	MOVD $0, R12
	MOVD $_L_str<>(SB), R14
_LBB0_4:
	WORD $0x386c69cd
	MOVD R12, R10
	CMPW R13, R11
	BNE _LBB0_8
	MOVWU R9, R10
	WORD $0x386a690d
	MOVD R13, R11
	ADDW $1, R9, R9
	MOVD R10, R12
	CBNZW R13, _LBB0_4
	JMP _LBB0_8
_LBB0_6:
	MOVW $1, R8
	JMP _LBB0_20
_LBB0_7:
	MOVD $0, R10
	MOVW $0, R11
	MOVD $_L_str<>(SB), R14
_LBB0_8:
	WORD $0x386a69c8
	CMPW R8, R11
	BNE _LBB0_14
	MOVD 72(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp3:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_19
	MOVD R8, R9
	WORD $0x38413d2a
	MOVD $_L_str_1<>(SB), R8
	CBZW R10, _LBB0_15
	MOVD R10, R12
	MOVW $1, R10
	MOVD $0, R13
_LBB0_12:
	WORD $0x386d690e
	MOVD R13, R11
	CMPW R14, R12
	BNE _LBB0_16
	MOVWU R10, R11
	WORD $0x386b692e
	MOVD R14, R12
	ADDW $1, R10, R10
	MOVD R11, R13
	CBNZW R14, _LBB0_12
	JMP _LBB0_16
_LBB0_14:
	MOVW $2, R8
	JMP _LBB0_20
_LBB0_15:
	MOVD $0, R11
	MOVW $0, R12
_LBB0_16:
	WORD $0x386b6908
	CMPW R8, R12
	BNE _LBB0_19
	MOVD 72(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_rewinddir(SB)
_Ltmp4:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp5:
	MOVD 72(RSP), R8
	MOVD RSP, R9
	ADD $80, RSP, R10
	MOVD R10, 24(R9)
	ADD $88, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir_r(SB)
_Ltmp6:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CBZW R8, _LBB0_21
	MOVW $4, R8
	JMP _LBB0_20
_LBB0_19:
	MOVW $3, R8
_LBB0_20:
	MOVW R8, 392(RSP)
	RET
_LBB0_21:
	MOVD 80(RSP), R8
	ADD $88, RSP, R9
	CMP R9, R8
	BNE _LBB0_35
	WORD $0x38413d09
	CBZW R9, _LBB0_26
	MOVD R9, R11
	MOVW $1, R9
	MOVD $0, R12
	MOVD $_L_str<>(SB), R14
_LBB0_24:
	WORD $0x386c69cd
	MOVD R12, R10
	CMPW R13, R11
	BNE _LBB0_27
	MOVWU R9, R10
	WORD $0x386a690d
	MOVD R13, R11
	ADDW $1, R9, R9
	MOVD R10, R12
	CBNZW R13, _LBB0_24
	JMP _LBB0_27
_LBB0_26:
	MOVD $0, R10
	MOVW $0, R11
	MOVD $_L_str<>(SB), R14
_LBB0_27:
	WORD $0x386a69c8
	CMPW R8, R11
	BNE _LBB0_35
	MOVD 72(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_dirfd(SB)
_Ltmp7:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVD RSP, R9
	MOVW R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·dup(SB)
_Ltmp8:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	TBNZ $31, R8, _LBB0_36
	MOVD R8, R9
	MOVD RSP, R8
	MOVW R9, 56(RSP)
	MOVW R9, 8(R8)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_fdopendir(SB)
_Ltmp9:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_37
	MOVD R8, 64(RSP)
	PCDATA $1, $4
	CALL ·ForceGC(SB)
_Ltmp10:
	MOVD 64(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp11:
	MOVD RSP, R8
	MOVD 16(R8), R8
	CBZ R8, _LBB0_42
	WORD $0x38413d09
	CBZW R9, _LBB0_38
	MOVD R9, R11
	MOVW $1, R9
	MOVD $0, R12
	MOVD $_L_str<>(SB), R14
_LBB0_33:
	WORD $0x386c69cd
	MOVD R12, R10
	CMPW R13, R11
	BNE _LBB0_39
	MOVWU R9, R10
	WORD $0x386a690d
	MOVD R13, R11
	ADDW $1, R9, R9
	MOVD R10, R12
	CBNZW R13, _LBB0_33
	JMP _LBB0_39
_LBB0_35:
	MOVW $5, R8
	JMP _LBB0_20
_LBB0_36:
	MOVW $6, R8
	JMP _LBB0_20
_LBB0_37:
	MOVD RSP, R8
	MOVWU 56(RSP), R9
	MOVW R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·close(SB)
_Ltmp12:
	MOVW $7, R8
	JMP _LBB0_20
_LBB0_38:
	MOVD $0, R10
	MOVW $0, R11
	MOVD $_L_str<>(SB), R14
_LBB0_39:
	WORD $0x386a69c8
	CMPW R8, R11
	BNE _LBB0_42
	MOVD 64(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp13:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_43
	MOVW $9, R8
	JMP _LBB0_20
_LBB0_42:
	MOVW $8, R8
	JMP _LBB0_20
_LBB0_43:
	MOVD 72(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp14:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $10, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R8
	JMP _LBB0_20
_Lfunc_end0:
	FUNCDATA $0, gclocals·4049a89979623773(SB)
DATA gclocals·4049a89979623773+0(SB)/4, $5
DATA gclocals·4049a89979623773+4(SB)/4, $1
DATA gclocals·4049a89979623773+8(SB)/1, $0x00
DATA gclocals·4049a89979623773+9(SB)/1, $0x00
DATA gclocals·4049a89979623773+10(SB)/1, $0x00
DATA gclocals·4049a89979623773+11(SB)/1, $0x00
DATA gclocals·4049a89979623773+12(SB)/1, $0x00
GLOBL gclocals·4049a89979623773(SB), DUPOK|RODATA, $13

	FUNCDATA $1, gclocals·ce4281ceff81567a(SB)
DATA gclocals·ce4281ceff81567a+0(SB)/4, $5
DATA gclocals·ce4281ceff81567a+4(SB)/4, $47
DATA gclocals·ce4281ceff81567a+8(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+9(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+10(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+11(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+12(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+13(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+14(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+15(SB)/1, $0x04
DATA gclocals·ce4281ceff81567a+16(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+17(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+18(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+19(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+20(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+21(SB)/1, $0x06
DATA gclocals·ce4281ceff81567a+22(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+23(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+24(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+25(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+26(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+27(SB)/1, $0x02
DATA gclocals·ce4281ceff81567a+28(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+29(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+30(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+31(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+32(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+33(SB)/1, $0x03
DATA gclocals·ce4281ceff81567a+34(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+35(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+36(SB)/1, $0x00
DATA gclocals·ce4281ceff81567a+37(SB)/1, $0x00
GLOBL gclocals·ce4281ceff81567a(SB), DUPOK|RODATA, $38

TEXT ·mlib_pthread_prefixed_selftest(SB), $144-8
	PCDATA $1, $-1
	MOVD ZR, 144(RSP)
	MOVD ZR, 104(RSP)
	WORD $0x6f00e400
	FMOVQ F0, 56(RSP)
	FMOVQ F0, 72(RSP)
	FMOVQ F0, 88(RSP)
	MOVD RSP, R8
	ADD $104, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp15:
	CBZW R0, _LBB1_2
	ADDW $10, R0, R8
	JMP _LBB1_4
_LBB1_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_mutex(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp16:
	CBZW R0, _LBB1_5
	ADDW $20, R0, R8
_LBB1_4:
	MOVW R8, 168(RSP)
	RET
_LBB1_5:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_pthread_mutex_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp17:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB1_8
	MOVD R8, 48(RSP)
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL ·exercise_prefixed_mutex(SB)
_Ltmp18:
	CBZW R0, _LBB1_9
	ADDW $30, R0, R8
	JMP _LBB1_4
_LBB1_8:
	MOVW $30, R8
	JMP _LBB1_4
_LBB1_9:
	MOVD ZR, 144(RSP)
	MOVW $-1, R8
	MOVW R8, 116(RSP)
	MOVD RSP, R8
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrInit(SB)
_Ltmp19:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_11
	MOVW $51, R8
	JMP _LBB1_4
_LBB1_11:
	MOVD RSP, R8
	MOVW $1, R9
	MOVW R9, 16(R8)
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrSetType(SB)
_Ltmp20:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB1_13
	MOVW $52, R8
	JMP _LBB1_4
_LBB1_13:
	MOVD RSP, R8
	ADD $116, RSP, R9
	ADD $120, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrGetType(SB)
_Ltmp21:
	MOVD RSP, R8
	MOVWU 24(R8), R9
	MOVW $53, R8
	CBNZW R9, _LBB1_4
	MOVWU 116(RSP), R9
	CMPW $1, R9
	BNE _LBB1_4
	MOVD RSP, R8
	ADD $120, RSP, R9
	ADD $144, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp22:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB1_17
	MOVW $54, R8
	JMP _LBB1_4
_LBB1_17:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp23:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_19
	MOVW $55, R8
	JMP _LBB1_4
_LBB1_19:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp24:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_21
	MOVW $56, R8
	JMP _LBB1_4
_LBB1_21:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp25:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp26:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_23
	MOVW $57, R8
	JMP _LBB1_4
_LBB1_23:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp27:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_25
	MOVW $58, R8
	JMP _LBB1_4
_LBB1_25:
	MOVD RSP, R8
	ADD $144, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp28:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_27
	MOVW $59, R8
	JMP _LBB1_4
_LBB1_27:
	MOVD RSP, R8
	ADD $120, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexAttrDestroy(SB)
_Ltmp29:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_29
	MOVW $60, R8
	JMP _LBB1_4
_LBB1_29:
	PCDATA $1, $0
	CALL ·exercise_prefixed_cond(SB)
_Ltmp30:
	CBZW R0, _LBB1_31
	ADDW $70, R0, R8
	JMP _LBB1_4
_LBB1_31:
	PCDATA $1, $0
	CALL ·exercise_prefixed_rwlock(SB)
_Ltmp31:
	CBZW R0, _LBB1_33
	ADDW $90, R0, R8
	JMP _LBB1_4
_LBB1_33:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexLock(SB)
_Ltmp32:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_35
	MOVW $111, R8
	JMP _LBB1_4
_LBB1_35:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexUnlock(SB)
_Ltmp33:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_37
	MOVW $112, R8
	JMP _LBB1_4
_LBB1_37:
	MOVD RSP, R8
	ADD $56, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadMutexDestroy(SB)
_Ltmp34:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $113, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R8
	JMP _LBB1_4
_Lfunc_end1:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·2603814e3e2186c6(SB)
DATA gclocals·2603814e3e2186c6+0(SB)/4, $4
DATA gclocals·2603814e3e2186c6+4(SB)/4, $19
DATA gclocals·2603814e3e2186c6+8(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+9(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+10(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+11(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+12(SB)/1, $0x20
DATA gclocals·2603814e3e2186c6+13(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+14(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+15(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+16(SB)/1, $0x04
DATA gclocals·2603814e3e2186c6+17(SB)/1, $0x40
DATA gclocals·2603814e3e2186c6+18(SB)/1, $0x00
DATA gclocals·2603814e3e2186c6+19(SB)/1, $0x04
GLOBL gclocals·2603814e3e2186c6(SB), DUPOK|RODATA, $20

TEXT ·exercise_prefixed_mutex(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	STP (ZR, ZR), 56(RSP)
	MOVD R9, 48(RSP)
	MOVD RSP, R10
	STP (R9, ZR), 8(R10)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp35:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB2_2
	MOVW $1, R0
	JMP _LBB2_11
_LBB2_2:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp36:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_4
	MOVW $2, R0
	JMP _LBB2_11
_LBB2_4:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp37:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp38:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB2_8
	MOVD 48(RSP), R8
	MOVD RSP, R9
	ADD $56, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp39:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $60, R8
	BNE _LBB2_9
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp40:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_10
	MOVW $5, R0
	JMP _LBB2_11
_LBB2_8:
	MOVW $3, R0
	JMP _LBB2_11
_LBB2_9:
	MOVW $4, R0
	JMP _LBB2_11
_LBB2_10:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp41:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $6, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
_LBB2_11:
	RET
_Lfunc_end2:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·18a3a95a1ff0a71e(SB)
DATA gclocals·18a3a95a1ff0a71e+0(SB)/4, $2
DATA gclocals·18a3a95a1ff0a71e+4(SB)/4, $9
DATA gclocals·18a3a95a1ff0a71e+8(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+9(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+10(SB)/1, $0x40
DATA gclocals·18a3a95a1ff0a71e+11(SB)/1, $0x00
GLOBL gclocals·18a3a95a1ff0a71e(SB), DUPOK|RODATA, $12

TEXT ·exercise_prefixed_cond(SB), $96-0
	PCDATA $1, $-1
	STP (ZR, ZR), 88(RSP)
	STP (ZR, ZR), 48(RSP)
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrInit(SB)
_Ltmp42:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_2
	MOVW $1, R0
	JMP _LBB3_12
_LBB3_2:
	MOVD RSP, R8
	ADD $96, RSP, R10
	STP (R10, ZR), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp43:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB3_4
	MOVW $2, R0
	JMP _LBB3_12
_LBB3_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	ADD $88, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp44:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB3_6
	MOVW $3, R0
	JMP _LBB3_12
_LBB3_6:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp45:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_8
	MOVW $4, R0
	JMP _LBB3_12
_LBB3_8:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp46:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 24(R8)
	ADD $96, RSP, R9
	ADD $88, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp47:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CMPW $60, R8
	BNE _LBB3_11
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp48:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp49:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_13
	MOVW $6, R0
	JMP _LBB3_12
_LBB3_11:
	MOVW $5, R0
_LBB3_12:
	RET
_LBB3_13:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondSignal(SB)
_Ltmp50:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_15
	MOVW $7, R0
	JMP _LBB3_12
_LBB3_15:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondBroadcast(SB)
_Ltmp51:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_17
	MOVW $8, R0
	JMP _LBB3_12
_LBB3_17:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp52:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_19
	MOVW $9, R0
	JMP _LBB3_12
_LBB3_19:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp53:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB3_21
	MOVW $10, R0
	JMP _LBB3_12
_LBB3_21:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondAttrDestroy(SB)
_Ltmp54:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $11, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB3_12
_Lfunc_end3:
	FUNCDATA $0, gclocals·c7c2bf3b330983e6(SB)
DATA gclocals·c7c2bf3b330983e6+0(SB)/4, $3
DATA gclocals·c7c2bf3b330983e6+4(SB)/4, $0
GLOBL gclocals·c7c2bf3b330983e6(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4fea40b68a78c7cb(SB)
DATA gclocals·4fea40b68a78c7cb+0(SB)/4, $3
DATA gclocals·4fea40b68a78c7cb+4(SB)/4, $13
DATA gclocals·4fea40b68a78c7cb+8(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+9(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+10(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+11(SB)/1, $0x18
DATA gclocals·4fea40b68a78c7cb+12(SB)/1, $0x00
DATA gclocals·4fea40b68a78c7cb+13(SB)/1, $0x10
GLOBL gclocals·4fea40b68a78c7cb(SB), DUPOK|RODATA, $14

TEXT ·exercise_prefixed_rwlock(SB), $64-0
	PCDATA $1, $-1
	MOVD ZR, 64(RSP)
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrInit(SB)
_Ltmp55:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_2
	MOVW $1, R0
	JMP _LBB4_10
_LBB4_2:
	MOVD RSP, R8
	ADD $40, RSP, R9
	ADD $64, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp56:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB4_4
	MOVW $2, R0
	JMP _LBB4_10
_LBB4_4:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp57:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_6
	MOVW $3, R0
	JMP _LBB4_10
_LBB4_6:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp58:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp59:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB4_9
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp60:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_11
	MOVW $5, R0
	JMP _LBB4_10
_LBB4_9:
	MOVW $4, R0
_LBB4_10:
	RET
_LBB4_11:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp61:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_13
	MOVW $6, R0
	JMP _LBB4_10
_LBB4_13:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp62:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB4_16
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp63:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_17
	MOVW $8, R0
	JMP _LBB4_10
_LBB4_16:
	MOVW $7, R0
	JMP _LBB4_10
_LBB4_17:
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp64:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB4_19
	MOVW $9, R0
	JMP _LBB4_10
_LBB4_19:
	MOVD RSP, R8
	ADD $40, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockAttrDestroy(SB)
_Ltmp65:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $10, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB4_10
_Lfunc_end4:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·mlib_sem_prefixed_selftest(SB), $48-8
	PCDATA $1, $-1
	MOVD ZR, 48(RSP)
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_prefixed_sem(SB)
_Ltmp66:
	CBZW R0, _LBB5_2
	ADDW $10, R0, R8
	JMP _LBB5_7
_LBB5_2:
	MOVD RSP, R8
	MOVD $·prefixed_global_sem(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL ·exercise_prefixed_sem(SB)
_Ltmp67:
	CBZW R0, _LBB5_4
	ADDW $20, R0, R8
	JMP _LBB5_7
_LBB5_4:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_mlib_sem_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp68:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB5_6
	MOVD R8, 40(RSP)
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $2
	CALL ·exercise_prefixed_sem(SB)
_Ltmp69:
	ADDW $30, R0, R9
	CMPW $0, R0
	CSELW EQ, ZR, R9, R8
	JMP _LBB5_7
_LBB5_6:
	MOVW $30, R8
_LBB5_7:
	MOVW R8, 72(RSP)
	RET
_Lfunc_end5:
	FUNCDATA $0, gclocals·be91aa5e7697217d(SB)
DATA gclocals·be91aa5e7697217d+0(SB)/4, $3
DATA gclocals·be91aa5e7697217d+4(SB)/4, $1
DATA gclocals·be91aa5e7697217d+8(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+9(SB)/1, $0x00
DATA gclocals·be91aa5e7697217d+10(SB)/1, $0x00
GLOBL gclocals·be91aa5e7697217d(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·1dc925208ae72fbb(SB)
DATA gclocals·1dc925208ae72fbb+0(SB)/4, $3
DATA gclocals·1dc925208ae72fbb+4(SB)/4, $7
DATA gclocals·1dc925208ae72fbb+8(SB)/1, $0x00
DATA gclocals·1dc925208ae72fbb+9(SB)/1, $0x40
DATA gclocals·1dc925208ae72fbb+10(SB)/1, $0x20
GLOBL gclocals·1dc925208ae72fbb(SB), DUPOK|RODATA, $11

TEXT ·exercise_prefixed_sem(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	MOVW $-1, R10
	MOVW R10, 68(RSP)
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 40(RSP)
	MOVD RSP, R8
	MOVD $4294967296, R10
	STP (R9, R10), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp70:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB6_2
	MOVW $1, R0
	JMP _LBB6_10
_LBB6_2:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp71:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp72:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_4
	MOVW $2, R0
	JMP _LBB6_10
_LBB6_4:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $48, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp73:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $60, R8
	BNE _LBB6_8
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp74:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $35, R8
	BNE _LBB6_9
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp75:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB6_11
	MOVW $5, R0
	JMP _LBB6_10
_LBB6_8:
	MOVW $3, R0
	JMP _LBB6_10
_LBB6_9:
	MOVW $4, R0
_LBB6_10:
	RET
_LBB6_11:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $68, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp76:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	MOVW $6, R0
	CBNZW R8, _LBB6_10
	MOVWU 68(RSP), R8
	CMPW $1, R8
	BNE _LBB6_10
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp77:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $7, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB6_10
_Lfunc_end6:
DATA _L_str<>+0(SB)/1, $0x2e
DATA _L_str<>+1(SB)/1, $0x00
GLOBL _L_str<>(SB), RODATA, $2

DATA _L_str_1<>+0(SB)/1, $0x2e
DATA _L_str_1<>+1(SB)/1, $0x2e
DATA _L_str_1<>+2(SB)/1, $0x00
GLOBL _L_str_1<>(SB), RODATA, $3

DATA c2go_global_gcmask·prefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·prefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·prefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·175d695a1edb77be(SB)
DATA gclocals·175d695a1edb77be+0(SB)/4, $2
DATA gclocals·175d695a1edb77be+4(SB)/4, $9
DATA gclocals·175d695a1edb77be+8(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+9(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+10(SB)/1, $0x20
DATA gclocals·175d695a1edb77be+11(SB)/1, $0x00
GLOBL gclocals·175d695a1edb77be(SB), DUPOK|RODATA, $12
