// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_dirent_unprefixed_selftest(SB), $392-8
	PCDATA $1, $-1
	LONG $0xe845c748
	LONG $0x00000000
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ _L_str<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_opendir(SB)
_Ltmp0:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	LONG $0xe845c748
	LONG $0x00000000
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_8
	MOVQ AX, -16(BP)
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp1:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp2:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVL $2, CX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_9
	LONG $0x1350b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_10
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_4:
	LONG $0x071c3a42
	MOVQ DI, DX
	JNE _LBB0_7
	MOVL SI, DX
	LONG $0x105cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_4
	XORL AX, AX
	MOVL AX, BX
_LBB0_7:
	LONG $0x021c3a42
	JNE _LBB0_9
	JMP _LBB0_11
_LBB0_8:
	MOVL $1, CX
_LBB0_9:
	MOVL CX, 16(BP)
	RET
_LBB0_10:
	XORL AX, AX
	MOVL AX, DX
	MOVL AX, BX
	LEAQ _L_str<>(SB), R8
	LONG $0x021c3a42
	JNE _LBB0_9
_LBB0_11:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp3:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	MOVL $3, AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB0_17
	LONG $0x1359b60f
	BYTE $0x84
	BYTE $0xdb
	JEQ _LBB0_18
	MOVL $1, DI
	XORL DX, DX
	MOVL DX, R8
	LEAQ _L_str_1<>(SB), DX
_LBB0_14:
	LONG $0x101c3a41
	MOVQ R8, SI
	JNE _LBB0_20
	MOVL DI, SI
	LONG $0x315cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc7
	MOVQ SI, R8
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_14
	XORL CX, CX
	JMP _LBB0_19
_LBB0_17:
	MOVL AX, CX
	JMP _LBB0_9
_LBB0_18:
	XORL CX, CX
	MOVL CX, SI
_LBB0_19:
	MOVL CX, BX
_LBB0_20:
	LEAQ _L_str_1<>(SB), DX
	MOVL AX, CX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x16
	JNE _LBB0_9
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_rewinddir(SB)
_Ltmp4:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp5:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -24(BP), DX
	MOVQ DX, 16(CX)
	LEAQ -336(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir_r(SB)
_Ltmp6:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x00187883
	JNE _LBB0_9
	MOVQ -24(BP), AX
	MOVL $5, CX
	LEAQ -336(BP), DX
	BYTE $0x48
	BYTE $0x39
	BYTE $0xd0
	JNE _LBB0_9
	LONG $0x1350b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_28
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_25:
	LONG $0x071c3a42
	MOVQ DI, DX
	JNE _LBB0_29
	MOVL SI, DX
	LONG $0x105cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_25
	XORL AX, AX
	MOVL AX, BX
	JMP _LBB0_29
_LBB0_28:
	XORL AX, AX
	MOVL AX, DX
	MOVL AX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_29:
	LONG $0x021c3a42
	JNE _LBB0_9
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_dirfd(SB)
_Ltmp7:
	MOVQ SP, AX
	MOVL 8(AX), AX
	MOVQ SP, CX
	MOVL AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·dup(SB)
_Ltmp8:
	MOVQ SP, AX
	MOVL 8(AX), CX
	BYTE $0x85
	BYTE $0xc9
	JMI _LBB0_38
	MOVQ SP, AX
	MOVL CX, -32(BP)
	MOVL CX, 0(AX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_fdopendir(SB)
_Ltmp9:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_39
	MOVQ AX, -40(BP)
	PCDATA $1, $4
	CALL ·ForceGC(SB)
_Ltmp10:
	MOVQ -40(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp11:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVL $8, CX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_9
	LONG $0x1350b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_40
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_35:
	LONG $0x071c3a42
	MOVQ DI, DX
	JNE _LBB0_41
	MOVL SI, DX
	LONG $0x105cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_35
	XORL AX, AX
	MOVL AX, BX
	JMP _LBB0_41
_LBB0_38:
	MOVL $6, CX
	JMP _LBB0_9
_LBB0_39:
	MOVQ SP, AX
	MOVL -32(BP), CX
	MOVL CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·close(SB)
_Ltmp12:
	MOVL $7, CX
	JMP _LBB0_9
_LBB0_40:
	XORL AX, AX
	MOVL AX, DX
	MOVL AX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_41:
	LONG $0x021c3a42
	JNE _LBB0_9
	MOVQ -40(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp13:
	MOVQ SP, AX
	MOVL $9, CX
	LONG $0x00087883
	JNE _LBB0_9
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp14:
	MOVQ SP, AX
	MOVL $10, CX
	LONG $0x00087883
	JNE _LBB0_9
	LONG $0xf845c748
	LONG $0x00000000
	MOVB $1, ·force_gc_in_compare(SB)
	MOVQ SP, AX
	LEAQ ·compare_reverse_alpha(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 8(AX)
	LEAQ _L_str<>(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	PCDATA $1, $5
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_scandir(SB)
_Ltmp15:
	MOVQ SP, AX
	MOVL 32(AX), AX
	MOVL $11, CX
	MOVL AX, -32(BP)
	BYTE $0x83
	BYTE $0xf8
	BYTE $0x02
	JLT _LBB0_9
	PCDATA $1, $5
	CALL ·ForceGC(SB)
_Ltmp16:
	LEAQ _L_str_1<>(SB), R11
	MOVL -32(BP), AX
	MOVQ AX, -56(BP)
	XORL R12, R12
	MOVL R12, AX
	MOVL R12, CX
	MOVL R12, SI
	JMP _LBB0_47
_LBB0_46:
	MOVQ R13, AX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc0
	MOVL DX, CX
	MOVL R8, SI
	LONG $0xc8453b48
	JEQ _LBB0_61
_LBB0_47:
	MOVQ AX, R13
	MOVQ -8(BP), AX
	MOVQ 0(AX)(R13*8), DX
	LONG $0x135ab60f
	BYTE $0x84
	BYTE $0xdb
	JEQ _LBB0_56
	MOVL $1, DI
	MOVL R12, R10
	MOVL BX, R9
_LBB0_49:
	LEAQ _L_str<>(SB), R8
	LONG $0x020c3a47
	JNE _LBB0_52
	MOVL DI, R8
	MOVL R8, R10
	LONG $0x4cb60f46
	BYTE $0x12
	BYTE $0x13
	MOVL DI, R8
	BYTE $0x41
	BYTE $0xff
	BYTE $0xc0
	MOVL R8, DI
	BYTE $0x45
	BYTE $0x84
	BYTE $0xc9
	JNE _LBB0_49
	LONG $0x02f88341
	MOVL $1, DI
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xf7
_LBB0_52:
	MOVL $1, R8
	MOVL R12, R9
_LBB0_53:
	LONG $0x191c3a43
	JNE _LBB0_57
	MOVL R8, DI
	LONG $0x3a5cb60f
	BYTE $0x13
	BYTE $0x41
	BYTE $0xff
	BYTE $0xc0
	MOVQ DI, R9
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_53
	XORL DX, DX
	MOVL DX, BX
	JMP _LBB0_58
_LBB0_56:
	XORL DX, DX
	MOVL DX, DI
	MOVL DX, BX
	JMP _LBB0_58
_LBB0_57:
	MOVQ R9, DI
_LBB0_58:
	MOVL SI, R8
	LONG $0x1f1c3a42
	MOVL CX, DX
	MOVL $1, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xd1
	BYTE $0x4d
	BYTE $0x85
	BYTE $0xed
	JEQ _LBB0_46
	LEAQ 0(AX)(R13*8), CX
	MOVQ AX, -16(BP)
	MOVQ SP, AX
	MOVQ CX, 8(AX)
	ADDQ $-8, CX
	MOVQ CX, 0(AX)
	MOVQ R13, -32(BP)
	MOVL DX, -48(BP)
	MOVL R8, -44(BP)
	PCDATA $1, $3
	CALL ·compare_reverse_alpha(SB)
_Ltmp17:
	MOVL -44(BP), R8
	MOVL -48(BP), DX
	MOVQ -32(BP), R13
	XORL R12, R12
	LEAQ _L_str_1<>(SB), R11
	BYTE $0x85
	BYTE $0xc0
	JLE _LBB0_46
	MOVL $12, CX
	JMP _LBB0_9
_LBB0_61:
	MOVL $13, CX
	BYTE $0x45
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_9
	BYTE $0x85
	BYTE $0xd2
	JEQ _LBB0_9
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ ·compare_reverse_alpha(SB), CX
	MOVQ CX, 24(AX)
	LEAQ ·select_dots(SB), CX
	MOVQ CX, 16(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 8(AX)
	LEAQ _L_str<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $5
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_scandir(SB)
_Ltmp18:
	MOVQ SP, AX
	MOVL $14, CX
	LONG $0x02207883
	JNE _LBB0_9
	PCDATA $1, $5
	CALL ·ForceGC(SB)
_Ltmp19:
	MOVQ -8(BP), AX
	MOVQ 0(AX), CX
	LONG $0x1351b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_69
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
_LBB0_66:
	LEAQ _L_str_1<>(SB), DX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x17
	MOVQ DI, DX
	JNE _LBB0_71
	MOVL SI, DX
	LONG $0x115cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_66
	XORL CX, CX
	JMP _LBB0_70
_LBB0_69:
	XORL CX, CX
	MOVL CX, DX
_LBB0_70:
	MOVL CX, BX
_LBB0_71:
	MOVL $15, CX
	LEAQ _L_str_1<>(SB), SI
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x32
	JNE _LBB0_9
	MOVQ 8(AX), CX
	LONG $0x1351b60f
	XORL AX, AX
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_77
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
_LBB0_74:
	LEAQ _L_str<>(SB), DX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x17
	MOVQ DI, DX
	JNE _LBB0_78
	MOVL SI, DX
	LONG $0x115cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_74
	XORL CX, CX
	MOVL CX, BX
	JMP _LBB0_78
_LBB0_77:
	MOVL AX, BX
	MOVL AX, DX
_LBB0_78:
	LEAQ _L_str<>(SB), CX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x0a
	MOVL $15, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	JMP _LBB0_9
_Lfunc_end0:
	FUNCDATA $0, gclocals·726b3031c54e09e2(SB)
DATA gclocals·726b3031c54e09e2+0(SB)/4, $6
DATA gclocals·726b3031c54e09e2+4(SB)/4, $1
DATA gclocals·726b3031c54e09e2+8(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+9(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+10(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+11(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+12(SB)/1, $0x00
DATA gclocals·726b3031c54e09e2+13(SB)/1, $0x00
GLOBL gclocals·726b3031c54e09e2(SB), DUPOK|RODATA, $14

	FUNCDATA $1, gclocals·00c097f2139d9d19(SB)
DATA gclocals·00c097f2139d9d19+0(SB)/4, $6
DATA gclocals·00c097f2139d9d19+4(SB)/4, $49
DATA gclocals·00c097f2139d9d19+8(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+9(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+10(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+11(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+12(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+13(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+14(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+15(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+16(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+17(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+18(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+19(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+20(SB)/1, $0x40
DATA gclocals·00c097f2139d9d19+21(SB)/1, $0x01
DATA gclocals·00c097f2139d9d19+22(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+23(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+24(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+25(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+26(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+27(SB)/1, $0xc0
DATA gclocals·00c097f2139d9d19+28(SB)/1, $0x01
DATA gclocals·00c097f2139d9d19+29(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+30(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+31(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+32(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+33(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+34(SB)/1, $0x80
DATA gclocals·00c097f2139d9d19+35(SB)/1, $0x01
DATA gclocals·00c097f2139d9d19+36(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+37(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+38(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+39(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+40(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+41(SB)/1, $0x90
DATA gclocals·00c097f2139d9d19+42(SB)/1, $0x01
DATA gclocals·00c097f2139d9d19+43(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+44(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+45(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+46(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+47(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+48(SB)/1, $0x00
DATA gclocals·00c097f2139d9d19+49(SB)/1, $0x01
GLOBL gclocals·00c097f2139d9d19(SB), DUPOK|RODATA, $50

TEXT ·compare_reverse_alpha(SB), $56-16
	PCDATA $1, $-1
	CMPB ·force_gc_in_compare(SB), $1
	MOVQ 16(BP), AX
	MOVQ 24(BP), CX
	JNE _LBB1_2
	MOVB $0, ·force_gc_in_compare(SB)
	MOVQ AX, -16(BP)
	MOVQ 24(BP), AX
	MOVQ AX, -8(BP)
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp20:
	MOVQ -8(BP), CX
	MOVQ -16(BP), AX
_LBB1_2:
	MOVQ CX, -8(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, DX
	MOVQ AX, 8(DX)
	MOVQ CX, 0(DX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·alphasort(SB)
_Ltmp21:
	MOVQ SP, AX
	MOVL 16(AX), AX
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·e1f3e66d4bb68923(SB)
DATA gclocals·e1f3e66d4bb68923+0(SB)/4, $2
DATA gclocals·e1f3e66d4bb68923+4(SB)/4, $2
DATA gclocals·e1f3e66d4bb68923+8(SB)/1, $0x03
DATA gclocals·e1f3e66d4bb68923+9(SB)/1, $0x03
GLOBL gclocals·e1f3e66d4bb68923(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·9300ac6ea5fafef0(SB)
DATA gclocals·9300ac6ea5fafef0+0(SB)/4, $2
DATA gclocals·9300ac6ea5fafef0+4(SB)/4, $7
DATA gclocals·9300ac6ea5fafef0+8(SB)/1, $0x00
DATA gclocals·9300ac6ea5fafef0+9(SB)/1, $0x60
GLOBL gclocals·9300ac6ea5fafef0(SB), DUPOK|RODATA, $10

TEXT ·select_dots(SB), $8-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0x1340b60f
	BYTE $0x84
	BYTE $0xc0
	JEQ _LBB2_1
	MOVL $1, SI
	XORL CX, CX
	MOVL CX, DI
	LEAQ _L_str<>(SB), CX
	MOVL AX, BX
_LBB2_4:
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x0f
	JNE _LBB2_6
	MOVL SI, DX
	MOVL DX, DI
	MOVQ 16(BP), DX
	LONG $0x3a5cb60f
	BYTE $0x13
	MOVL SI, DX
	BYTE $0xff
	BYTE $0xc2
	MOVL DX, SI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB2_4
	MOVL $1, CX
	BYTE $0x83
	BYTE $0xfa
	BYTE $0x02
	JEQ _LBB2_11
_LBB2_6:
	MOVL $1, DX
	XORL CX, CX
	MOVL CX, SI
	LEAQ _L_str_1<>(SB), CX
	MOVL AX, BX
_LBB2_7:
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x0e
	MOVQ SI, AX
	JNE _LBB2_10
	MOVL DX, AX
	MOVQ 16(BP), SI
	LONG $0x065cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc2
	MOVQ AX, SI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB2_7
	XORL CX, CX
	MOVL CX, BX
	JMP _LBB2_10
_LBB2_1:
	XORL AX, AX
	MOVL AX, CX
	MOVL AX, BX
	MOVQ CX, AX
_LBB2_10:
	LEAQ _L_str_1<>(SB), CX
	XORL DX, DX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x08
	BYTE $0x0f
	BYTE $0x94
	BYTE $0xc0
	MOVB AL, DL
	MOVL DX, CX
_LBB2_11:
	MOVL CX, AX
	RET
_Lfunc_end2:
	FUNCDATA $0, gclocals·5f490f070d449c5c(SB)
DATA gclocals·5f490f070d449c5c+0(SB)/4, $1
DATA gclocals·5f490f070d449c5c+4(SB)/4, $1
DATA gclocals·5f490f070d449c5c+8(SB)/1, $0x01
GLOBL gclocals·5f490f070d449c5c(SB), DUPOK|RODATA, $9

	FUNCDATA $1, gclocals·5f4910070d449e0f(SB)
DATA gclocals·5f4910070d449e0f+0(SB)/4, $1
DATA gclocals·5f4910070d449e0f+4(SB)/4, $1
DATA gclocals·5f4910070d449e0f+8(SB)/1, $0x00
GLOBL gclocals·5f4910070d449e0f(SB), DUPOK|RODATA, $9

TEXT ·mlib_ftw_unprefixed_selftest(SB), $200-8
	PCDATA $1, $-1
	MOVQ SP, AX
	LEAQ _L_str_2<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·Getenv(SB)
_Ltmp22:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB3_2
	BYTE $0x80
	BYTE $0x39
	BYTE $0x00
	MOVQ CX, AX
	JNE _LBB3_3
_LBB3_2:
	LEAQ _L_str_1_3<>(SB), CX
	XORL AX, AX
_LBB3_3:
	MOVQ AX, -16(BP)
	MOVQ CX, -8(BP)
	MOVQ SP, AX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp23:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -24(BP)
	MOVQ SP, AX
	LEAQ _L_str_2_4<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp24:
	MOVQ -24(BP), DX
	MOVQ SP, AX
	MOVQ 8(AX), SI
	MOVL $512, AX
	SUBQ DX, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc6
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB3_5
	LEAQ 0(DX)(SI*1), AX
	ADDQ $2, AX
	LONG $0x02013d48
	BYTE $0x00
	BYTE $0x00
	JCS _LBB3_8
_LBB3_5:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp25:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
_LBB3_6:
	MOVL $1, CX
_LBB3_7:
	MOVL CX, 16(BP)
	RET
_LBB3_8:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ DX, 16(CX)
	MOVQ AX, 8(CX)
	LEAQ ·c2go_mlib_ftw_root(SB), AX
	MOVQ AX, 0(CX)
	MOVQ SI, -32(BP)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp26:
	LEAQ ·c2go_mlib_ftw_root(SB), AX
	MOVQ -24(BP), CX
	LONG $0x2f0104c6
	ADDQ CX, AX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc0
	MOVQ -32(BP), CX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc1
	MOVQ SP, DX
	MOVQ CX, 16(DX)
	LEAQ _L_str_2_4<>(SB), CX
	MOVQ CX, 8(DX)
	MOVQ AX, 0(DX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp27:
	MOVQ SP, AX
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·mkdtemp(SB)
_Ltmp28:
	MOVQ SP, AX
	LONG $0x08788348
	BYTE $0x00
	JEQ _LBB3_6
	MOVQ SP, AX
	LEAQ _L_str_3<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·c2go_mlib_ftw_mkdir(SB)
_Ltmp29:
	MOVL $2, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB3_7
	MOVQ SP, AX
	LEAQ _L_str_4<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·c2go_mlib_ftw_mkdir(SB)
_Ltmp30:
	MOVL $3, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB3_7
	MOVQ SP, AX
	LEAQ _L_str_5<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·c2go_mlib_ftw_mkfile(SB)
_Ltmp31:
	MOVL $4, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB3_7
	MOVQ SP, AX
	LEAQ _L_str_6<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·c2go_mlib_ftw_mkfile(SB)
_Ltmp32:
	MOVL $5, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB3_7
	MOVQ SP, AX
	LEAQ _L_str_7<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·c2go_mlib_ftw_mkfile(SB)
_Ltmp33:
	MOVL $6, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB3_7
	MOVL $0, ·c2go_mlib_ftw_dirs(SB)
	MOVL $0, ·c2go_mlib_ftw_files(SB)
	MOVL $0, ·c2go_mlib_ftw_depth_dirs(SB)
	MOVL $0, ·c2go_mlib_ftw_other(SB)
	MOVL $0, ·c2go_mlib_ftw_total(SB)
	MOVL $0, ·c2go_mlib_ftw_root_pos(SB)
	MOVL $0, ·c2go_mlib_ftw_max_level(SB)
	MOVB $1, ·c2go_mlib_ftw_force_gc(SB)
	MOVQ SP, AX
	LEAQ ·c2go_mlib_nftw_count(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000008
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp34:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x00187883
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_total(SB), $6
	MOVL $8, CX
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_root_pos(SB), $1
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_dirs(SB), $3
	MOVL $9, CX
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_files(SB), $3
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_depth_dirs(SB), $0
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_other(SB), $0
	JNE _LBB3_7
	MOVL $10, CX
	CMPL ·c2go_mlib_ftw_max_level(SB), $3
	JNE _LBB3_7
	MOVL $0, ·c2go_mlib_ftw_dirs(SB)
	MOVL $0, ·c2go_mlib_ftw_files(SB)
	MOVL $0, ·c2go_mlib_ftw_depth_dirs(SB)
	MOVL $0, ·c2go_mlib_ftw_other(SB)
	MOVL $0, ·c2go_mlib_ftw_total(SB)
	MOVL $0, ·c2go_mlib_ftw_root_pos(SB)
	MOVL $0, ·c2go_mlib_ftw_max_level(SB)
	MOVB $1, ·c2go_mlib_ftw_force_gc(SB)
	MOVQ SP, AX
	MOVQ $34359738376, CX
	MOVQ CX, 16(AX)
	LEAQ ·c2go_mlib_nftw_count(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp35:
	MOVQ SP, AX
	MOVL $11, CX
	LONG $0x00187883
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_total(SB), $6
	MOVL $12, CX
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_root_pos(SB), $6
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_depth_dirs(SB), $3
	MOVL $13, CX
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_files(SB), $3
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_dirs(SB), $0
	JNE _LBB3_7
	CMPL ·c2go_mlib_ftw_other(SB), $0
	JNE _LBB3_7
	MOVL $0, ·c2go_mlib_ftw_total(SB)
	MOVB $1, ·c2go_mlib_ftw_force_gc(SB)
	MOVQ SP, AX
	LEAQ ·c2go_mlib_ftw_count(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x081040c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_ftw(SB)
_Ltmp36:
	MOVQ SP, AX
	MOVL $14, CX
	LONG $0x00187883
	JNE _LBB3_7
	MOVL $15, CX
	CMPL ·c2go_mlib_ftw_total(SB), $6
	JNE _LBB3_7
	MOVL $0, ·c2go_mlib_ftw_total(SB)
	MOVQ SP, AX
	LEAQ ·c2go_mlib_nftw_stop(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000008
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp37:
	MOVQ SP, AX
	MOVL $16, CX
	LONG $0x07187883
	JNE _LBB3_7
	MOVL $17, CX
	CMPL ·c2go_mlib_ftw_total(SB), $2
	JNE _LBB3_7
	MOVQ SP, AX
	LEAQ ·c2go_mlib_nftw_count(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp38:
	MOVQ SP, AX
	MOVL $18, CX
	LONG $0x00187883
	JNE _LBB3_7
	MOVQ SP, AX
	MOVQ $38654705672, CX
	MOVQ CX, 16(AX)
	LEAQ ·c2go_mlib_nftw_remove(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp39:
	MOVQ SP, AX
	MOVL $19, CX
	LONG $0x00187883
	JNE _LBB3_7
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp40:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x000000c7
	BYTE $0x00
	BYTE $0x00
	MOVQ SP, AX
	LEAQ -152(BP), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·stat(SB)
_Ltmp41:
	MOVQ SP, AX
	LONG $0xff107883
	JEQ _LBB3_38
	MOVL $20, CX
	JMP _LBB3_7
_LBB3_38:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp42:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	BYTE $0x83
	BYTE $0x38
	BYTE $0x02
	MOVL $20, CX
	JNE _LBB3_7
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp43:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x000000c7
	BYTE $0x00
	BYTE $0x00
	MOVQ SP, AX
	LEAQ ·c2go_mlib_nftw_count(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000008
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_nftw(SB)
_Ltmp44:
	MOVQ SP, AX
	MOVL $21, CX
	LONG $0xff187883
	JNE _LBB3_7
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp45:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	XORL CX, CX
	BYTE $0x83
	BYTE $0x38
	BYTE $0x02
	MOVL $21, AX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc1
	MOVL AX, CX
	JMP _LBB3_7
_Lfunc_end3:
	FUNCDATA $0, gclocals·be86e5a039a56de6(SB)
DATA gclocals·be86e5a039a56de6+0(SB)/4, $2
DATA gclocals·be86e5a039a56de6+4(SB)/4, $1
DATA gclocals·be86e5a039a56de6+8(SB)/1, $0x00
DATA gclocals·be86e5a039a56de6+9(SB)/1, $0x00
GLOBL gclocals·be86e5a039a56de6(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·8509aba6547803e1(SB)
DATA gclocals·8509aba6547803e1+0(SB)/4, $2
DATA gclocals·8509aba6547803e1+4(SB)/4, $25
DATA gclocals·8509aba6547803e1+8(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+9(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+10(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+11(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+12(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+13(SB)/1, $0x00
DATA gclocals·8509aba6547803e1+14(SB)/1, $0x80
DATA gclocals·8509aba6547803e1+15(SB)/1, $0x01
GLOBL gclocals·8509aba6547803e1(SB), DUPOK|RODATA, $16

TEXT ·c2go_mlib_ftw_mkdir(SB), $664-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	MOVQ AX, -8(BP)
	MOVQ SP, AX
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp46:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -16(BP)
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp47:
	MOVQ -16(BP), DX
	MOVQ SP, AX
	MOVQ 8(AX), SI
	MOVL $600, AX
	SUBQ DX, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc6
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB4_2
	LEAQ 0(DX)(SI*1), AX
	ADDQ $2, AX
	LONG $0x02593d48
	BYTE $0x00
	BYTE $0x00
	JCS _LBB4_3
_LBB4_2:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp48:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
	MOVL $-1, AX
	JMP _LBB4_4
_LBB4_3:
	MOVQ SP, AX
	MOVQ DX, 16(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 8(AX)
	LEAQ -624(BP), CX
	MOVQ CX, 0(AX)
	MOVQ SI, -24(BP)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp49:
	MOVQ -8(BP), AX
	MOVQ -16(BP), CX
	LONG $0x900d84c6
	LONG $0x2ffffffd
	ADDQ BP, CX
	ADDQ $-623, CX
	MOVQ -24(BP), DX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc2
	MOVQ SP, SI
	MOVQ DX, 16(SI)
	MOVQ AX, 8(SI)
	MOVQ CX, 0(SI)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp50:
	MOVQ SP, AX
	LEAQ -624(BP), CX
	MOVQ CX, 0(AX)
	LONG $0xed0840c7
	BYTE $0x01
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·mkdir(SB)
_Ltmp51:
	MOVQ SP, AX
	MOVL 16(AX), AX
_LBB4_4:
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·ba9839c7073dc298(SB)
DATA gclocals·ba9839c7073dc298+0(SB)/4, $2
DATA gclocals·ba9839c7073dc298+4(SB)/4, $83
DATA gclocals·ba9839c7073dc298+8(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+9(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+10(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+11(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+12(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+13(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+14(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+15(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+16(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+17(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+18(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+19(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+20(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+21(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+22(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+23(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+24(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+25(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+26(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+27(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+28(SB)/1, $0x00
DATA gclocals·ba9839c7073dc298+29(SB)/1, $0x04
GLOBL gclocals·ba9839c7073dc298(SB), DUPOK|RODATA, $30

TEXT ·c2go_mlib_ftw_mkfile(SB), $696-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -40(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, AX
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp52:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -24(BP)
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp53:
	MOVQ -24(BP), DX
	MOVQ SP, AX
	MOVQ 8(AX), SI
	MOVL $600, AX
	SUBQ DX, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc6
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB5_2
	LEAQ 0(DX)(SI*1), AX
	ADDQ $2, AX
	LONG $0x02593d48
	BYTE $0x00
	BYTE $0x00
	JCS _LBB5_5
_LBB5_2:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp54:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
_LBB5_3:
	MOVL $-1, AX
_LBB5_4:
	RET
_LBB5_5:
	MOVQ SP, AX
	MOVQ DX, 16(AX)
	LEAQ ·c2go_mlib_ftw_root(SB), CX
	MOVQ CX, 8(AX)
	LEAQ -648(BP), CX
	MOVQ CX, 0(AX)
	MOVQ SI, -48(BP)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp55:
	MOVQ -16(BP), AX
	MOVQ -24(BP), CX
	LONG $0x780d84c6
	LONG $0x2ffffffd
	ADDQ BP, CX
	ADDQ $-647, CX
	MOVQ -48(BP), DX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc2
	MOVQ SP, SI
	MOVQ DX, 16(SI)
	MOVQ AX, 8(SI)
	MOVQ CX, 0(SI)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp56:
	LONG $0xa4fc45c7
	BYTE $0x01
	BYTE $0x00
	BYTE $0x00
	LEAQ -4(BP), AX
	MOVQ AX, -40(BP)
	LONG $0xe045c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -648(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x010840c7
	BYTE $0x06
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·open(SB)
_Ltmp57:
	MOVQ SP, AX
	MOVL 24(AX), DX
	BYTE $0x85
	BYTE $0xd2
	JMI _LBB5_3
	MOVQ SP, AX
	LEAQ _L_str_8<>(SB), CX
	MOVQ CX, 8(AX)
	MOVL DX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000001
	MOVL DX, -48(BP)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·write(SB)
_Ltmp58:
	MOVQ SP, AX
	MOVQ 24(AX), AX
	MOVQ AX, -24(BP)
	MOVQ SP, AX
	MOVL -48(BP), CX
	MOVL CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·close(SB)
_Ltmp59:
	MOVL $-1, CX
	LONG $0xe87d8348
	BYTE $0x01
	JNE _LBB5_8
	MOVQ SP, AX
	MOVL 8(AX), CX
_LBB5_8:
	MOVL CX, AX
	JMP _LBB5_4
_Lfunc_end5:
	FUNCDATA $0, gclocals·b5eb945e71b20448(SB)
DATA gclocals·b5eb945e71b20448+0(SB)/4, $3
DATA gclocals·b5eb945e71b20448+4(SB)/4, $1
DATA gclocals·b5eb945e71b20448+8(SB)/1, $0x01
DATA gclocals·b5eb945e71b20448+9(SB)/1, $0x01
DATA gclocals·b5eb945e71b20448+10(SB)/1, $0x01
GLOBL gclocals·b5eb945e71b20448(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·91529b8b01fd398b(SB)
DATA gclocals·91529b8b01fd398b+0(SB)/4, $3
DATA gclocals·91529b8b01fd398b+4(SB)/4, $87
DATA gclocals·91529b8b01fd398b+8(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+9(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+10(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+11(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+12(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+13(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+14(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+15(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+16(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+17(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+18(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+19(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+20(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+21(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+22(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+23(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+24(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+25(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+26(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+27(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+28(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+29(SB)/1, $0x2c
DATA gclocals·91529b8b01fd398b+30(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+31(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+32(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+33(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+34(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+35(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+36(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+37(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+38(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+39(SB)/1, $0x00
DATA gclocals·91529b8b01fd398b+40(SB)/1, $0x0c
GLOBL gclocals·91529b8b01fd398b(SB), DUPOK|RODATA, $41

TEXT ·c2go_mlib_nftw_count(SB), $56-32
	PCDATA $1, $-1
	CMPB ·c2go_mlib_ftw_force_gc(SB), $1
	MOVQ 16(BP), AX
	MOVQ 40(BP), CX
	JNE _LBB6_2
	MOVB $0, ·c2go_mlib_ftw_force_gc(SB)
	MOVQ AX, -16(BP)
	MOVQ 40(BP), AX
	MOVQ AX, -8(BP)
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp60:
	MOVQ -8(BP), CX
	MOVQ -16(BP), AX
_LBB6_2:
	INCL ·c2go_mlib_ftw_total(SB)
	MOVQ AX, -16(BP)
	MOVQ CX, -8(BP)
	MOVQ SP, CX
	LEAQ ·c2go_mlib_ftw_root(SB), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp61:
	MOVQ SP, CX
	MOVQ -8(BP), AX
	LONG $0x00107983
	JNE _LBB6_4
	MOVL ·c2go_mlib_ftw_total(SB), CX
	MOVL CX, ·c2go_mlib_ftw_root_pos(SB)
_LBB6_4:
	MOVL 32(BP), CX
	BYTE $0x83
	BYTE $0xf9
	BYTE $0x06
	JEQ _LBB6_9
	BYTE $0x83
	BYTE $0xf9
	BYTE $0x02
	JEQ _LBB6_6
	BYTE $0x83
	BYTE $0xf9
	BYTE $0x01
	JNE _LBB6_10
	LEAQ ·c2go_mlib_ftw_files(SB), CX
	JMP _LBB6_11
_LBB6_6:
	LEAQ ·c2go_mlib_ftw_dirs(SB), CX
	JMP _LBB6_11
_LBB6_9:
	LEAQ ·c2go_mlib_ftw_depth_dirs(SB), CX
	JMP _LBB6_11
_LBB6_10:
	LEAQ ·c2go_mlib_ftw_other(SB), CX
_LBB6_11:
	BYTE $0xff
	BYTE $0x01
	MOVL 4(AX), AX
	CMPL AX, ·c2go_mlib_ftw_max_level(SB)
	JLE _LBB6_13
	MOVL AX, ·c2go_mlib_ftw_max_level(SB)
_LBB6_13:
	XORL AX, AX
	RET
_Lfunc_end6:
	FUNCDATA $0, gclocals·28d4b2076fde8289(SB)
DATA gclocals·28d4b2076fde8289+0(SB)/4, $2
DATA gclocals·28d4b2076fde8289+4(SB)/4, $4
DATA gclocals·28d4b2076fde8289+8(SB)/1, $0x0b
DATA gclocals·28d4b2076fde8289+9(SB)/1, $0x0b
GLOBL gclocals·28d4b2076fde8289(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·9300ac6ea5fafef0(SB)
TEXT ·c2go_mlib_ftw_count(SB), $8-24
	PCDATA $1, $-1
	CMPB ·c2go_mlib_ftw_force_gc(SB), $1
	JNE _LBB7_2
	MOVB $0, ·c2go_mlib_ftw_force_gc(SB)
	PCDATA $1, $0
	CALL ·ForceGC(SB)
_Ltmp62:
_LBB7_2:
	INCL ·c2go_mlib_ftw_total(SB)
	XORL AX, AX
	RET
_Lfunc_end7:
	FUNCDATA $0, gclocals·78a6d35c07e36dbc(SB)
DATA gclocals·78a6d35c07e36dbc+0(SB)/4, $1
DATA gclocals·78a6d35c07e36dbc+4(SB)/4, $3
DATA gclocals·78a6d35c07e36dbc+8(SB)/1, $0x03
GLOBL gclocals·78a6d35c07e36dbc(SB), DUPOK|RODATA, $9

	FUNCDATA $1, gclocals·5f4910070d449e0f(SB)
TEXT ·c2go_mlib_nftw_stop(SB), $8-32
	PCDATA $1, $-1
	MOVL ·c2go_mlib_ftw_total(SB), AX
	BYTE $0xff
	BYTE $0xc0
	MOVL AX, ·c2go_mlib_ftw_total(SB)
	XORL CX, CX
	BYTE $0x83
	BYTE $0xf8
	BYTE $0x02
	MOVL $7, AX
	BYTE $0x0f
	BYTE $0x45
	BYTE $0xc1
	RET
_Lfunc_end8:
	FUNCDATA $0, gclocals·1fdeab329ab79cd1(SB)
DATA gclocals·1fdeab329ab79cd1+0(SB)/4, $1
DATA gclocals·1fdeab329ab79cd1+4(SB)/4, $4
DATA gclocals·1fdeab329ab79cd1+8(SB)/1, $0x0b
GLOBL gclocals·1fdeab329ab79cd1(SB), DUPOK|RODATA, $9

	FUNCDATA $1, gclocals·5f4910070d449e0f(SB)
TEXT ·c2go_mlib_nftw_remove(SB), $40-32
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0x06207d83
	JNE _LBB9_2
	MOVQ AX, -8(BP)
	MOVQ SP, AX
	MOVQ 16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·rmdir(SB)
_Ltmp63:
	JMP _LBB9_3
_LBB9_2:
	MOVQ AX, -8(BP)
	MOVQ SP, AX
	MOVQ 16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·unlink(SB)
_Ltmp64:
_LBB9_3:
	MOVQ SP, AX
	MOVL 8(AX), AX
	XORL CX, CX
	BYTE $0xf7
	BYTE $0xd8
	MOVL CX, AX
	BYTE $0x19
	BYTE $0xc8
	RET
_Lfunc_end9:
	FUNCDATA $0, gclocals·28d4b2076fde8289(SB)
	FUNCDATA $1, gclocals·4c2d44d481de39d2(SB)
DATA gclocals·4c2d44d481de39d2+0(SB)/4, $2
DATA gclocals·4c2d44d481de39d2+4(SB)/4, $5
DATA gclocals·4c2d44d481de39d2+8(SB)/1, $0x00
DATA gclocals·4c2d44d481de39d2+9(SB)/1, $0x10
GLOBL gclocals·4c2d44d481de39d2(SB), DUPOK|RODATA, $10

TEXT ·mlib_glob_unprefixed_selftest(SB), $4280-8
	PCDATA $1, $-1
	LONG $0xb045c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000048
	LONG $0x000840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memset(SB)
_Ltmp65:
	MOVQ SP, AX
	LEAQ _L_str_9<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·Getenv(SB)
_Ltmp66:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB10_2
	BYTE $0x80
	BYTE $0x39
	BYTE $0x00
	MOVQ CX, AX
	JNE _LBB10_5
_LBB10_2:
	MOVQ SP, AX
	LEAQ _L_str_1_10<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·Getenv(SB)
_Ltmp67:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB10_4
	BYTE $0x80
	BYTE $0x39
	BYTE $0x00
	MOVQ CX, AX
	JNE _LBB10_5
_LBB10_4:
	LEAQ _L_str_2_11<>(SB), CX
	XORL AX, AX
_LBB10_5:
	MOVQ AX, -16(BP)
	MOVQ CX, -8(BP)
	MOVQ SP, AX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp68:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -96(BP)
	MOVQ SP, AX
	LEAQ _L_str_3_12<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp69:
	MOVQ -96(BP), DX
	MOVQ SP, AX
	MOVQ 8(AX), SI
	MOVL $512, AX
	SUBQ DX, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc6
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB10_7
	LEAQ 0(DX)(SI*1), AX
	ADDQ $2, AX
	LONG $0x02013d48
	BYTE $0x00
	BYTE $0x00
	JCS _LBB10_10
_LBB10_7:
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp70:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
_LBB10_8:
	MOVL $1, CX
_LBB10_9:
	MOVL CX, 16(BP)
	RET
_LBB10_10:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ DX, 16(CX)
	MOVQ AX, 8(CX)
	LEAQ -616(BP), AX
	MOVQ AX, 0(CX)
	MOVQ SI, -104(BP)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp71:
	MOVQ -96(BP), AX
	LONG $0x980584c6
	LONG $0x2ffffffd
	ADDQ BP, AX
	LONG $0xfd990548
	BYTE $0xff
	BYTE $0xff
	MOVQ -104(BP), CX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc1
	MOVQ SP, DX
	MOVQ CX, 16(DX)
	LEAQ _L_str_3_12<>(SB), CX
	MOVQ CX, 8(DX)
	MOVQ AX, 0(DX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp72:
	MOVQ SP, AX
	LEAQ -616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·mkdtemp(SB)
_Ltmp73:
	MOVQ SP, AX
	LONG $0x08788348
	BYTE $0x00
	JEQ _LBB10_8
	MOVQ SP, AX
	LEAQ _L_str_4_13<>(SB), CX
	MOVQ CX, 8(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_mkfile(SB)
_Ltmp74:
	MOVL $2, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_5_14<>(SB), CX
	MOVQ CX, 8(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_mkfile(SB)
_Ltmp75:
	MOVL $3, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_6_15<>(SB), CX
	MOVQ CX, 8(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_mkfile(SB)
_Ltmp76:
	MOVL $4, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_7_16<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp77:
	MOVL $5, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	LONG $0xed0840c7
	BYTE $0x01
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·mkdir(SB)
_Ltmp78:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL $5, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_5_14<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -3616(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp79:
	MOVL $6, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_4_13<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -2416(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp80:
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_18
	MOVQ SP, AX
	LEAQ _L_str_6_15<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -3016(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp81:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_22
_LBB10_18:
	MOVL $6, CX
	JMP _LBB10_9
_LBB10_22:
	MOVQ SP, AX
	LEAQ _L_str_8_17<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp82:
	MOVL $6, CX
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x000840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp83:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x00207883
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x02
	MOVL $8, CX
	JNE _LBB10_9
	LONG $0xb07d8348
	BYTE $0x00
	JEQ _LBB10_9
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp84:
	MOVQ -80(BP), AX
	MOVQ 0(AX), CX
	MOVQ CX, -8(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, AX
	LEAQ -3616(BP), DX
	MOVQ DX, 8(AX)
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp85:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_27
	MOVQ -16(BP), AX
	MOVQ 8(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -2416(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp86:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB10_30
_LBB10_27:
	MOVL $9, CX
	JMP _LBB10_9
_LBB10_30:
	MOVQ -16(BP), AX
	LONG $0x10788348
	BYTE $0x00
	MOVL $9, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_9_18<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp87:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_33
	MOVL $10, CX
	JMP _LBB10_9
_LBB10_33:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp88:
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x200840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp89:
	MOVQ SP, AX
	LONG $0x00207883
	MOVL $10, CX
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x03
	MOVL $11, CX
	JNE _LBB10_9
	LONG $0xb07d8348
	BYTE $0x00
	JEQ _LBB10_9
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp90:
	MOVQ -80(BP), AX
	MOVQ 0(AX), CX
	MOVQ CX, -8(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, AX
	LEAQ -3616(BP), DX
	MOVQ DX, 8(AX)
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp91:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_37
	MOVQ -16(BP), AX
	MOVQ 8(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -2416(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp92:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_37
	MOVQ -16(BP), AX
	MOVQ 16(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -3016(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp93:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB10_42
_LBB10_37:
	MOVL $12, CX
	JMP _LBB10_9
_LBB10_42:
	MOVQ -16(BP), AX
	LONG $0x18788348
	BYTE $0x00
	MOVL $12, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_globfree(SB)
_Ltmp94:
	LONG $0xa87d8348
	BYTE $0x00
	MOVL $13, CX
	JNE _LBB10_9
	LONG $0xb07d8348
	BYTE $0x00
	JNE _LBB10_9
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp95:
	LONG $0xb845c748
	LONG $0x00000002
	MOVQ SP, AX
	LEAQ _L_str_8_17<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp96:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_47
	MOVL $14, CX
	JMP _LBB10_9
_LBB10_47:
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x080840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp97:
	MOVQ SP, AX
	LONG $0x00207883
	MOVL $14, CX
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x02
	MOVQ -80(BP), AX
	BYTE $0x0f
	BYTE $0x94
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	BYTE $0x0f
	BYTE $0x95
	BYTE $0xc2
	ANDB CL, DL
	BYTE $0x80
	BYTE $0xfa
	BYTE $0x01
	JNE _LBB10_51
	LONG $0x00388348
	JNE _LBB10_51
	LONG $0x08788348
	BYTE $0x00
	JNE _LBB10_51
	MOVQ 16(AX), CX
	MOVQ AX, -16(BP)
	MOVQ CX, -8(BP)
	MOVQ SP, AX
	LEAQ -3616(BP), DX
	MOVQ DX, 8(AX)
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp98:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_51
	MOVQ -16(BP), AX
	MOVQ 24(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -2416(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp99:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB10_58
_LBB10_51:
	MOVL $15, CX
	JMP _LBB10_9
_LBB10_58:
	MOVQ -16(BP), AX
	LONG $0x20788348
	BYTE $0x00
	MOVL $15, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_9_18<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp100:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_61
	MOVL $16, CX
	JMP _LBB10_9
_LBB10_61:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp101:
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x280840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp102:
	MOVQ SP, AX
	LONG $0x00207883
	MOVL $16, CX
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x03
	MOVQ -80(BP), AX
	BYTE $0x0f
	BYTE $0x94
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	BYTE $0x0f
	BYTE $0x95
	BYTE $0xc2
	ANDB CL, DL
	BYTE $0x80
	BYTE $0xfa
	BYTE $0x01
	JNE _LBB10_65
	LONG $0x00388348
	JNE _LBB10_65
	LONG $0x08788348
	BYTE $0x00
	JNE _LBB10_65
	MOVQ 16(AX), CX
	MOVQ AX, -16(BP)
	MOVQ CX, -8(BP)
	MOVQ SP, AX
	LEAQ -3616(BP), DX
	MOVQ DX, 8(AX)
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp103:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_65
	MOVQ -16(BP), AX
	MOVQ 24(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -2416(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp104:
	MOVQ SP, AX
	LONG $0x00107883
	JNE _LBB10_65
	MOVQ -16(BP), AX
	MOVQ 32(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -3016(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp105:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB10_74
_LBB10_65:
	MOVL $17, CX
	JMP _LBB10_9
_LBB10_74:
	MOVQ -16(BP), AX
	LONG $0x28788348
	BYTE $0x00
	MOVL $17, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_globfree(SB)
_Ltmp106:
	MOVQ SP, AX
	LEAQ _L_str_10<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp107:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_77
	MOVL $18, CX
	JMP _LBB10_9
_LBB10_77:
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x100840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp108:
	MOVQ SP, AX
	LONG $0x00207883
	MOVL $18, CX
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x01
	JNE _LBB10_81
	MOVQ -80(BP), AX
	MOVQ 0(AX), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -1816(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp109:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB10_82
_LBB10_81:
	MOVL $19, CX
	JMP _LBB10_9
_LBB10_82:
	MOVQ -80(BP), AX
	LONG $0x08788348
	BYTE $0x00
	MOVL $19, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_globfree(SB)
_Ltmp110:
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x000840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp111:
	MOVQ SP, AX
	MOVL $20, CX
	LONG $0x03207883
	JNE _LBB10_9
	LONG $0xa87d8348
	BYTE $0x00
	MOVL $21, CX
	JNE _LBB10_9
	LONG $0xb07d8348
	BYTE $0x00
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ _L_str_11<>(SB), CX
	MOVQ CX, 24(AX)
	LEAQ -616(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000258
	PCDATA $1, $1
	CALL ·c2go_mlib_glob_path(SB)
_Ltmp112:
	BYTE $0x85
	BYTE $0xc0
	JNE _LBB10_87
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp113:
	MOVQ SP, AX
	MOVQ $-601, CX
	LONG $0x08480348
	LONG $0xa5f98148
	BYTE $0xfd
	BYTE $0xff
	BYTE $0xff
	JCC _LBB10_90
_LBB10_87:
	MOVL $22, CX
	JMP _LBB10_9
_LBB10_90:
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp114:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ SP, CX
	MOVQ AX, 16(CX)
	LEAQ -1216(BP), AX
	MOVQ AX, 8(CX)
	LEAQ -4224(BP), AX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp115:
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp116:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	LONG $0x800584c6
	LONG $0x2fffffef
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp117:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	LONG $0x810584c6
	LONG $0x00ffffef
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 24(AX)
	LEAQ -1816(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x1040c748
	LONG $0x00000000
	LONG $0x020840c7
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_glob(SB)
_Ltmp118:
	MOVQ SP, AX
	LONG $0x00207883
	MOVL $22, CX
	JNE _LBB10_9
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp119:
	LONG $0xa87d8348
	BYTE $0x00
	JEQ _LBB10_97
	XORL CX, CX
	MOVL CX, DX
_LBB10_93:
	MOVQ DX, -104(BP)
	MOVL CX, -96(BP)
	MOVQ -80(BP), AX
	MOVQ 0(AX)(DX*8), AX
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	LEAQ -4224(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·strcmp(SB)
_Ltmp120:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL -96(BP), AX
	MOVL $1, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc1
	MOVQ -104(BP), DX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc2
	MOVL AX, CX
	LONG $0xa8553b48
	JCS _LBB10_93
	MOVL $23, CX
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB10_9
	MOVQ SP, AX
	LEAQ -88(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_globfree(SB)
_Ltmp121:
	MOVQ SP, AX
	LEAQ -3616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·unlink(SB)
_Ltmp122:
	MOVQ SP, AX
	LONG $0x00087883
	JNE _LBB10_96
	MOVQ SP, AX
	LEAQ -2416(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·unlink(SB)
_Ltmp123:
	MOVQ SP, AX
	LONG $0x00087883
	JNE _LBB10_96
	MOVQ SP, AX
	LEAQ -3016(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·unlink(SB)
_Ltmp124:
	MOVQ SP, AX
	LONG $0x00087883
	JEQ _LBB10_102
_LBB10_96:
	MOVL $24, CX
	JMP _LBB10_9
_LBB10_97:
	MOVL $23, CX
	JMP _LBB10_9
_LBB10_102:
	MOVQ SP, AX
	LEAQ -1216(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·rmdir(SB)
_Ltmp125:
	MOVQ SP, AX
	LONG $0x00087883
	MOVL $24, CX
	JNE _LBB10_9
	MOVQ SP, AX
	LEAQ -616(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·rmdir(SB)
_Ltmp126:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $24, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	JMP _LBB10_9
_Lfunc_end10:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·a3b2d7ae67cd5cb0(SB)
DATA gclocals·a3b2d7ae67cd5cb0+0(SB)/4, $4
DATA gclocals·a3b2d7ae67cd5cb0+4(SB)/4, $535
DATA gclocals·a3b2d7ae67cd5cb0+8(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+9(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+10(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+11(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+12(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+13(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+14(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+15(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+16(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+17(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+18(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+19(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+20(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+21(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+22(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+23(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+24(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+25(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+26(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+27(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+28(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+29(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+30(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+31(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+32(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+33(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+34(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+35(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+36(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+37(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+38(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+39(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+40(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+41(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+42(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+43(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+44(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+45(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+46(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+47(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+48(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+49(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+50(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+51(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+52(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+53(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+54(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+55(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+56(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+57(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+58(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+59(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+60(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+61(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+62(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+63(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+64(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+65(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+66(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+67(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+68(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+69(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+70(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+71(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+72(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+73(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+74(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+75(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+76(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+77(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+78(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+79(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+80(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+81(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+82(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+83(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+84(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+85(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+86(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+87(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+88(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+89(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+90(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+91(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+92(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+93(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+94(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+95(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+96(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+97(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+98(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+99(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+100(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+101(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+102(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+103(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+104(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+105(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+106(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+107(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+108(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+109(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+110(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+111(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+112(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+113(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+114(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+115(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+116(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+117(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+118(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+119(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+120(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+121(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+122(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+123(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+124(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+125(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+126(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+127(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+128(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+129(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+130(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+131(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+132(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+133(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+134(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+135(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+136(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+137(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+138(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+139(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+140(SB)/1, $0x20
DATA gclocals·a3b2d7ae67cd5cb0+141(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+142(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+143(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+144(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+145(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+146(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+147(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+148(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+149(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+150(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+151(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+152(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+153(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+154(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+155(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+156(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+157(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+158(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+159(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+160(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+161(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+162(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+163(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+164(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+165(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+166(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+167(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+168(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+169(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+170(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+171(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+172(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+173(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+174(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+175(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+176(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+177(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+178(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+179(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+180(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+181(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+182(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+183(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+184(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+185(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+186(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+187(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+188(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+189(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+190(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+191(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+192(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+193(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+194(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+195(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+196(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+197(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+198(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+199(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+200(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+201(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+202(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+203(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+204(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+205(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+206(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+207(SB)/1, $0x20
DATA gclocals·a3b2d7ae67cd5cb0+208(SB)/1, $0x60
DATA gclocals·a3b2d7ae67cd5cb0+209(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+210(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+211(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+212(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+213(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+214(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+215(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+216(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+217(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+218(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+219(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+220(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+221(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+222(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+223(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+224(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+225(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+226(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+227(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+228(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+229(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+230(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+231(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+232(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+233(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+234(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+235(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+236(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+237(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+238(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+239(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+240(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+241(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+242(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+243(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+244(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+245(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+246(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+247(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+248(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+249(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+250(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+251(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+252(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+253(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+254(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+255(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+256(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+257(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+258(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+259(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+260(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+261(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+262(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+263(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+264(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+265(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+266(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+267(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+268(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+269(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+270(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+271(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+272(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+273(SB)/1, $0x00
DATA gclocals·a3b2d7ae67cd5cb0+274(SB)/1, $0x20
DATA gclocals·a3b2d7ae67cd5cb0+275(SB)/1, $0x40
GLOBL gclocals·a3b2d7ae67cd5cb0(SB), DUPOK|RODATA, $276

TEXT ·c2go_mlib_glob_mkfile(SB), $696-16
	PCDATA $1, $-1
	MOVQ 24(BP), AX
	MOVQ 16(BP), CX
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -40(BP)
	MOVQ CX, -24(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, AX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp127:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -48(BP)
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp128:
	MOVQ -48(BP), DX
	MOVQ SP, AX
	MOVQ 8(AX), SI
	MOVL $600, AX
	SUBQ DX, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc6
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB11_2
	LEAQ 0(DX)(SI*1), AX
	ADDQ $2, AX
	LONG $0x02593d48
	BYTE $0x00
	BYTE $0x00
	JCS _LBB11_5
_LBB11_2:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp129:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
_LBB11_3:
	MOVL $-1, AX
_LBB11_4:
	RET
_LBB11_5:
	MOVQ -24(BP), AX
	MOVQ SP, CX
	MOVQ DX, 16(CX)
	MOVQ AX, 8(CX)
	LEAQ -656(BP), AX
	MOVQ AX, 0(CX)
	MOVQ SI, -56(BP)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp130:
	MOVQ -16(BP), AX
	MOVQ -48(BP), CX
	LONG $0x700d84c6
	LONG $0x2ffffffd
	ADDQ BP, CX
	ADDQ $-655, CX
	MOVQ -56(BP), DX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc2
	MOVQ SP, SI
	MOVQ DX, 16(SI)
	MOVQ AX, 8(SI)
	MOVQ CX, 0(SI)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp131:
	LONG $0xa4fc45c7
	BYTE $0x01
	BYTE $0x00
	BYTE $0x00
	LEAQ -4(BP), AX
	MOVQ AX, -40(BP)
	LONG $0xe045c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -656(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x010840c7
	BYTE $0x06
	BYTE $0x00
	BYTE $0x00
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc·open(SB)
_Ltmp132:
	MOVQ SP, AX
	MOVL 24(AX), AX
	BYTE $0x85
	BYTE $0xc0
	JMI _LBB11_3
	MOVQ SP, CX
	MOVL AX, 0(CX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·close(SB)
_Ltmp133:
	MOVQ SP, AX
	MOVL 8(AX), AX
	JMP _LBB11_4
_Lfunc_end11:
	FUNCDATA $0, gclocals·f75f0251d3cfbdd7(SB)
DATA gclocals·f75f0251d3cfbdd7+0(SB)/4, $4
DATA gclocals·f75f0251d3cfbdd7+4(SB)/4, $2
DATA gclocals·f75f0251d3cfbdd7+8(SB)/1, $0x03
DATA gclocals·f75f0251d3cfbdd7+9(SB)/1, $0x03
DATA gclocals·f75f0251d3cfbdd7+10(SB)/1, $0x03
DATA gclocals·f75f0251d3cfbdd7+11(SB)/1, $0x03
GLOBL gclocals·f75f0251d3cfbdd7(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·b3222361e5b066da(SB)
DATA gclocals·b3222361e5b066da+0(SB)/4, $4
DATA gclocals·b3222361e5b066da+4(SB)/4, $87
DATA gclocals·b3222361e5b066da+8(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+9(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+10(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+11(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+12(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+13(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+14(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+15(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+16(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+17(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+18(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+19(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+20(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+21(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+22(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+23(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+24(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+25(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+26(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+27(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+28(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+29(SB)/1, $0x3c
DATA gclocals·b3222361e5b066da+30(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+31(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+32(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+33(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+34(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+35(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+36(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+37(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+38(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+39(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+40(SB)/1, $0x2c
DATA gclocals·b3222361e5b066da+41(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+42(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+43(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+44(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+45(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+46(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+47(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+48(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+49(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+50(SB)/1, $0x00
DATA gclocals·b3222361e5b066da+51(SB)/1, $0x0c
GLOBL gclocals·b3222361e5b066da(SB), DUPOK|RODATA, $52

TEXT ·c2go_mlib_glob_path(SB), $88-32
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	MOVQ 32(BP), CX
	MOVQ 40(BP), DX
	MOVQ DX, -16(BP)
	MOVQ CX, -24(BP)
	MOVQ AX, -8(BP)
	MOVQ SP, AX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp134:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	MOVQ AX, -32(BP)
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·strlen(SB)
_Ltmp135:
	MOVQ -32(BP), SI
	MOVQ SP, AX
	MOVQ 8(AX), DX
	MOVQ 24(BP), AX
	SUBQ SI, AX
	BYTE $0x0f
	BYTE $0x92
	BYTE $0xc1
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc2
	BYTE $0x0f
	BYTE $0x97
	BYTE $0xc0
	ORB CL, AL
	JNE _LBB12_2
	LEAQ 0(SI)(DX*1), AX
	ADDQ $2, AX
	MOVQ 24(BP), CX
	BYTE $0x48
	BYTE $0x39
	BYTE $0xc8
	JLS _LBB12_3
_LBB12_2:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·ErrnoPtr(SB)
_Ltmp136:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	LONG $0x003f00c7
	BYTE $0x00
	BYTE $0x00
	MOVL $-1, AX
	JMP _LBB12_4
_LBB12_3:
	MOVQ -8(BP), AX
	MOVQ -24(BP), CX
	MOVQ DX, -40(BP)
	MOVQ SP, DX
	MOVQ SI, 16(DX)
	MOVQ CX, 8(DX)
	MOVQ AX, 0(DX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp137:
	MOVQ -8(BP), AX
	MOVQ -16(BP), CX
	MOVQ -32(BP), DX
	LONG $0x2f1004c6
	ADDQ DX, AX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc0
	MOVQ -40(BP), DX
	BYTE $0x48
	BYTE $0xff
	BYTE $0xc2
	MOVQ SP, SI
	MOVQ DX, 16(SI)
	MOVQ CX, 8(SI)
	MOVQ AX, 0(SI)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·memmove(SB)
_Ltmp138:
	XORL AX, AX
_LBB12_4:
	RET
_Lfunc_end12:
	FUNCDATA $0, gclocals·54645eab1d167ee7(SB)
DATA gclocals·54645eab1d167ee7+0(SB)/4, $3
DATA gclocals·54645eab1d167ee7+4(SB)/4, $4
DATA gclocals·54645eab1d167ee7+8(SB)/1, $0x0d
DATA gclocals·54645eab1d167ee7+9(SB)/1, $0x0d
DATA gclocals·54645eab1d167ee7+10(SB)/1, $0x0d
GLOBL gclocals·54645eab1d167ee7(SB), DUPOK|RODATA, $11

	FUNCDATA $1, gclocals·ff4663bd478145ba(SB)
DATA gclocals·ff4663bd478145ba+0(SB)/4, $3
DATA gclocals·ff4663bd478145ba+4(SB)/4, $11
DATA gclocals·ff4663bd478145ba+8(SB)/1, $0x00
DATA gclocals·ff4663bd478145ba+9(SB)/1, $0x00
DATA gclocals·ff4663bd478145ba+10(SB)/1, $0x00
DATA gclocals·ff4663bd478145ba+11(SB)/1, $0x07
DATA gclocals·ff4663bd478145ba+12(SB)/1, $0x00
DATA gclocals·ff4663bd478145ba+13(SB)/1, $0x06
GLOBL gclocals·ff4663bd478145ba(SB), DUPOK|RODATA, $14

TEXT ·mlib_pthread_unprefixed_selftest(SB), $88-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xf045c748
	LONG $0x00000000
	LONG $0xd845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp139:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB13_2
	ADDL $10, AX
	JMP _LBB13_22
_LBB13_2:
	MOVQ SP, AX
	LEAQ ·unprefixed_global_mutex(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp140:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB13_4
	ADDL $20, AX
_LBB13_22:
	MOVL AX, 16(BP)
	RET
_LBB13_4:
	MOVQ SP, AX
	MOVQ ·_typeinfo_pthread_mutex_t(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000008
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp141:
	MOVQ SP, AX
	MOVQ 16(AX), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB13_5
	MOVQ AX, -48(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp142:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB13_8
	ADDL $30, AX
	JMP _LBB13_22
_LBB13_5:
	MOVL $30, AX
	JMP _LBB13_22
_LBB13_8:
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xf045c748
	LONG $0x00000000
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp143:
	MOVQ SP, AX
	MOVL $51, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB13_22
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp144:
	MOVQ SP, AX
	MOVL $52, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB13_22
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp145:
	MOVQ SP, AX
	MOVL $53, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB13_22
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp146:
	MOVQ SP, AX
	LEAQ -32(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp147:
	MOVQ SP, AX
	MOVL $54, CX
	LONG $0x3c187883
	MOVL CX, AX
	JNE _LBB13_22
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp148:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp149:
	MOVQ SP, AX
	MOVL $55, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB13_22
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp150:
	MOVQ SP, AX
	MOVL $56, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB13_22
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp151:
	MOVQ SP, AX
	MOVL $57, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB13_22
	PCDATA $1, $0
	CALL ·exercise_unprefixed_rwlock(SB)
_Ltmp152:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB13_17
	ADDL $70, AX
	JMP _LBB13_22
_LBB13_17:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadSelf(SB)
_Ltmp153:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVQ SP, CX
	MOVQ AX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadEqual(SB)
_Ltmp154:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB13_18
	MOVQ SP, AX
	LEAQ ·unprefixed_once_init(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·unprefixed_once(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp155:
	MOVQ SP, AX
	MOVL $92, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB13_22
	MOVQ SP, AX
	LEAQ ·unprefixed_once_init(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·unprefixed_once(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp156:
	MOVQ SP, AX
	MOVL $93, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB13_22
	XORL AX, AX
	CMPL ·unprefixed_once_count(SB), $1
	MOVL $94, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
	JMP _LBB13_22
_LBB13_18:
	MOVL $91, AX
	JMP _LBB13_22
_Lfunc_end13:
	FUNCDATA $0, gclocals·4049a89979623773(SB)
DATA gclocals·4049a89979623773+0(SB)/4, $5
DATA gclocals·4049a89979623773+4(SB)/4, $1
DATA gclocals·4049a89979623773+8(SB)/1, $0x00
DATA gclocals·4049a89979623773+9(SB)/1, $0x00
DATA gclocals·4049a89979623773+10(SB)/1, $0x00
DATA gclocals·4049a89979623773+11(SB)/1, $0x00
DATA gclocals·4049a89979623773+12(SB)/1, $0x00
GLOBL gclocals·4049a89979623773(SB), DUPOK|RODATA, $13

	FUNCDATA $1, gclocals·bda3f787f14ed759(SB)
DATA gclocals·bda3f787f14ed759+0(SB)/4, $5
DATA gclocals·bda3f787f14ed759+4(SB)/4, $11
DATA gclocals·bda3f787f14ed759+8(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+9(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+10(SB)/1, $0x40
DATA gclocals·bda3f787f14ed759+11(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+12(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+13(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+14(SB)/1, $0x20
DATA gclocals·bda3f787f14ed759+15(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+16(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+17(SB)/1, $0x04
GLOBL gclocals·bda3f787f14ed759(SB), DUPOK|RODATA, $18

TEXT ·exercise_unprefixed_mutex(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	LONG $0x0841c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp157:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB14_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp158:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB14_6
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp159:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp160:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB14_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp161:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x3c107883
	MOVL CX, AX
	JNE _LBB14_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp162:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB14_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp163:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $6, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB14_6:
	RET
_Lfunc_end14:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·exercise_unprefixed_rwlock(SB), $40-0
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp164:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp165:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB15_8
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp166:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp167:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp168:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp169:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp170:
	MOVQ SP, AX
	MOVL $6, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp171:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB15_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp172:
	MOVQ SP, AX
	XORL CX, CX
	LONG $0x00087883
	BYTE $0x0f
	BYTE $0x95
	BYTE $0xc0
	MOVB AL, CL
	SHLL $3, CX
	MOVL CX, AX
_LBB15_8:
	RET
_Lfunc_end15:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4c2d44d481de39d2(SB)
TEXT ·unprefixed_once_init(SB), $8-0
	PCDATA $1, $-1
	INCL ·unprefixed_once_count(SB)
	RET
_Lfunc_end16:
	FUNCDATA $0, gclocals·89cd31291d2aefa4(SB)
DATA gclocals·89cd31291d2aefa4+0(SB)/4, $1
DATA gclocals·89cd31291d2aefa4+4(SB)/4, $0
GLOBL gclocals·89cd31291d2aefa4(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·5f4910070d449e0f(SB)
TEXT ·mlib_sem_unprefixed_selftest(SB), $24-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp173:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB17_2
	ADDL $10, AX
	JMP _LBB17_3
_LBB17_2:
	MOVQ SP, AX
	LEAQ ·unprefixed_global_sem(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp174:
	MOVL AX, CX
	ADDL $20, CX
	BYTE $0x85
	BYTE $0xc0
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB17_3:
	MOVL AX, 16(BP)
	RET
_Lfunc_end17:
	FUNCDATA $0, gclocals·be86e5a039a56de6(SB)
	FUNCDATA $1, gclocals·055a193a5dc1daa8(SB)
DATA gclocals·055a193a5dc1daa8+0(SB)/4, $2
DATA gclocals·055a193a5dc1daa8+4(SB)/4, $3
DATA gclocals·055a193a5dc1daa8+8(SB)/1, $0x00
DATA gclocals·055a193a5dc1daa8+9(SB)/1, $0x04
GLOBL gclocals·055a193a5dc1daa8(SB), DUPOK|RODATA, $10

TEXT ·exercise_unprefixed_sem(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0xfffc45c7
	BYTE $0xff
	BYTE $0xff
	BYTE $0xff
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ $4294967296, DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp175:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB18_8
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp176:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp177:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB18_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp178:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x3c107883
	MOVL CX, AX
	JNE _LBB18_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp179:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x23087883
	MOVL CX, AX
	JNE _LBB18_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp180:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB18_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -4(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp181:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL $6, AX
	JNE _LBB18_8
	LONG $0x01fc7d83
	JNE _LBB18_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp182:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $7, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB18_8:
	RET
_Lfunc_end18:
DATA _L_str<>+0(SB)/1, $0x2e
DATA _L_str<>+1(SB)/1, $0x00
GLOBL _L_str<>(SB), RODATA, $2

DATA _L_str_1<>+0(SB)/1, $0x2e
DATA _L_str_1<>+1(SB)/1, $0x2e
DATA _L_str_1<>+2(SB)/1, $0x00
GLOBL _L_str_1<>(SB), RODATA, $3

GLOBL ·force_gc_in_compare(SB), NOPTR, $1

DATA _L_str_2<>+0(SB)/1, $0x54
DATA _L_str_2<>+1(SB)/1, $0x4d
DATA _L_str_2<>+2(SB)/1, $0x50
DATA _L_str_2<>+3(SB)/1, $0x44
DATA _L_str_2<>+4(SB)/1, $0x49
DATA _L_str_2<>+5(SB)/1, $0x52
DATA _L_str_2<>+6(SB)/1, $0x00
GLOBL _L_str_2<>(SB), RODATA, $7

DATA _L_str_1_3<>+0(SB)/1, $0x2f
DATA _L_str_1_3<>+1(SB)/1, $0x74
DATA _L_str_1_3<>+2(SB)/1, $0x6d
DATA _L_str_1_3<>+3(SB)/1, $0x70
DATA _L_str_1_3<>+4(SB)/1, $0x00
GLOBL _L_str_1_3<>(SB), RODATA, $5

GLOBL ·c2go_mlib_ftw_root(SB), NOPTR, $512

DATA _L_str_2_4<>+0(SB)/8, $0x696c6d5f6f673263
DATA _L_str_2_4<>+8(SB)/8, $0x58585f7774665f62
DATA _L_str_2_4<>+16(SB)/1, $0x58
DATA _L_str_2_4<>+17(SB)/1, $0x58
DATA _L_str_2_4<>+18(SB)/1, $0x58
DATA _L_str_2_4<>+19(SB)/1, $0x58
DATA _L_str_2_4<>+20(SB)/1, $0x00
GLOBL _L_str_2_4<>(SB), RODATA, $21

DATA _L_str_3<>+0(SB)/1, $0x61
DATA _L_str_3<>+1(SB)/1, $0x00
GLOBL _L_str_3<>(SB), RODATA, $2

DATA _L_str_4<>+0(SB)/1, $0x61
DATA _L_str_4<>+1(SB)/1, $0x2f
DATA _L_str_4<>+2(SB)/1, $0x62
DATA _L_str_4<>+3(SB)/1, $0x00
GLOBL _L_str_4<>(SB), RODATA, $4

DATA _L_str_5<>+0(SB)/1, $0x66
DATA _L_str_5<>+1(SB)/1, $0x31
DATA _L_str_5<>+2(SB)/1, $0x00
GLOBL _L_str_5<>(SB), RODATA, $3

DATA _L_str_6<>+0(SB)/1, $0x61
DATA _L_str_6<>+1(SB)/1, $0x2f
DATA _L_str_6<>+2(SB)/1, $0x66
DATA _L_str_6<>+3(SB)/1, $0x32
DATA _L_str_6<>+4(SB)/1, $0x00
GLOBL _L_str_6<>(SB), RODATA, $5

DATA _L_str_7<>+0(SB)/1, $0x61
DATA _L_str_7<>+1(SB)/1, $0x2f
DATA _L_str_7<>+2(SB)/1, $0x62
DATA _L_str_7<>+3(SB)/1, $0x2f
DATA _L_str_7<>+4(SB)/1, $0x66
DATA _L_str_7<>+5(SB)/1, $0x33
DATA _L_str_7<>+6(SB)/1, $0x00
GLOBL _L_str_7<>(SB), RODATA, $7

GLOBL ·c2go_mlib_ftw_force_gc(SB), NOPTR, $1

GLOBL ·c2go_mlib_ftw_total(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_root_pos(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_dirs(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_files(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_depth_dirs(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_other(SB), NOPTR, $4

GLOBL ·c2go_mlib_ftw_max_level(SB), NOPTR, $4

DATA _L_str_8<>+0(SB)/1, $0x78
DATA _L_str_8<>+1(SB)/1, $0x00
GLOBL _L_str_8<>(SB), RODATA, $2

DATA _L_str_9<>+0(SB)/1, $0x54
DATA _L_str_9<>+1(SB)/1, $0x4d
DATA _L_str_9<>+2(SB)/1, $0x50
DATA _L_str_9<>+3(SB)/1, $0x44
DATA _L_str_9<>+4(SB)/1, $0x49
DATA _L_str_9<>+5(SB)/1, $0x52
DATA _L_str_9<>+6(SB)/1, $0x00
GLOBL _L_str_9<>(SB), RODATA, $7

DATA _L_str_1_10<>+0(SB)/1, $0x54
DATA _L_str_1_10<>+1(SB)/1, $0x45
DATA _L_str_1_10<>+2(SB)/1, $0x4d
DATA _L_str_1_10<>+3(SB)/1, $0x50
DATA _L_str_1_10<>+4(SB)/1, $0x00
GLOBL _L_str_1_10<>(SB), RODATA, $5

DATA _L_str_2_11<>+0(SB)/1, $0x2e
DATA _L_str_2_11<>+1(SB)/1, $0x00
GLOBL _L_str_2_11<>(SB), RODATA, $2

DATA _L_str_3_12<>+0(SB)/8, $0x696c6d5f6f673263
DATA _L_str_3_12<>+8(SB)/8, $0x585f626f6c675f62
DATA _L_str_3_12<>+16(SB)/1, $0x58
DATA _L_str_3_12<>+17(SB)/1, $0x58
DATA _L_str_3_12<>+18(SB)/1, $0x58
DATA _L_str_3_12<>+19(SB)/1, $0x58
DATA _L_str_3_12<>+20(SB)/1, $0x58
DATA _L_str_3_12<>+21(SB)/1, $0x00
GLOBL _L_str_3_12<>(SB), RODATA, $22

DATA _L_str_4_13<>+0(SB)/1, $0x62
DATA _L_str_4_13<>+1(SB)/1, $0x2e
DATA _L_str_4_13<>+2(SB)/1, $0x63
DATA _L_str_4_13<>+3(SB)/1, $0x00
GLOBL _L_str_4_13<>(SB), RODATA, $4

DATA _L_str_5_14<>+0(SB)/1, $0x61
DATA _L_str_5_14<>+1(SB)/1, $0x2e
DATA _L_str_5_14<>+2(SB)/1, $0x63
DATA _L_str_5_14<>+3(SB)/1, $0x00
GLOBL _L_str_5_14<>(SB), RODATA, $4

DATA _L_str_6_15<>+0(SB)/1, $0x63
DATA _L_str_6_15<>+1(SB)/1, $0x2e
DATA _L_str_6_15<>+2(SB)/1, $0x68
DATA _L_str_6_15<>+3(SB)/1, $0x00
GLOBL _L_str_6_15<>(SB), RODATA, $4

DATA _L_str_7_16<>+0(SB)/1, $0x73
DATA _L_str_7_16<>+1(SB)/1, $0x75
DATA _L_str_7_16<>+2(SB)/1, $0x62
DATA _L_str_7_16<>+3(SB)/1, $0x00
GLOBL _L_str_7_16<>(SB), RODATA, $4

DATA _L_str_8_17<>+0(SB)/1, $0x2a
DATA _L_str_8_17<>+1(SB)/1, $0x2e
DATA _L_str_8_17<>+2(SB)/1, $0x63
DATA _L_str_8_17<>+3(SB)/1, $0x00
GLOBL _L_str_8_17<>(SB), RODATA, $4

DATA _L_str_9_18<>+0(SB)/1, $0x2a
DATA _L_str_9_18<>+1(SB)/1, $0x2e
DATA _L_str_9_18<>+2(SB)/1, $0x68
DATA _L_str_9_18<>+3(SB)/1, $0x00
GLOBL _L_str_9_18<>(SB), RODATA, $4

DATA _L_str_10<>+0(SB)/8, $0x2d676e697373696d
DATA _L_str_10<>+8(SB)/1, $0x2a
DATA _L_str_10<>+9(SB)/1, $0x2e
DATA _L_str_10<>+10(SB)/1, $0x7a
DATA _L_str_10<>+11(SB)/1, $0x7a
DATA _L_str_10<>+12(SB)/1, $0x00
GLOBL _L_str_10<>(SB), RODATA, $13

DATA _L_str_11<>+0(SB)/1, $0x2a
DATA _L_str_11<>+1(SB)/1, $0x00
GLOBL _L_str_11<>(SB), RODATA, $2

GLOBL ·unprefixed_once(SB), NOPTR, $16

GLOBL ·unprefixed_once_count(SB), NOPTR, $4

DATA c2go_global_gcmask·unprefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·unprefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·1617295a1dc6485e(SB)
DATA gclocals·1617295a1dc6485e+0(SB)/4, $2
DATA gclocals·1617295a1dc6485e+4(SB)/4, $9
DATA gclocals·1617295a1dc6485e+8(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+9(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+10(SB)/1, $0x80
DATA gclocals·1617295a1dc6485e+11(SB)/1, $0x00
GLOBL gclocals·1617295a1dc6485e(SB), DUPOK|RODATA, $12
