// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_dirent_unprefixed_selftest(SB), $344-8
	PCDATA $1, $-1
	LONG $0xf045c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ _L_str<>(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_opendir(SB)
_Ltmp0:
	MOVQ SP, AX
	MOVQ 8(AX), AX
	LONG $0xf045c748
	LONG $0x00000000
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB0_8
	MOVQ AX, -8(BP)
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp1:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp2:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	MOVL $2, AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB0_9
	LONG $0x1351b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_10
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_4:
	LONG $0x071c3a42
	MOVQ DI, DX
	JNE _LBB0_7
	MOVL SI, DX
	LONG $0x115cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_4
	XORL CX, CX
	MOVL CX, BX
_LBB0_7:
	LONG $0x021c3a42
	JNE _LBB0_9
	JMP _LBB0_11
_LBB0_8:
	MOVL $1, AX
_LBB0_9:
	MOVL AX, 16(BP)
	RET
_LBB0_10:
	XORL CX, CX
	MOVL CX, DX
	MOVL CX, BX
	LEAQ _L_str<>(SB), R8
	LONG $0x021c3a42
	JNE _LBB0_9
_LBB0_11:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir(SB)
_Ltmp3:
	MOVQ SP, AX
	MOVQ 8(AX), CX
	MOVL $3, AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc9
	JEQ _LBB0_9
	LONG $0x1359b60f
	BYTE $0x84
	BYTE $0xdb
	JEQ _LBB0_17
	MOVL $1, DI
	XORL DX, DX
	MOVL DX, R8
	LEAQ _L_str_1<>(SB), DX
_LBB0_14:
	LONG $0x101c3a41
	MOVQ R8, SI
	JNE _LBB0_19
	MOVL DI, SI
	LONG $0x315cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc7
	MOVQ SI, R8
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_14
	XORL CX, CX
	JMP _LBB0_18
_LBB0_17:
	XORL CX, CX
	MOVL CX, SI
_LBB0_18:
	MOVL CX, BX
_LBB0_19:
	LEAQ _L_str_1<>(SB), CX
	BYTE $0x3a
	BYTE $0x1c
	BYTE $0x0e
	JNE _LBB0_9
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_rewinddir(SB)
_Ltmp4:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp5:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	LEAQ -16(BP), DX
	MOVQ DX, 16(CX)
	LEAQ -296(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_readdir_r(SB)
_Ltmp6:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x00187883
	MOVL CX, AX
	JNE _LBB0_9
	MOVQ -16(BP), CX
	MOVL $5, AX
	LEAQ -296(BP), DX
	BYTE $0x48
	BYTE $0x39
	BYTE $0xd1
	JNE _LBB0_9
	LONG $0x1351b60f
	BYTE $0x84
	BYTE $0xd2
	JEQ _LBB0_27
	MOVL $1, SI
	XORL DI, DI
	MOVL DX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_24:
	LONG $0x071c3a42
	MOVQ DI, DX
	JNE _LBB0_28
	MOVL SI, DX
	LONG $0x115cb60f
	BYTE $0x13
	BYTE $0xff
	BYTE $0xc6
	MOVQ DX, DI
	BYTE $0x84
	BYTE $0xdb
	JNE _LBB0_24
	XORL CX, CX
	MOVL CX, BX
	JMP _LBB0_28
_LBB0_27:
	XORL CX, CX
	MOVL CX, DX
	MOVL CX, BX
	LEAQ _L_str<>(SB), R8
_LBB0_28:
	LONG $0x021c3a42
	JNE _LBB0_9
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL github·com∕c2gohq∕c2go_libc∕mlib·mlib_closedir(SB)
_Ltmp7:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $10, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
	JMP _LBB0_9
_Lfunc_end0:
	FUNCDATA $0, gclocals·605edb4fa6e837b0(SB)
DATA gclocals·605edb4fa6e837b0+0(SB)/4, $4
DATA gclocals·605edb4fa6e837b0+4(SB)/4, $1
DATA gclocals·605edb4fa6e837b0+8(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+9(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+10(SB)/1, $0x00
DATA gclocals·605edb4fa6e837b0+11(SB)/1, $0x00
GLOBL gclocals·605edb4fa6e837b0(SB), DUPOK|RODATA, $12

	FUNCDATA $1, gclocals·8140324275b7f18a(SB)
DATA gclocals·8140324275b7f18a+0(SB)/4, $4
DATA gclocals·8140324275b7f18a+4(SB)/4, $43
DATA gclocals·8140324275b7f18a+8(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+9(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+10(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+11(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+12(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+13(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+14(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+15(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+16(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+17(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+18(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+19(SB)/1, $0x02
DATA gclocals·8140324275b7f18a+20(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+21(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+22(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+23(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+24(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+25(SB)/1, $0x06
DATA gclocals·8140324275b7f18a+26(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+27(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+28(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+29(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+30(SB)/1, $0x00
DATA gclocals·8140324275b7f18a+31(SB)/1, $0x04
GLOBL gclocals·8140324275b7f18a(SB), DUPOK|RODATA, $32

TEXT ·mlib_pthread_unprefixed_selftest(SB), $88-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xf045c748
	LONG $0x00000000
	LONG $0xd845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -40(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp8:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB1_2
	ADDL $10, AX
	JMP _LBB1_22
_LBB1_2:
	MOVQ SP, AX
	LEAQ ·unprefixed_global_mutex(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp9:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB1_4
	ADDL $20, AX
_LBB1_22:
	MOVL AX, 16(BP)
	RET
_LBB1_4:
	MOVQ SP, AX
	MOVQ ·_typeinfo_pthread_mutex_t(SB), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000008
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp10:
	MOVQ SP, AX
	MOVQ 16(AX), AX
	BYTE $0x48
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB1_5
	MOVQ AX, -48(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $3
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp11:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB1_8
	ADDL $30, AX
	JMP _LBB1_22
_LBB1_5:
	MOVL $30, AX
	JMP _LBB1_22
_LBB1_8:
	LONG $0xf845c748
	LONG $0x00000000
	LONG $0xf045c748
	LONG $0x00000000
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp12:
	MOVQ SP, AX
	MOVL $51, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB1_22
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp13:
	MOVQ SP, AX
	MOVL $52, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB1_22
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp14:
	MOVQ SP, AX
	MOVL $53, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_22
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp15:
	MOVQ SP, AX
	LEAQ -32(BP), CX
	MOVQ CX, 16(AX)
	LEAQ -8(BP), CX
	MOVQ CX, 8(AX)
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp16:
	MOVQ SP, AX
	MOVL $54, CX
	LONG $0x8a187881
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	MOVL CX, AX
	JNE _LBB1_22
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp17:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp18:
	MOVQ SP, AX
	MOVL $55, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_22
	MOVQ SP, AX
	LEAQ -16(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp19:
	MOVQ SP, AX
	MOVL $56, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_22
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp20:
	MOVQ SP, AX
	MOVL $57, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB1_22
	PCDATA $1, $0
	CALL ·exercise_unprefixed_rwlock(SB)
_Ltmp21:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB1_17
	ADDL $70, AX
	JMP _LBB1_22
_LBB1_17:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadSelf(SB)
_Ltmp22:
	MOVQ SP, AX
	MOVQ 0(AX), AX
	MOVQ SP, CX
	MOVQ AX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadEqual(SB)
_Ltmp23:
	MOVQ SP, AX
	LONG $0x00107883
	JEQ _LBB1_18
	MOVQ SP, AX
	LEAQ ·unprefixed_once_init(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·unprefixed_once(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp24:
	MOVQ SP, AX
	MOVL $92, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB1_22
	MOVQ SP, AX
	LEAQ ·unprefixed_once_init(SB), CX
	MOVQ CX, 8(AX)
	LEAQ ·unprefixed_once(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp25:
	MOVQ SP, AX
	MOVL $93, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB1_22
	XORL AX, AX
	CMPL ·unprefixed_once_count(SB), $1
	MOVL $94, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
	JMP _LBB1_22
_LBB1_18:
	MOVL $91, AX
	JMP _LBB1_22
_Lfunc_end1:
	FUNCDATA $0, gclocals·4049a89979623773(SB)
DATA gclocals·4049a89979623773+0(SB)/4, $5
DATA gclocals·4049a89979623773+4(SB)/4, $1
DATA gclocals·4049a89979623773+8(SB)/1, $0x00
DATA gclocals·4049a89979623773+9(SB)/1, $0x00
DATA gclocals·4049a89979623773+10(SB)/1, $0x00
DATA gclocals·4049a89979623773+11(SB)/1, $0x00
DATA gclocals·4049a89979623773+12(SB)/1, $0x00
GLOBL gclocals·4049a89979623773(SB), DUPOK|RODATA, $13

	FUNCDATA $1, gclocals·bda3f787f14ed759(SB)
DATA gclocals·bda3f787f14ed759+0(SB)/4, $5
DATA gclocals·bda3f787f14ed759+4(SB)/4, $11
DATA gclocals·bda3f787f14ed759+8(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+9(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+10(SB)/1, $0x40
DATA gclocals·bda3f787f14ed759+11(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+12(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+13(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+14(SB)/1, $0x20
DATA gclocals·bda3f787f14ed759+15(SB)/1, $0x06
DATA gclocals·bda3f787f14ed759+16(SB)/1, $0x00
DATA gclocals·bda3f787f14ed759+17(SB)/1, $0x04
GLOBL gclocals·bda3f787f14ed759(SB), DUPOK|RODATA, $18

TEXT ·exercise_unprefixed_mutex(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -8(BP)
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	LONG $0x0841c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp26:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB2_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp27:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_6
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp28:
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp29:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB2_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp30:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x8a107881
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	MOVL CX, AX
	JNE _LBB2_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp31:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB2_6
	MOVQ -8(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp32:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $6, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB2_6:
	RET
_Lfunc_end2:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·17ca2a5a1f37de91(SB)
DATA gclocals·17ca2a5a1f37de91+0(SB)/4, $2
DATA gclocals·17ca2a5a1f37de91+4(SB)/4, $9
DATA gclocals·17ca2a5a1f37de91+8(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+9(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+10(SB)/1, $0x00
DATA gclocals·17ca2a5a1f37de91+11(SB)/1, $0x01
GLOBL gclocals·17ca2a5a1f37de91(SB), DUPOK|RODATA, $12

TEXT ·exercise_unprefixed_rwlock(SB), $40-0
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	LONG $0x0840c748
	LONG $0x00000000
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp33:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp34:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_8
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp35:
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp36:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp37:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp38:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp39:
	MOVQ SP, AX
	MOVL $6, CX
	LONG $0x10087883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp40:
	MOVQ SP, AX
	MOVL $7, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB3_8
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp41:
	MOVQ SP, AX
	XORL CX, CX
	LONG $0x00087883
	BYTE $0x0f
	BYTE $0x95
	BYTE $0xc0
	MOVB AL, CL
	SHLL $3, CX
	MOVL CX, AX
_LBB3_8:
	RET
_Lfunc_end3:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·4c2d44d481de39d2(SB)
DATA gclocals·4c2d44d481de39d2+0(SB)/4, $2
DATA gclocals·4c2d44d481de39d2+4(SB)/4, $5
DATA gclocals·4c2d44d481de39d2+8(SB)/1, $0x00
DATA gclocals·4c2d44d481de39d2+9(SB)/1, $0x10
GLOBL gclocals·4c2d44d481de39d2(SB), DUPOK|RODATA, $10

TEXT ·unprefixed_once_init(SB), $8-0
	PCDATA $1, $-1
	INCL ·unprefixed_once_count(SB)
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·89cd31291d2aefa4(SB)
DATA gclocals·89cd31291d2aefa4+0(SB)/4, $1
DATA gclocals·89cd31291d2aefa4+4(SB)/4, $0
GLOBL gclocals·89cd31291d2aefa4(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·5f4910070d449e0f(SB)
DATA gclocals·5f4910070d449e0f+0(SB)/4, $1
DATA gclocals·5f4910070d449e0f+4(SB)/4, $1
DATA gclocals·5f4910070d449e0f+8(SB)/1, $0x00
GLOBL gclocals·5f4910070d449e0f(SB), DUPOK|RODATA, $9

TEXT ·mlib_sem_unprefixed_selftest(SB), $24-8
	PCDATA $1, $-1
	LONG $0xf845c748
	LONG $0x00000000
	MOVQ SP, AX
	LEAQ -8(BP), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp42:
	BYTE $0x85
	BYTE $0xc0
	JEQ _LBB5_2
	ADDL $10, AX
	JMP _LBB5_3
_LBB5_2:
	MOVQ SP, AX
	LEAQ ·unprefixed_global_sem(SB), CX
	MOVQ CX, 0(AX)
	PCDATA $1, $0
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp43:
	MOVL AX, CX
	ADDL $20, CX
	BYTE $0x85
	BYTE $0xc0
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB5_3:
	MOVL AX, 16(BP)
	RET
_Lfunc_end5:
	FUNCDATA $0, gclocals·be86e5a039a56de6(SB)
DATA gclocals·be86e5a039a56de6+0(SB)/4, $2
DATA gclocals·be86e5a039a56de6+4(SB)/4, $1
DATA gclocals·be86e5a039a56de6+8(SB)/1, $0x00
DATA gclocals·be86e5a039a56de6+9(SB)/1, $0x00
GLOBL gclocals·be86e5a039a56de6(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·055a193a5dc1daa8(SB)
DATA gclocals·055a193a5dc1daa8+0(SB)/4, $2
DATA gclocals·055a193a5dc1daa8+4(SB)/4, $3
DATA gclocals·055a193a5dc1daa8+8(SB)/1, $0x00
DATA gclocals·055a193a5dc1daa8+9(SB)/1, $0x04
GLOBL gclocals·055a193a5dc1daa8(SB), DUPOK|RODATA, $10

TEXT ·exercise_unprefixed_sem(SB), $72-8
	PCDATA $1, $-1
	MOVQ 16(BP), AX
	LONG $0xfffc45c7
	BYTE $0xff
	BYTE $0xff
	BYTE $0xff
	BYTE $0x0f
	BYTE $0x57
	BYTE $0xc0
	MOVUPS X0, -32(BP)
	MOVQ AX, -16(BP)
	MOVQ SP, CX
	MOVQ $4294967296, DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp44:
	MOVQ SP, AX
	MOVL $1, CX
	LONG $0x00107883
	MOVL CX, AX
	JNE _LBB6_8
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp45:
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp46:
	MOVQ SP, AX
	MOVL $2, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB6_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -32(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp47:
	MOVQ SP, AX
	MOVL $3, CX
	LONG $0x8a107881
	BYTE $0x00
	BYTE $0x00
	BYTE $0x00
	MOVL CX, AX
	JNE _LBB6_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp48:
	MOVQ SP, AX
	MOVL $4, CX
	LONG $0x0b087883
	MOVL CX, AX
	JNE _LBB6_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp49:
	MOVQ SP, AX
	MOVL $5, CX
	LONG $0x00087883
	MOVL CX, AX
	JNE _LBB6_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	LEAQ -4(BP), DX
	MOVQ DX, 8(CX)
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp50:
	MOVQ SP, AX
	LONG $0x00107883
	MOVL $6, AX
	JNE _LBB6_8
	LONG $0x01fc7d83
	JNE _LBB6_8
	MOVQ -16(BP), AX
	MOVQ SP, CX
	MOVQ AX, 0(CX)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp51:
	MOVQ SP, AX
	MOVL 8(AX), AX
	BYTE $0x85
	BYTE $0xc0
	MOVL $7, CX
	BYTE $0x0f
	BYTE $0x44
	BYTE $0xc8
	MOVL CX, AX
_LBB6_8:
	RET
_Lfunc_end6:
DATA _L_str<>+0(SB)/1, $0x2e
DATA _L_str<>+1(SB)/1, $0x00
GLOBL _L_str<>(SB), RODATA, $2

DATA _L_str_1<>+0(SB)/1, $0x2e
DATA _L_str_1<>+1(SB)/1, $0x2e
DATA _L_str_1<>+2(SB)/1, $0x00
GLOBL _L_str_1<>(SB), RODATA, $3

GLOBL ·unprefixed_once(SB), NOPTR, $16

GLOBL ·unprefixed_once_count(SB), NOPTR, $4

DATA c2go_global_gcmask·unprefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·unprefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·1617295a1dc6485e(SB)
DATA gclocals·1617295a1dc6485e+0(SB)/4, $2
DATA gclocals·1617295a1dc6485e+4(SB)/4, $9
DATA gclocals·1617295a1dc6485e+8(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+9(SB)/1, $0x00
DATA gclocals·1617295a1dc6485e+10(SB)/1, $0x80
DATA gclocals·1617295a1dc6485e+11(SB)/1, $0x00
GLOBL gclocals·1617295a1dc6485e(SB), DUPOK|RODATA, $12
