// Code generated by clang (-fc2go-emit-plan9-asm); DO NOT EDIT.
#include "textflag.h"
#include "go_asm.h"

TEXT ·mlib_pthread_unprefixed_selftest(SB), $96-8
	PCDATA $1, $-1
	STP (ZR, ZR), 88(RSP)
	MOVD ZR, 64(RSP)
	MOVD RSP, R8
	ADD $64, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp0:
	CBZW R0, _LBB0_2
	ADDW $10, R0, R8
	JMP _LBB0_4
_LBB0_2:
	MOVD RSP, R8
	MOVD $·unprefixed_global_mutex(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp1:
	CBZW R0, _LBB0_5
	ADDW $20, R0, R8
_LBB0_4:
	MOVW R8, 120(RSP)
	RET
_LBB0_5:
	MOVD RSP, R8
	MOVW $8, R9
	MOVD ·_typeinfo_pthread_mutex_t(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc·GCMalloc(SB)
_Ltmp2:
	MOVD RSP, R8
	MOVD 24(R8), R8
	CBZ R8, _LBB0_8
	MOVD R8, 56(RSP)
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $3
	CALL ·exercise_unprefixed_mutex(SB)
_Ltmp3:
	CBZW R0, _LBB0_9
	ADDW $30, R0, R8
	JMP _LBB0_4
_LBB0_8:
	MOVW $30, R8
	JMP _LBB0_4
_LBB0_9:
	STP (ZR, ZR), 88(RSP)
	STP (ZR, ZR), 72(RSP)
	MOVD RSP, R9
	ADD $96, RSP, R10
	STP (R10, ZR), 8(R9)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp4:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_11
	MOVW $51, R8
	JMP _LBB0_4
_LBB0_11:
	MOVD RSP, R8
	ADD $88, RSP, R10
	STP (R10, ZR), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondInit(SB)
_Ltmp5:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_13
	MOVW $52, R8
	JMP _LBB0_4
_LBB0_13:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp6:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_15
	MOVW $53, R8
	JMP _LBB0_4
_LBB0_15:
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp7:
	MOVD RSP, R8
	ADD $72, RSP, R9
	MOVD R9, 24(R8)
	ADD $96, RSP, R9
	ADD $88, RSP, R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondTimedwait(SB)
_Ltmp8:
	MOVD RSP, R8
	MOVWU 32(R8), R8
	CMPW $60, R8
	BNE _LBB0_18
	PCDATA $1, $2
	CALL ·ForceGC(SB)
_Ltmp9:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp10:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_19
	MOVW $55, R8
	JMP _LBB0_4
_LBB0_18:
	MOVW $54, R8
	JMP _LBB0_4
_LBB0_19:
	MOVD RSP, R8
	ADD $88, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $2
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadCondDestroy(SB)
_Ltmp11:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_21
	MOVW $56, R8
	JMP _LBB0_4
_LBB0_21:
	MOVD RSP, R8
	ADD $96, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $4
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp12:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB0_23
	MOVW $57, R8
	JMP _LBB0_4
_LBB0_23:
	PCDATA $1, $0
	CALL ·exercise_unprefixed_rwlock(SB)
_Ltmp13:
	CBZW R0, _LBB0_25
	ADDW $70, R0, R8
	JMP _LBB0_4
_LBB0_25:
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadSelf(SB)
_Ltmp14:
	MOVD RSP, R8
	MOVD 8(R8), R8
	MOVD RSP, R9
	STP (R8, R8), 8(R9)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadEqual(SB)
_Ltmp15:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_28
	MOVD RSP, R8
	MOVD $·unprefixed_once_init(SB), R9
	MOVD $·unprefixed_once(SB), R10
	STP (R10, R9), 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp16:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_29
	MOVW $92, R8
	JMP _LBB0_4
_LBB0_28:
	MOVW $91, R8
	JMP _LBB0_4
_LBB0_29:
	MOVD RSP, R8
	MOVD $·unprefixed_once_init(SB), R10
	MOVD $·unprefixed_once(SB), R9
	STP (R9, R10), 8(R8)
	PCDATA $1, $0
	CALL github·com∕c2gohq∕c2go_libc·PthreadOnce(SB)
_Ltmp17:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB0_31
	MOVW $93, R8
	JMP _LBB0_4
_LBB0_31:
	MOVW ·unprefixed_once_count(SB), R9
	MOVW $94, R10
	CMPW $1, R9
	CSELW EQ, ZR, R10, R8
	JMP _LBB0_4
_Lfunc_end0:
	FUNCDATA $0, gclocals·4049a89979623773(SB)
DATA gclocals·4049a89979623773+0(SB)/4, $5
DATA gclocals·4049a89979623773+4(SB)/4, $1
DATA gclocals·4049a89979623773+8(SB)/1, $0x00
DATA gclocals·4049a89979623773+9(SB)/1, $0x00
DATA gclocals·4049a89979623773+10(SB)/1, $0x00
DATA gclocals·4049a89979623773+11(SB)/1, $0x00
DATA gclocals·4049a89979623773+12(SB)/1, $0x00
GLOBL gclocals·4049a89979623773(SB), DUPOK|RODATA, $13

	FUNCDATA $1, gclocals·02f27f998ecd3972(SB)
DATA gclocals·02f27f998ecd3972+0(SB)/4, $5
DATA gclocals·02f27f998ecd3972+4(SB)/4, $13
DATA gclocals·02f27f998ecd3972+8(SB)/1, $0x00
DATA gclocals·02f27f998ecd3972+9(SB)/1, $0x00
DATA gclocals·02f27f998ecd3972+10(SB)/1, $0x00
DATA gclocals·02f27f998ecd3972+11(SB)/1, $0x19
DATA gclocals·02f27f998ecd3972+12(SB)/1, $0x00
DATA gclocals·02f27f998ecd3972+13(SB)/1, $0x18
DATA gclocals·02f27f998ecd3972+14(SB)/1, $0x80
DATA gclocals·02f27f998ecd3972+15(SB)/1, $0x18
DATA gclocals·02f27f998ecd3972+16(SB)/1, $0x00
DATA gclocals·02f27f998ecd3972+17(SB)/1, $0x10
GLOBL gclocals·02f27f998ecd3972(SB), DUPOK|RODATA, $18

TEXT ·exercise_unprefixed_mutex(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	STP (ZR, ZR), 56(RSP)
	MOVD R9, 48(RSP)
	MOVD RSP, R10
	STP (R9, ZR), 8(R10)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexInit(SB)
_Ltmp18:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB1_2
	MOVW $1, R0
	JMP _LBB1_11
_LBB1_2:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexLock(SB)
_Ltmp19:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_4
	MOVW $2, R0
	JMP _LBB1_11
_LBB1_4:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp20:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTryLock(SB)
_Ltmp21:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB1_8
	MOVD 48(RSP), R8
	MOVD RSP, R9
	ADD $56, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexTimedlock(SB)
_Ltmp22:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $60, R8
	BNE _LBB1_9
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexUnlock(SB)
_Ltmp23:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB1_10
	MOVW $5, R0
	JMP _LBB1_11
_LBB1_8:
	MOVW $3, R0
	JMP _LBB1_11
_LBB1_9:
	MOVW $4, R0
	JMP _LBB1_11
_LBB1_10:
	MOVD 48(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadMutexDestroy(SB)
_Ltmp24:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $6, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
_LBB1_11:
	RET
_Lfunc_end1:
	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
DATA gclocals·be8a4aa039a84f5c+0(SB)/4, $2
DATA gclocals·be8a4aa039a84f5c+4(SB)/4, $1
DATA gclocals·be8a4aa039a84f5c+8(SB)/1, $0x01
DATA gclocals·be8a4aa039a84f5c+9(SB)/1, $0x01
GLOBL gclocals·be8a4aa039a84f5c(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·18a3a95a1ff0a71e(SB)
DATA gclocals·18a3a95a1ff0a71e+0(SB)/4, $2
DATA gclocals·18a3a95a1ff0a71e+4(SB)/4, $9
DATA gclocals·18a3a95a1ff0a71e+8(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+9(SB)/1, $0x00
DATA gclocals·18a3a95a1ff0a71e+10(SB)/1, $0x40
DATA gclocals·18a3a95a1ff0a71e+11(SB)/1, $0x00
GLOBL gclocals·18a3a95a1ff0a71e(SB), DUPOK|RODATA, $12

TEXT ·exercise_unprefixed_rwlock(SB), $48-0
	PCDATA $1, $-1
	MOVD ZR, 48(RSP)
	MOVD RSP, R9
	ADD $48, RSP, R10
	STP (R10, ZR), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockInit(SB)
_Ltmp25:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB2_2
	MOVW $1, R0
	JMP _LBB2_8
_LBB2_2:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockRdlock(SB)
_Ltmp26:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_4
	MOVW $2, R0
	JMP _LBB2_8
_LBB2_4:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp27:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTrywrlock(SB)
_Ltmp28:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB2_7
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp29:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_9
	MOVW $4, R0
	JMP _LBB2_8
_LBB2_7:
	MOVW $3, R0
_LBB2_8:
	RET
_LBB2_9:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockWrlock(SB)
_Ltmp30:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_11
	MOVW $5, R0
	JMP _LBB2_8
_LBB2_11:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRwlockTryrdlock(SB)
_Ltmp31:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $16, R8
	BNE _LBB2_14
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockUnlock(SB)
_Ltmp32:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB2_15
	MOVW $7, R0
	JMP _LBB2_8
_LBB2_14:
	MOVW $6, R0
	JMP _LBB2_8
_LBB2_15:
	MOVD RSP, R8
	ADD $48, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·PthreadRWLockDestroy(SB)
_Ltmp33:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $8, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB2_8
_Lfunc_end2:
	FUNCDATA $0, gclocals·e6bd86443df8ce07(SB)
DATA gclocals·e6bd86443df8ce07+0(SB)/4, $2
DATA gclocals·e6bd86443df8ce07+4(SB)/4, $0
GLOBL gclocals·e6bd86443df8ce07(SB), DUPOK|RODATA, $8

	FUNCDATA $1, gclocals·9300cc6ea5fb3550(SB)
DATA gclocals·9300cc6ea5fb3550+0(SB)/4, $2
DATA gclocals·9300cc6ea5fb3550+4(SB)/4, $7
DATA gclocals·9300cc6ea5fb3550+8(SB)/1, $0x00
DATA gclocals·9300cc6ea5fb3550+9(SB)/1, $0x40
GLOBL gclocals·9300cc6ea5fb3550(SB), DUPOK|RODATA, $10

TEXT ·unprefixed_once_init(SB), NOSPLIT|NOFRAME, $0-0
	MOVW ·unprefixed_once_count(SB), R9
	ADDW $1, R9, R9
	MOVW R9, ·unprefixed_once_count(SB)
	RET
_Lfunc_end3:
TEXT ·mlib_sem_unprefixed_selftest(SB), $32-8
	PCDATA $1, $-1
	MOVD ZR, 32(RSP)
	MOVD RSP, R8
	ADD $32, RSP, R9
	MOVD R9, 8(R8)
	PCDATA $1, $1
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp34:
	CBZW R0, _LBB4_2
	ADDW $10, R0, R8
	JMP _LBB4_3
_LBB4_2:
	MOVD RSP, R8
	MOVD $·unprefixed_global_sem(SB), R9
	MOVD R9, 8(R8)
	PCDATA $1, $0
	CALL ·exercise_unprefixed_sem(SB)
_Ltmp35:
	ADDW $20, R0, R9
	CMPW $0, R0
	CSELW EQ, ZR, R9, R8
_LBB4_3:
	MOVW R8, 56(RSP)
	RET
_Lfunc_end4:
	FUNCDATA $0, gclocals·be86e5a039a56de6(SB)
DATA gclocals·be86e5a039a56de6+0(SB)/4, $2
DATA gclocals·be86e5a039a56de6+4(SB)/4, $1
DATA gclocals·be86e5a039a56de6+8(SB)/1, $0x00
DATA gclocals·be86e5a039a56de6+9(SB)/1, $0x00
GLOBL gclocals·be86e5a039a56de6(SB), DUPOK|RODATA, $10

	FUNCDATA $1, gclocals·4c2d44d481de39d2(SB)
DATA gclocals·4c2d44d481de39d2+0(SB)/4, $2
DATA gclocals·4c2d44d481de39d2+4(SB)/4, $5
DATA gclocals·4c2d44d481de39d2+8(SB)/1, $0x00
DATA gclocals·4c2d44d481de39d2+9(SB)/1, $0x10
GLOBL gclocals·4c2d44d481de39d2(SB), DUPOK|RODATA, $10

TEXT ·exercise_unprefixed_sem(SB), $64-8
	PCDATA $1, $-1
	MOVD 88(RSP), R9
	MOVW $-1, R10
	MOVW R10, 68(RSP)
	STP (ZR, ZR), 48(RSP)
	MOVD R9, 40(RSP)
	MOVD RSP, R8
	MOVD $4294967296, R10
	STP (R9, R10), 8(R8)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemInit(SB)
_Ltmp36:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CBZW R8, _LBB5_2
	MOVW $1, R0
	JMP _LBB5_10
_LBB5_2:
	PCDATA $1, $1
	CALL ·ForceGC(SB)
_Ltmp37:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemWait(SB)
_Ltmp38:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_4
	MOVW $2, R0
	JMP _LBB5_10
_LBB5_4:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $48, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTimedwait(SB)
_Ltmp39:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	CMPW $60, R8
	BNE _LBB5_8
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemTrywait(SB)
_Ltmp40:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CMPW $35, R8
	BNE _LBB5_9
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemPost(SB)
_Ltmp41:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	CBZW R8, _LBB5_11
	MOVW $5, R0
	JMP _LBB5_10
_LBB5_8:
	MOVW $3, R0
	JMP _LBB5_10
_LBB5_9:
	MOVW $4, R0
_LBB5_10:
	RET
_LBB5_11:
	MOVD 40(RSP), R8
	MOVD RSP, R9
	ADD $68, RSP, R10
	STP (R8, R10), 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemGetvalue(SB)
_Ltmp42:
	MOVD RSP, R8
	MOVWU 24(R8), R8
	MOVW $6, R0
	CBNZW R8, _LBB5_10
	MOVWU 68(RSP), R8
	CMPW $1, R8
	BNE _LBB5_10
	MOVD 40(RSP), R8
	MOVD RSP, R9
	MOVD R8, 8(R9)
	PCDATA $1, $1
	CALL github·com∕c2gohq∕c2go_libc∕mlib·SemDestroy(SB)
_Ltmp43:
	MOVD RSP, R8
	MOVWU 16(R8), R8
	MOVW $7, R10
	CMPW $0, R8
	CSELW EQ, ZR, R10, R0
	JMP _LBB5_10
_Lfunc_end5:
GLOBL ·unprefixed_once(SB), NOPTR, $16

GLOBL ·unprefixed_once_count(SB), NOPTR, $4

DATA c2go_global_gcmask·unprefixed_global_mutex+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_mutex(SB), RODATA, $1

DATA c2go_global_gcmask·unprefixed_global_sem+0(SB)/1, $0x01
GLOBL c2go_global_gcmask·unprefixed_global_sem(SB), RODATA, $1

	FUNCDATA $0, gclocals·be8a4aa039a84f5c(SB)
	FUNCDATA $1, gclocals·175d695a1edb77be(SB)
DATA gclocals·175d695a1edb77be+0(SB)/4, $2
DATA gclocals·175d695a1edb77be+4(SB)/4, $9
DATA gclocals·175d695a1edb77be+8(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+9(SB)/1, $0x00
DATA gclocals·175d695a1edb77be+10(SB)/1, $0x20
DATA gclocals·175d695a1edb77be+11(SB)/1, $0x00
GLOBL gclocals·175d695a1edb77be(SB), DUPOK|RODATA, $12
